"""UHSC V2 store-queue address and data families.
昆明湖 V2 存储队列地址与数据 family。

StoreQueueData.scala contains four generated specializations.  This aggregate
keeps their flattened ports exact while sharing the source's banked registers,
registered reads, masked writes, and forwarding CAM equations.
"""

from __future__ import annotations

from typing import Any, cast

from amaranth import Array, ClockDomain, Const, Elaboratable, Module, Mux, Signal
from amaranth.back import verilog


# =============================================================================
# Module Contract
# =============================================================================
__all__ = ["COVERED_MODULES", "StoreQueueDataFamily", "build_verilog", "main"]

COVERED_MODULES: tuple[str, ...] = (
    "SQAddrModule", "SQAddrModule_1", "SQData8Module", "SQDataModule",
)
SOURCE_PATHS: tuple[str, ...] = (
    "upstream/src/main/scala/xiangshan/mem/lsqueue/StoreQueueData.scala",
)


# =============================================================================
# Configuration
# =============================================================================
def addr_specs(data_width: int, include_read_lineflag: bool) -> tuple[tuple[str, str, int], ...]:
    """Construct an SQAddr port surface. / 构造 SQAddr 端口表面。"""

    ports: list[tuple[str, str, int]] = [("clock", "input", 1), ("reset", "input", 1)]
    for index in range(2):
        ports.extend(((f"io_raddr_{index}", "input", 6), (f"io_rdata_{index}", "output", data_width)))
    if include_read_lineflag:
        ports.extend((f"io_rlineflag_{index}", "output", 1) for index in range(2))
    for index in range(2):
        ports.extend(((f"io_wen_{index}", "input", 1), (f"io_waddr_{index}", "input", 6),
                      (f"io_wdata_{index}", "input", data_width), (f"io_wmask_{index}", "input", 16)))
        ports.append((f"io_wlineflag_{index}", "input", 1))
    for index in range(3):
        ports.extend(((f"io_forwardMdata_{index}", "input", data_width),
                      (f"io_forwardDataMask_{index}", "input", 16)))
    for forward in range(3):
        for entry in range(56):
            ports.append((f"io_forwardMmask_{forward}_{entry}", "output", 1))
    return tuple(ports)


def data8_specs() -> tuple[tuple[str, str, int], ...]:
    """Construct the byte data-array port surface. / 构造字节数据阵列端口表面。"""

    ports: list[tuple[str, str, int]] = [("clock", "input", 1), ("reset", "input", 1)]
    for index in range(2):
        ports.extend(((f"io_raddr_{index}", "input", 6), (f"io_rdata_{index}_valid", "output", 1),
                      (f"io_rdata_{index}_data", "output", 8)))
    for index in range(2):
        ports.extend(((f"io_data_wen_{index}", "input", 1), (f"io_data_waddr_{index}", "input", 6),
                      (f"io_data_wdata_{index}", "input", 8), (f"io_mask_wen_{index}", "input", 1),
                      (f"io_mask_waddr_{index}", "input", 6), (f"io_mask_wdata_{index}", "input", 1)))
    for forward in range(3):
        for half in range(2):
            ports.append((f"io_needForward_{forward}_{half}", "input", 56))
    for forward in range(3):
        ports.extend(((f"io_forwardValid_{forward}", "output", 1),
                      (f"io_forwardData_{forward}", "output", 8)))
    return tuple(ports)


def data_specs() -> tuple[tuple[str, str, int], ...]:
    """Construct the 128-bit data-array port surface. / 构造 128 位数据阵列端口表面。"""

    ports: list[tuple[str, str, int]] = [("clock", "input", 1), ("reset", "input", 1)]
    for index in range(2):
        ports.extend(((f"io_raddr_{index}", "input", 6), (f"io_rdata_{index}_mask", "output", 16),
                      (f"io_rdata_{index}_data", "output", 128)))
    for index in range(2):
        ports.extend(((f"io_data_wen_{index}", "input", 1), (f"io_data_waddr_{index}", "input", 6),
                      (f"io_data_wdata_{index}", "input", 128), (f"io_mask_wen_{index}", "input", 1),
                      (f"io_mask_waddr_{index}", "input", 6), (f"io_mask_wdata_{index}", "input", 16)))
    for forward in range(3):
        for half in range(2):
            ports.append((f"io_needForward_{forward}_{half}", "input", 56))
    for forward in range(3):
        for byte in range(16):
            ports.append((f"io_forwardMask_{forward}_{byte}", "output", 1))
        for byte in range(16):
            ports.append((f"io_forwardData_{forward}_{byte}", "output", 8))
    return tuple(ports)


PORT_SPECS: dict[str, tuple[tuple[str, str, int], ...]] = {
    "SQAddrModule": addr_specs(48, True),
    "SQAddrModule_1": addr_specs(50, False),
    "SQData8Module": data8_specs(),
    "SQDataModule": data_specs(),
}

# BEGIN LOCKED PORT CATALOG
# Exact V2 ANSI names, directions, widths, and declaration order. / 精确 V2 ANSI 名称、方向、位宽与声明顺序。
LOCKED_PORT_SPECS: dict[str, tuple[tuple[str, str, int], ...]] = {
    "SQAddrModule": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "reset",
            "input",
            1,
        ),
        (
            "io_raddr_0",
            "input",
            6,
        ),
        (
            "io_raddr_1",
            "input",
            6,
        ),
        (
            "io_rdata_0",
            "output",
            48,
        ),
        (
            "io_rdata_1",
            "output",
            48,
        ),
        (
            "io_rlineflag_0",
            "output",
            1,
        ),
        (
            "io_rlineflag_1",
            "output",
            1,
        ),
        (
            "io_wen_0",
            "input",
            1,
        ),
        (
            "io_wen_1",
            "input",
            1,
        ),
        (
            "io_waddr_0",
            "input",
            6,
        ),
        (
            "io_waddr_1",
            "input",
            6,
        ),
        (
            "io_wdata_0",
            "input",
            48,
        ),
        (
            "io_wdata_1",
            "input",
            48,
        ),
        (
            "io_wmask_0",
            "input",
            16,
        ),
        (
            "io_wmask_1",
            "input",
            16,
        ),
        (
            "io_wlineflag_0",
            "input",
            1,
        ),
        (
            "io_wlineflag_1",
            "input",
            1,
        ),
        (
            "io_forwardMdata_0",
            "input",
            48,
        ),
        (
            "io_forwardMdata_1",
            "input",
            48,
        ),
        (
            "io_forwardMdata_2",
            "input",
            48,
        ),
        (
            "io_forwardDataMask_0",
            "input",
            16,
        ),
        (
            "io_forwardDataMask_1",
            "input",
            16,
        ),
        (
            "io_forwardDataMask_2",
            "input",
            16,
        ),
        (
            "io_forwardMmask_0_0",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_1",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_2",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_3",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_4",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_5",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_6",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_7",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_8",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_9",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_10",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_11",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_12",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_13",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_14",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_15",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_16",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_17",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_18",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_19",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_20",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_21",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_22",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_23",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_24",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_25",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_26",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_27",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_28",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_29",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_30",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_31",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_32",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_33",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_34",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_35",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_36",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_37",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_38",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_39",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_40",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_41",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_42",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_43",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_44",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_45",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_46",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_47",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_48",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_49",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_50",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_51",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_52",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_53",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_54",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_55",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_0",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_1",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_2",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_3",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_4",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_5",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_6",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_7",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_8",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_9",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_10",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_11",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_12",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_13",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_14",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_15",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_16",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_17",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_18",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_19",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_20",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_21",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_22",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_23",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_24",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_25",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_26",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_27",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_28",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_29",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_30",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_31",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_32",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_33",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_34",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_35",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_36",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_37",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_38",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_39",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_40",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_41",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_42",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_43",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_44",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_45",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_46",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_47",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_48",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_49",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_50",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_51",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_52",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_53",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_54",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_55",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_0",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_1",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_2",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_3",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_4",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_5",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_6",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_7",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_8",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_9",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_10",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_11",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_12",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_13",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_14",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_15",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_16",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_17",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_18",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_19",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_20",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_21",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_22",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_23",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_24",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_25",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_26",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_27",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_28",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_29",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_30",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_31",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_32",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_33",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_34",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_35",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_36",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_37",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_38",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_39",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_40",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_41",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_42",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_43",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_44",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_45",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_46",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_47",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_48",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_49",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_50",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_51",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_52",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_53",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_54",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_55",
            "output",
            1,
        ),
    ),
    "SQAddrModule_1": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "reset",
            "input",
            1,
        ),
        (
            "io_raddr_0",
            "input",
            6,
        ),
        (
            "io_raddr_1",
            "input",
            6,
        ),
        (
            "io_rdata_0",
            "output",
            50,
        ),
        (
            "io_rdata_1",
            "output",
            50,
        ),
        (
            "io_wen_0",
            "input",
            1,
        ),
        (
            "io_wen_1",
            "input",
            1,
        ),
        (
            "io_waddr_0",
            "input",
            6,
        ),
        (
            "io_waddr_1",
            "input",
            6,
        ),
        (
            "io_wdata_0",
            "input",
            50,
        ),
        (
            "io_wdata_1",
            "input",
            50,
        ),
        (
            "io_wmask_0",
            "input",
            16,
        ),
        (
            "io_wmask_1",
            "input",
            16,
        ),
        (
            "io_wlineflag_0",
            "input",
            1,
        ),
        (
            "io_wlineflag_1",
            "input",
            1,
        ),
        (
            "io_forwardMdata_0",
            "input",
            50,
        ),
        (
            "io_forwardMdata_1",
            "input",
            50,
        ),
        (
            "io_forwardMdata_2",
            "input",
            50,
        ),
        (
            "io_forwardDataMask_0",
            "input",
            16,
        ),
        (
            "io_forwardDataMask_1",
            "input",
            16,
        ),
        (
            "io_forwardDataMask_2",
            "input",
            16,
        ),
        (
            "io_forwardMmask_0_0",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_1",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_2",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_3",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_4",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_5",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_6",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_7",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_8",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_9",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_10",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_11",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_12",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_13",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_14",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_15",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_16",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_17",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_18",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_19",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_20",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_21",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_22",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_23",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_24",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_25",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_26",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_27",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_28",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_29",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_30",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_31",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_32",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_33",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_34",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_35",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_36",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_37",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_38",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_39",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_40",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_41",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_42",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_43",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_44",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_45",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_46",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_47",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_48",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_49",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_50",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_51",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_52",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_53",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_54",
            "output",
            1,
        ),
        (
            "io_forwardMmask_0_55",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_0",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_1",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_2",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_3",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_4",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_5",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_6",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_7",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_8",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_9",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_10",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_11",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_12",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_13",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_14",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_15",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_16",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_17",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_18",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_19",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_20",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_21",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_22",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_23",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_24",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_25",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_26",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_27",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_28",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_29",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_30",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_31",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_32",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_33",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_34",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_35",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_36",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_37",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_38",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_39",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_40",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_41",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_42",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_43",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_44",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_45",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_46",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_47",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_48",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_49",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_50",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_51",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_52",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_53",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_54",
            "output",
            1,
        ),
        (
            "io_forwardMmask_1_55",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_0",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_1",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_2",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_3",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_4",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_5",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_6",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_7",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_8",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_9",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_10",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_11",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_12",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_13",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_14",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_15",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_16",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_17",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_18",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_19",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_20",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_21",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_22",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_23",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_24",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_25",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_26",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_27",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_28",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_29",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_30",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_31",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_32",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_33",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_34",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_35",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_36",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_37",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_38",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_39",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_40",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_41",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_42",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_43",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_44",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_45",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_46",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_47",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_48",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_49",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_50",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_51",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_52",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_53",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_54",
            "output",
            1,
        ),
        (
            "io_forwardMmask_2_55",
            "output",
            1,
        ),
    ),
    "SQData8Module": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "reset",
            "input",
            1,
        ),
        (
            "io_raddr_0",
            "input",
            6,
        ),
        (
            "io_raddr_1",
            "input",
            6,
        ),
        (
            "io_rdata_0_valid",
            "output",
            1,
        ),
        (
            "io_rdata_0_data",
            "output",
            8,
        ),
        (
            "io_rdata_1_valid",
            "output",
            1,
        ),
        (
            "io_rdata_1_data",
            "output",
            8,
        ),
        (
            "io_data_wen_0",
            "input",
            1,
        ),
        (
            "io_data_wen_1",
            "input",
            1,
        ),
        (
            "io_data_waddr_0",
            "input",
            6,
        ),
        (
            "io_data_waddr_1",
            "input",
            6,
        ),
        (
            "io_data_wdata_0",
            "input",
            8,
        ),
        (
            "io_data_wdata_1",
            "input",
            8,
        ),
        (
            "io_mask_wen_0",
            "input",
            1,
        ),
        (
            "io_mask_wen_1",
            "input",
            1,
        ),
        (
            "io_mask_waddr_0",
            "input",
            6,
        ),
        (
            "io_mask_waddr_1",
            "input",
            6,
        ),
        (
            "io_mask_wdata_0",
            "input",
            1,
        ),
        (
            "io_mask_wdata_1",
            "input",
            1,
        ),
        (
            "io_needForward_0_0",
            "input",
            56,
        ),
        (
            "io_needForward_0_1",
            "input",
            56,
        ),
        (
            "io_needForward_1_0",
            "input",
            56,
        ),
        (
            "io_needForward_1_1",
            "input",
            56,
        ),
        (
            "io_needForward_2_0",
            "input",
            56,
        ),
        (
            "io_needForward_2_1",
            "input",
            56,
        ),
        (
            "io_forwardValid_0",
            "output",
            1,
        ),
        (
            "io_forwardValid_1",
            "output",
            1,
        ),
        (
            "io_forwardValid_2",
            "output",
            1,
        ),
        (
            "io_forwardData_0",
            "output",
            8,
        ),
        (
            "io_forwardData_1",
            "output",
            8,
        ),
        (
            "io_forwardData_2",
            "output",
            8,
        ),
    ),
    "SQDataModule": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "reset",
            "input",
            1,
        ),
        (
            "io_raddr_0",
            "input",
            6,
        ),
        (
            "io_raddr_1",
            "input",
            6,
        ),
        (
            "io_rdata_0_mask",
            "output",
            16,
        ),
        (
            "io_rdata_0_data",
            "output",
            128,
        ),
        (
            "io_rdata_1_mask",
            "output",
            16,
        ),
        (
            "io_rdata_1_data",
            "output",
            128,
        ),
        (
            "io_data_wen_0",
            "input",
            1,
        ),
        (
            "io_data_wen_1",
            "input",
            1,
        ),
        (
            "io_data_waddr_0",
            "input",
            6,
        ),
        (
            "io_data_waddr_1",
            "input",
            6,
        ),
        (
            "io_data_wdata_0",
            "input",
            128,
        ),
        (
            "io_data_wdata_1",
            "input",
            128,
        ),
        (
            "io_mask_wen_0",
            "input",
            1,
        ),
        (
            "io_mask_wen_1",
            "input",
            1,
        ),
        (
            "io_mask_waddr_0",
            "input",
            6,
        ),
        (
            "io_mask_waddr_1",
            "input",
            6,
        ),
        (
            "io_mask_wdata_0",
            "input",
            16,
        ),
        (
            "io_mask_wdata_1",
            "input",
            16,
        ),
        (
            "io_needForward_0_0",
            "input",
            56,
        ),
        (
            "io_needForward_0_1",
            "input",
            56,
        ),
        (
            "io_needForward_1_0",
            "input",
            56,
        ),
        (
            "io_needForward_1_1",
            "input",
            56,
        ),
        (
            "io_needForward_2_0",
            "input",
            56,
        ),
        (
            "io_needForward_2_1",
            "input",
            56,
        ),
        (
            "io_forwardMask_0_0",
            "output",
            1,
        ),
        (
            "io_forwardMask_0_1",
            "output",
            1,
        ),
        (
            "io_forwardMask_0_2",
            "output",
            1,
        ),
        (
            "io_forwardMask_0_3",
            "output",
            1,
        ),
        (
            "io_forwardMask_0_4",
            "output",
            1,
        ),
        (
            "io_forwardMask_0_5",
            "output",
            1,
        ),
        (
            "io_forwardMask_0_6",
            "output",
            1,
        ),
        (
            "io_forwardMask_0_7",
            "output",
            1,
        ),
        (
            "io_forwardMask_0_8",
            "output",
            1,
        ),
        (
            "io_forwardMask_0_9",
            "output",
            1,
        ),
        (
            "io_forwardMask_0_10",
            "output",
            1,
        ),
        (
            "io_forwardMask_0_11",
            "output",
            1,
        ),
        (
            "io_forwardMask_0_12",
            "output",
            1,
        ),
        (
            "io_forwardMask_0_13",
            "output",
            1,
        ),
        (
            "io_forwardMask_0_14",
            "output",
            1,
        ),
        (
            "io_forwardMask_0_15",
            "output",
            1,
        ),
        (
            "io_forwardMask_1_0",
            "output",
            1,
        ),
        (
            "io_forwardMask_1_1",
            "output",
            1,
        ),
        (
            "io_forwardMask_1_2",
            "output",
            1,
        ),
        (
            "io_forwardMask_1_3",
            "output",
            1,
        ),
        (
            "io_forwardMask_1_4",
            "output",
            1,
        ),
        (
            "io_forwardMask_1_5",
            "output",
            1,
        ),
        (
            "io_forwardMask_1_6",
            "output",
            1,
        ),
        (
            "io_forwardMask_1_7",
            "output",
            1,
        ),
        (
            "io_forwardMask_1_8",
            "output",
            1,
        ),
        (
            "io_forwardMask_1_9",
            "output",
            1,
        ),
        (
            "io_forwardMask_1_10",
            "output",
            1,
        ),
        (
            "io_forwardMask_1_11",
            "output",
            1,
        ),
        (
            "io_forwardMask_1_12",
            "output",
            1,
        ),
        (
            "io_forwardMask_1_13",
            "output",
            1,
        ),
        (
            "io_forwardMask_1_14",
            "output",
            1,
        ),
        (
            "io_forwardMask_1_15",
            "output",
            1,
        ),
        (
            "io_forwardMask_2_0",
            "output",
            1,
        ),
        (
            "io_forwardMask_2_1",
            "output",
            1,
        ),
        (
            "io_forwardMask_2_2",
            "output",
            1,
        ),
        (
            "io_forwardMask_2_3",
            "output",
            1,
        ),
        (
            "io_forwardMask_2_4",
            "output",
            1,
        ),
        (
            "io_forwardMask_2_5",
            "output",
            1,
        ),
        (
            "io_forwardMask_2_6",
            "output",
            1,
        ),
        (
            "io_forwardMask_2_7",
            "output",
            1,
        ),
        (
            "io_forwardMask_2_8",
            "output",
            1,
        ),
        (
            "io_forwardMask_2_9",
            "output",
            1,
        ),
        (
            "io_forwardMask_2_10",
            "output",
            1,
        ),
        (
            "io_forwardMask_2_11",
            "output",
            1,
        ),
        (
            "io_forwardMask_2_12",
            "output",
            1,
        ),
        (
            "io_forwardMask_2_13",
            "output",
            1,
        ),
        (
            "io_forwardMask_2_14",
            "output",
            1,
        ),
        (
            "io_forwardMask_2_15",
            "output",
            1,
        ),
        (
            "io_forwardData_0_0",
            "output",
            8,
        ),
        (
            "io_forwardData_0_1",
            "output",
            8,
        ),
        (
            "io_forwardData_0_2",
            "output",
            8,
        ),
        (
            "io_forwardData_0_3",
            "output",
            8,
        ),
        (
            "io_forwardData_0_4",
            "output",
            8,
        ),
        (
            "io_forwardData_0_5",
            "output",
            8,
        ),
        (
            "io_forwardData_0_6",
            "output",
            8,
        ),
        (
            "io_forwardData_0_7",
            "output",
            8,
        ),
        (
            "io_forwardData_0_8",
            "output",
            8,
        ),
        (
            "io_forwardData_0_9",
            "output",
            8,
        ),
        (
            "io_forwardData_0_10",
            "output",
            8,
        ),
        (
            "io_forwardData_0_11",
            "output",
            8,
        ),
        (
            "io_forwardData_0_12",
            "output",
            8,
        ),
        (
            "io_forwardData_0_13",
            "output",
            8,
        ),
        (
            "io_forwardData_0_14",
            "output",
            8,
        ),
        (
            "io_forwardData_0_15",
            "output",
            8,
        ),
        (
            "io_forwardData_1_0",
            "output",
            8,
        ),
        (
            "io_forwardData_1_1",
            "output",
            8,
        ),
        (
            "io_forwardData_1_2",
            "output",
            8,
        ),
        (
            "io_forwardData_1_3",
            "output",
            8,
        ),
        (
            "io_forwardData_1_4",
            "output",
            8,
        ),
        (
            "io_forwardData_1_5",
            "output",
            8,
        ),
        (
            "io_forwardData_1_6",
            "output",
            8,
        ),
        (
            "io_forwardData_1_7",
            "output",
            8,
        ),
        (
            "io_forwardData_1_8",
            "output",
            8,
        ),
        (
            "io_forwardData_1_9",
            "output",
            8,
        ),
        (
            "io_forwardData_1_10",
            "output",
            8,
        ),
        (
            "io_forwardData_1_11",
            "output",
            8,
        ),
        (
            "io_forwardData_1_12",
            "output",
            8,
        ),
        (
            "io_forwardData_1_13",
            "output",
            8,
        ),
        (
            "io_forwardData_1_14",
            "output",
            8,
        ),
        (
            "io_forwardData_1_15",
            "output",
            8,
        ),
        (
            "io_forwardData_2_0",
            "output",
            8,
        ),
        (
            "io_forwardData_2_1",
            "output",
            8,
        ),
        (
            "io_forwardData_2_2",
            "output",
            8,
        ),
        (
            "io_forwardData_2_3",
            "output",
            8,
        ),
        (
            "io_forwardData_2_4",
            "output",
            8,
        ),
        (
            "io_forwardData_2_5",
            "output",
            8,
        ),
        (
            "io_forwardData_2_6",
            "output",
            8,
        ),
        (
            "io_forwardData_2_7",
            "output",
            8,
        ),
        (
            "io_forwardData_2_8",
            "output",
            8,
        ),
        (
            "io_forwardData_2_9",
            "output",
            8,
        ),
        (
            "io_forwardData_2_10",
            "output",
            8,
        ),
        (
            "io_forwardData_2_11",
            "output",
            8,
        ),
        (
            "io_forwardData_2_12",
            "output",
            8,
        ),
        (
            "io_forwardData_2_13",
            "output",
            8,
        ),
        (
            "io_forwardData_2_14",
            "output",
            8,
        ),
        (
            "io_forwardData_2_15",
            "output",
            8,
        ),
    ),
}
PORT_SPECS = LOCKED_PORT_SPECS
# END LOCKED PORT CATALOG


# =============================================================================
# Implementation
# =============================================================================
class StoreQueueDataFamily(Elaboratable):
    """One selected StoreQueueData specialization. / 一个选定的存储队列数据特化。"""

    def __init__(self, member: str = "SQAddrModule") -> None:
        """Declare exact locked ports. / 声明精确锁定端口。"""

        if member not in PORT_SPECS:
            raise ValueError(f"unsupported store-queue member: {member}")
        self.member = member
        self.specs = PORT_SPECS[member]
        self.ports: dict[str, Signal] = {
            name: Signal(width, name=name) for name, _direction, width in self.specs
        }
        self.clock = self.ports["clock"]
        self.reset = self.ports["reset"]

    # Build an address CAM specialization. / 构建地址 CAM 特化。
    def elaborate_addr(self, module: Module) -> None:
        """Implement SQAddr reads, writes, and line-aware forwarding. / 实现 SQAddr 读写与按 cacheline 转发。"""

        data_width = 48 if self.member == "SQAddrModule" else 50
        memory = Array(Signal(data_width, name=f"addr_entry_{i}", reset_less=True) for i in range(56))
        line_flags = Array(Signal(name=f"lineflag_{i}", reset_less=True) for i in range(56))
        masks = Array(Signal(16, name=f"addr_mask_{i}", reset_less=True) for i in range(56))
        for write in range(2):
            with cast(Any, module.If(self.ports[f"io_wen_{write}"])):
                module.d.sync += [
                    memory[self.ports[f"io_waddr_{write}"]].eq(self.ports[f"io_wdata_{write}"]),
                    masks[self.ports[f"io_waddr_{write}"]].eq(self.ports[f"io_wmask_{write}"]),
                ]
                if self.member == "SQAddrModule":
                    module.d.sync += line_flags[self.ports[f"io_waddr_{write}"]].eq(self.ports[f"io_wlineflag_{write}"])
        for read in range(2):
            address = Signal(6, name=f"addr_read_{read}")
            with cast(Any, module.If(1)):
                module.d.sync += address.eq(self.ports[f"io_raddr_{read}"])
            module.d.comb += self.ports[f"io_rdata_{read}"].eq(memory[address])
            if self.member == "SQAddrModule":
                module.d.comb += self.ports[f"io_rlineflag_{read}"].eq(line_flags[address])
        for forward in range(3):
            query = self.ports[f"io_forwardMdata_{forward}"]
            query_mask = self.ports[f"io_forwardDataMask_{forward}"]
            for entry in range(56):
                line_hit = query[6:data_width] == memory[entry][6:data_width]
                word_hit = query[3:6] == memory[entry][3:6]
                mask_hit = (query_mask & masks[entry]) != 0
                if self.member == "SQAddrModule":
                    hit = line_hit & (line_flags[entry] | (word_hit & mask_hit))
                else:
                    hit = line_hit & (word_hit & mask_hit)
                module.d.comb += self.ports[f"io_forwardMmask_{forward}_{entry}"].eq(hit)

    # Build the byte-array specialization. / 构建字节阵列特化。
    def elaborate_data8(self, module: Module) -> None:
        """Implement byte writes, registered reads, and forwarding. / 实现字节写入、寄存读取与转发。"""

        data = Array(Signal(8, name=f"byte_data_{i}", reset_less=True) for i in range(56))
        valid = Array(Signal(name=f"byte_valid_{i}", reset_less=True) for i in range(56))
        read_addr = [Signal(6, name=f"byte_read_addr_{i}") for i in range(2)]
        for index in range(2):
            with cast(Any, module.If(1)):
                module.d.sync += read_addr[index].eq(self.ports[f"io_raddr_{index}"])
            module.d.comb += [
                self.ports[f"io_rdata_{index}_valid"].eq(valid[read_addr[index]]),
                self.ports[f"io_rdata_{index}_data"].eq(data[read_addr[index]]),
            ]
        for write in range(2):
            with cast(Any, module.If(self.ports[f"io_data_wen_{write}"])):
                module.d.sync += data[self.ports[f"io_data_waddr_{write}"]].eq(self.ports[f"io_data_wdata_{write}"])
            with cast(Any, module.If(self.ports[f"io_mask_wen_{write}"])):
                module.d.sync += valid[self.ports[f"io_mask_waddr_{write}"]].eq(self.ports[f"io_mask_wdata_{write}"])
        for forward in range(3):
            valid_expr: Any = Const(0, 1)
            selected: Any = Const(0, 8)
            for entry in range(56):
                match = (cast(Any, self.ports[f"io_needForward_{forward}_0"][entry]) |
                         cast(Any, self.ports[f"io_needForward_{forward}_1"][entry])) & valid[entry]
                valid_expr = valid_expr | match
                selected = Mux(match, data[entry], selected)
            module.d.comb += [
                self.ports[f"io_forwardValid_{forward}"].eq(valid_expr),
                self.ports[f"io_forwardData_{forward}"].eq(selected),
            ]

    # Build the 128-bit data specialization. / 构建 128 位数据特化。
    def elaborate_data(self, module: Module) -> None:
        """Implement masked data storage and 16-byte forwarding. / 实现带掩码数据存储及 16 字节转发。"""

        data = Array(Signal(128, name=f"store_data_{i}", reset_less=True) for i in range(56))
        masks = Array(Signal(16, name=f"store_mask_{i}", reset_less=True) for i in range(56))
        read_addr = [Signal(6, name=f"store_read_addr_{i}") for i in range(2)]
        for index in range(2):
            module.d.sync += read_addr[index].eq(self.ports[f"io_raddr_{index}"])
            module.d.comb += [
                self.ports[f"io_rdata_{index}_mask"].eq(masks[read_addr[index]]),
                self.ports[f"io_rdata_{index}_data"].eq(data[read_addr[index]]),
            ]
        for write in range(2):
            with cast(Any, module.If(self.ports[f"io_data_wen_{write}"])):
                module.d.sync += data[self.ports[f"io_data_waddr_{write}"]].eq(self.ports[f"io_data_wdata_{write}"])
            with cast(Any, module.If(self.ports[f"io_mask_wen_{write}"])):
                module.d.sync += masks[self.ports[f"io_mask_waddr_{write}"]].eq(self.ports[f"io_mask_wdata_{write}"])
        for forward in range(3):
            for byte in range(16):
                valid_expr: Any = Const(0, 1)
                data_expr: Any = Const(0, 8)
                for entry in range(56):
                    match = (cast(Any, self.ports[f"io_needForward_{forward}_0"][entry]) |
                             cast(Any, self.ports[f"io_needForward_{forward}_1"][entry])) & cast(Any, masks[entry][byte])
                    valid_expr = valid_expr | match
                    data_expr = Mux(match, data[entry][byte * 8:(byte + 1) * 8], data_expr)
                module.d.comb += [
                    self.ports[f"io_forwardMask_{forward}_{byte}"].eq(valid_expr),
                    self.ports[f"io_forwardData_{forward}_{byte}"].eq(data_expr),
                ]

    # Select the specialization implementation. / 选择特化实现。
    def elaborate(self, platform: Any) -> Module:
        """Elaborate one StoreQueueData member. / 展开一个 StoreQueueData 成员。"""

        del platform
        module = Module()
        domain = ClockDomain("sync", async_reset=True)
        domain.clk = self.clock
        domain.rst = self.reset
        module.domains += domain
        if self.member.startswith("SQAddr"):
            self.elaborate_addr(module)
        elif self.member == "SQData8Module":
            self.elaborate_data8(module)
        else:
            self.elaborate_data(module)
        return module


# =============================================================================
# Public Adapter
# =============================================================================
def build_verilog(configuration: Any, injected_dependencies: Any) -> str:
    """Export one deterministic same-name StoreQueueData member. / 导出确定性的同名存储队列成员。"""

    del injected_dependencies
    member = "SQAddrModule"
    if isinstance(configuration, dict):
        member = str(configuration.get("module", member))
    elif isinstance(configuration, str):
        member = configuration
    top = StoreQueueDataFamily(member)
    return verilog.convert(top, name=member, ports=[top.ports[n] for n, _d, _w in top.specs], emit_src=False)


# =============================================================================
# Direct Entry
# =============================================================================
def main() -> None:
    """Print the default SQ address member. / 打印默认 SQ 地址成员。"""

    print(build_verilog({"module": "SQAddrModule"}, {}))


if __name__ == "__main__":
    main()
