"""RISC-V CSR address constants (auto-generated from parse_opcodes). / RISC-V CSR 地址常量（由 parse_opcodes 自动生成）。"""

from __future__ import annotations

from typing import Any

from amaranth import Elaboratable, Module, Signal

# =============================================================================
# Module Contract
# =============================================================================
# =============================================================================
# Configuration
# =============================================================================
# =============================================================================
# Implementation
# =============================================================================
# =============================================================================
# Public Adapter
# =============================================================================
# =============================================================================
# Direct Entry
# =============================================================================



# =============================================================================
# =============================================================================
# Public symbols / 公开符号:
#   - CSRs : RISC-V CSR address constant collection (455 entries)
#   - build_verilog, main : minimal probe adapter
# Source: decode/isa/CSRs.scala (auto-generated by parse_opcodes).
# Pure constant table (no hardware).
# Status / 状态: PYTHON_PRESENT_UNVERIFIED (phase-1 bulk port / 阶段一批量重写)
__all__ = [
    "CSRs",
    "CSRConst",
    "CSRProbe",
    "csr_access_permission_check",
    "perfcnt_permission_check",
    "dcsr_permission_check",
    "trigger_permission_check",
    "build_verilog",
    "main",
]


# =============================================================================
# =============================================================================
# depends on Build-Cpu.Backend.Decode.Isa.CSRs (this file is the source)


# =============================================================================
# =============================================================================
class CSRs:
    # RISC-V CSR address constants / RISC-V CSR 地址常量
    fflags = 0x1
    frm = 0x2
    fcsr = 0x3
    vstart = 0x8
    vxsat = 0x9
    vxrm = 0xa
    vcsr = 0xf
    seed = 0x15
    jvt = 0x17
    cycle = 0xc00
    time = 0xc01
    instret = 0xc02
    hpmcounter3 = 0xc03
    hpmcounter4 = 0xc04
    hpmcounter5 = 0xc05
    hpmcounter6 = 0xc06
    hpmcounter7 = 0xc07
    hpmcounter8 = 0xc08
    hpmcounter9 = 0xc09
    hpmcounter10 = 0xc0a
    hpmcounter11 = 0xc0b
    hpmcounter12 = 0xc0c
    hpmcounter13 = 0xc0d
    hpmcounter14 = 0xc0e
    hpmcounter15 = 0xc0f
    hpmcounter16 = 0xc10
    hpmcounter17 = 0xc11
    hpmcounter18 = 0xc12
    hpmcounter19 = 0xc13
    hpmcounter20 = 0xc14
    hpmcounter21 = 0xc15
    hpmcounter22 = 0xc16
    hpmcounter23 = 0xc17
    hpmcounter24 = 0xc18
    hpmcounter25 = 0xc19
    hpmcounter26 = 0xc1a
    hpmcounter27 = 0xc1b
    hpmcounter28 = 0xc1c
    hpmcounter29 = 0xc1d
    hpmcounter30 = 0xc1e
    hpmcounter31 = 0xc1f
    vl = 0xc20
    vtype = 0xc21
    vlenb = 0xc22
    sstatus = 0x100
    sedeleg = 0x102
    sideleg = 0x103
    sie = 0x104
    stvec = 0x105
    scounteren = 0x106
    senvcfg = 0x10a
    sstateen0 = 0x10c
    sstateen1 = 0x10d
    sstateen2 = 0x10e
    sstateen3 = 0x10f
    sscratch = 0x140
    sepc = 0x141
    scause = 0x142
    stval = 0x143
    sip = 0x144
    stimecmp = 0x14d
    siselect = 0x150
    sireg = 0x151
    sireg2 = 0x152
    sireg3 = 0x153
    sireg4 = 0x155
    sireg5 = 0x156
    sireg6 = 0x157
    stopei = 0x15c
    satp = 0x180
    scontext = 0x5a8
    vsstatus = 0x200
    vsie = 0x204
    vstvec = 0x205
    vsscratch = 0x240
    vsepc = 0x241
    vscause = 0x242
    vstval = 0x243
    vsip = 0x244
    vstimecmp = 0x24d
    vsiselect = 0x250
    vsireg = 0x251
    vsireg2 = 0x252
    vsireg3 = 0x253
    vsireg4 = 0x255
    vsireg5 = 0x256
    vsireg6 = 0x257
    vstopei = 0x25c
    vsatp = 0x280
    hstatus = 0x600
    hedeleg = 0x602
    hideleg = 0x603
    hie = 0x604
    htimedelta = 0x605
    hcounteren = 0x606
    hgeie = 0x607
    hvien = 0x608
    hvictl = 0x609
    henvcfg = 0x60a
    hstateen0 = 0x60c
    hstateen1 = 0x60d
    hstateen2 = 0x60e
    hstateen3 = 0x60f
    htval = 0x643
    hip = 0x644
    hvip = 0x645
    hviprio1 = 0x646
    hviprio2 = 0x647
    htinst = 0x64a
    hgatp = 0x680
    hcontext = 0x6a8
    hgeip = 0xe12
    vstopi = 0xeb0
    scountovf = 0xda0
    stopi = 0xdb0
    utvt = 0x7
    unxti = 0x45
    uintstatus = 0x46
    uscratchcsw = 0x48
    uscratchcswl = 0x49
    stvt = 0x107
    snxti = 0x145
    sintstatus = 0x146
    sscratchcsw = 0x148
    sscratchcswl = 0x149
    mtvt = 0x307
    mnxti = 0x345
    mintstatus = 0x346
    mscratchcsw = 0x348
    mscratchcswl = 0x349
    mstatus = 0x300
    misa = 0x301
    medeleg = 0x302
    mideleg = 0x303
    mie = 0x304
    mtvec = 0x305
    mcounteren = 0x306
    mvien = 0x308
    mvip = 0x309
    menvcfg = 0x30a
    mstateen0 = 0x30c
    mstateen1 = 0x30d
    mstateen2 = 0x30e
    mstateen3 = 0x30f
    mcountinhibit = 0x320
    mscratch = 0x340
    mepc = 0x341
    mcause = 0x342
    mtval = 0x343
    mip = 0x344
    mtinst = 0x34a
    mtval2 = 0x34b
    miselect = 0x350
    mireg = 0x351
    mireg2 = 0x352
    mireg3 = 0x353
    mireg4 = 0x355
    mireg5 = 0x356
    mireg6 = 0x357
    mtopei = 0x35c
    pmpcfg0 = 0x3a0
    pmpcfg1 = 0x3a1
    pmpcfg2 = 0x3a2
    pmpcfg3 = 0x3a3
    pmpcfg4 = 0x3a4
    pmpcfg5 = 0x3a5
    pmpcfg6 = 0x3a6
    pmpcfg7 = 0x3a7
    pmpcfg8 = 0x3a8
    pmpcfg9 = 0x3a9
    pmpcfg10 = 0x3aa
    pmpcfg11 = 0x3ab
    pmpcfg12 = 0x3ac
    pmpcfg13 = 0x3ad
    pmpcfg14 = 0x3ae
    pmpcfg15 = 0x3af
    pmpaddr0 = 0x3b0
    pmpaddr1 = 0x3b1
    pmpaddr2 = 0x3b2
    pmpaddr3 = 0x3b3
    pmpaddr4 = 0x3b4
    pmpaddr5 = 0x3b5
    pmpaddr6 = 0x3b6
    pmpaddr7 = 0x3b7
    pmpaddr8 = 0x3b8
    pmpaddr9 = 0x3b9
    pmpaddr10 = 0x3ba
    pmpaddr11 = 0x3bb
    pmpaddr12 = 0x3bc
    pmpaddr13 = 0x3bd
    pmpaddr14 = 0x3be
    pmpaddr15 = 0x3bf
    pmpaddr16 = 0x3c0
    pmpaddr17 = 0x3c1
    pmpaddr18 = 0x3c2
    pmpaddr19 = 0x3c3
    pmpaddr20 = 0x3c4
    pmpaddr21 = 0x3c5
    pmpaddr22 = 0x3c6
    pmpaddr23 = 0x3c7
    pmpaddr24 = 0x3c8
    pmpaddr25 = 0x3c9
    pmpaddr26 = 0x3ca
    pmpaddr27 = 0x3cb
    pmpaddr28 = 0x3cc
    pmpaddr29 = 0x3cd
    pmpaddr30 = 0x3ce
    pmpaddr31 = 0x3cf
    pmpaddr32 = 0x3d0
    pmpaddr33 = 0x3d1
    pmpaddr34 = 0x3d2
    pmpaddr35 = 0x3d3
    pmpaddr36 = 0x3d4
    pmpaddr37 = 0x3d5
    pmpaddr38 = 0x3d6
    pmpaddr39 = 0x3d7
    pmpaddr40 = 0x3d8
    pmpaddr41 = 0x3d9
    pmpaddr42 = 0x3da
    pmpaddr43 = 0x3db
    pmpaddr44 = 0x3dc
    pmpaddr45 = 0x3dd
    pmpaddr46 = 0x3de
    pmpaddr47 = 0x3df
    pmpaddr48 = 0x3e0
    pmpaddr49 = 0x3e1
    pmpaddr50 = 0x3e2
    pmpaddr51 = 0x3e3
    pmpaddr52 = 0x3e4
    pmpaddr53 = 0x3e5
    pmpaddr54 = 0x3e6
    pmpaddr55 = 0x3e7
    pmpaddr56 = 0x3e8
    pmpaddr57 = 0x3e9
    pmpaddr58 = 0x3ea
    pmpaddr59 = 0x3eb
    pmpaddr60 = 0x3ec
    pmpaddr61 = 0x3ed
    pmpaddr62 = 0x3ee
    pmpaddr63 = 0x3ef
    mseccfg = 0x747
    tselect = 0x7a0
    tdata1 = 0x7a1
    tdata2 = 0x7a2
    tdata3 = 0x7a3
    tinfo = 0x7a4
    tcontrol = 0x7a5
    mcontext = 0x7a8
    mscontext = 0x7aa
    dcsr = 0x7b0
    dpc = 0x7b1
    dscratch0 = 0x7b2
    dscratch1 = 0x7b3
    mcycle = 0xb00
    minstret = 0xb02
    mhpmcounter3 = 0xb03
    mhpmcounter4 = 0xb04
    mhpmcounter5 = 0xb05
    mhpmcounter6 = 0xb06
    mhpmcounter7 = 0xb07
    mhpmcounter8 = 0xb08
    mhpmcounter9 = 0xb09
    mhpmcounter10 = 0xb0a
    mhpmcounter11 = 0xb0b
    mhpmcounter12 = 0xb0c
    mhpmcounter13 = 0xb0d
    mhpmcounter14 = 0xb0e
    mhpmcounter15 = 0xb0f
    mhpmcounter16 = 0xb10
    mhpmcounter17 = 0xb11
    mhpmcounter18 = 0xb12
    mhpmcounter19 = 0xb13
    mhpmcounter20 = 0xb14
    mhpmcounter21 = 0xb15
    mhpmcounter22 = 0xb16
    mhpmcounter23 = 0xb17
    mhpmcounter24 = 0xb18
    mhpmcounter25 = 0xb19
    mhpmcounter26 = 0xb1a
    mhpmcounter27 = 0xb1b
    mhpmcounter28 = 0xb1c
    mhpmcounter29 = 0xb1d
    mhpmcounter30 = 0xb1e
    mhpmcounter31 = 0xb1f
    mhpmevent3 = 0x323
    mhpmevent4 = 0x324
    mhpmevent5 = 0x325
    mhpmevent6 = 0x326
    mhpmevent7 = 0x327
    mhpmevent8 = 0x328
    mhpmevent9 = 0x329
    mhpmevent10 = 0x32a
    mhpmevent11 = 0x32b
    mhpmevent12 = 0x32c
    mhpmevent13 = 0x32d
    mhpmevent14 = 0x32e
    mhpmevent15 = 0x32f
    mhpmevent16 = 0x330
    mhpmevent17 = 0x331
    mhpmevent18 = 0x332
    mhpmevent19 = 0x333
    mhpmevent20 = 0x334
    mhpmevent21 = 0x335
    mhpmevent22 = 0x336
    mhpmevent23 = 0x337
    mhpmevent24 = 0x338
    mhpmevent25 = 0x339
    mhpmevent26 = 0x33a
    mhpmevent27 = 0x33b
    mhpmevent28 = 0x33c
    mhpmevent29 = 0x33d
    mhpmevent30 = 0x33e
    mhpmevent31 = 0x33f
    mvendorid = 0xf11
    marchid = 0xf12
    mimpid = 0xf13
    mhartid = 0xf14
    mconfigptr = 0xf15
    mtopi = 0xfb0
    sieh = 0x114
    siph = 0x154
    stimecmph = 0x15d
    vsieh = 0x214
    vsiph = 0x254
    vstimecmph = 0x25d
    htimedeltah = 0x615
    hidelegh = 0x613
    hvienh = 0x618
    henvcfgh = 0x61a
    hviph = 0x655
    hviprio1h = 0x656
    hviprio2h = 0x657
    hstateen0h = 0x61c
    hstateen1h = 0x61d
    hstateen2h = 0x61e
    hstateen3h = 0x61f
    cycleh = 0xc80
    timeh = 0xc81
    instreth = 0xc82
    hpmcounter3h = 0xc83
    hpmcounter4h = 0xc84
    hpmcounter5h = 0xc85
    hpmcounter6h = 0xc86
    hpmcounter7h = 0xc87
    hpmcounter8h = 0xc88
    hpmcounter9h = 0xc89
    hpmcounter10h = 0xc8a
    hpmcounter11h = 0xc8b
    hpmcounter12h = 0xc8c
    hpmcounter13h = 0xc8d
    hpmcounter14h = 0xc8e
    hpmcounter15h = 0xc8f
    hpmcounter16h = 0xc90
    hpmcounter17h = 0xc91
    hpmcounter18h = 0xc92
    hpmcounter19h = 0xc93
    hpmcounter20h = 0xc94
    hpmcounter21h = 0xc95
    hpmcounter22h = 0xc96
    hpmcounter23h = 0xc97
    hpmcounter24h = 0xc98
    hpmcounter25h = 0xc99
    hpmcounter26h = 0xc9a
    hpmcounter27h = 0xc9b
    hpmcounter28h = 0xc9c
    hpmcounter29h = 0xc9d
    hpmcounter30h = 0xc9e
    hpmcounter31h = 0xc9f
    mstatush = 0x310
    midelegh = 0x313
    mieh = 0x314
    mvienh = 0x318
    mviph = 0x319
    menvcfgh = 0x31a
    mstateen0h = 0x31c
    mstateen1h = 0x31d
    mstateen2h = 0x31e
    mstateen3h = 0x31f
    miph = 0x354
    mhpmevent3h = 0x723
    mhpmevent4h = 0x724
    mhpmevent5h = 0x725
    mhpmevent6h = 0x726
    mhpmevent7h = 0x727
    mhpmevent8h = 0x728
    mhpmevent9h = 0x729
    mhpmevent10h = 0x72a
    mhpmevent11h = 0x72b
    mhpmevent12h = 0x72c
    mhpmevent13h = 0x72d
    mhpmevent14h = 0x72e
    mhpmevent15h = 0x72f
    mhpmevent16h = 0x730
    mhpmevent17h = 0x731
    mhpmevent18h = 0x732
    mhpmevent19h = 0x733
    mhpmevent20h = 0x734
    mhpmevent21h = 0x735
    mhpmevent22h = 0x736
    mhpmevent23h = 0x737
    mhpmevent24h = 0x738
    mhpmevent25h = 0x739
    mhpmevent26h = 0x73a
    mhpmevent27h = 0x73b
    mhpmevent28h = 0x73c
    mhpmevent29h = 0x73d
    mhpmevent30h = 0x73e
    mhpmevent31h = 0x73f
    mnscratch = 0x740
    mnepc = 0x741
    mncause = 0x742
    mnstatus = 0x744
    mseccfgh = 0x757
    mcycleh = 0xb80
    minstreth = 0xb82
    mhpmcounter3h = 0xb83
    mhpmcounter4h = 0xb84
    mhpmcounter5h = 0xb85
    mhpmcounter6h = 0xb86
    mhpmcounter7h = 0xb87
    mhpmcounter8h = 0xb88
    mhpmcounter9h = 0xb89
    mhpmcounter10h = 0xb8a
    mhpmcounter11h = 0xb8b
    mhpmcounter12h = 0xb8c
    mhpmcounter13h = 0xb8d
    mhpmcounter14h = 0xb8e
    mhpmcounter15h = 0xb8f
    mhpmcounter16h = 0xb90
    mhpmcounter17h = 0xb91
    mhpmcounter18h = 0xb92
    mhpmcounter19h = 0xb93
    mhpmcounter20h = 0xb94
    mhpmcounter21h = 0xb95
    mhpmcounter22h = 0xb96
    mhpmcounter23h = 0xb97
    mhpmcounter24h = 0xb98
    mhpmcounter25h = 0xb99
    mhpmcounter26h = 0xb9a
    mhpmcounter27h = 0xb9b
    mhpmcounter28h = 0xb9c
    mhpmcounter29h = 0xb9d
    mhpmcounter30h = 0xb9e
    mhpmcounter31h = 0xb9f


# =============================================================================
# V2 custom CSR constants and permission helpers. / V2 自定义 CSR 常量与权限辅助函数。
class CSRConst:
    """Expose XiangShan's V2 CSRConst trait as pure Python values. / 以纯 Python 值暴露 V2 CSRConst trait。"""

    Sbpctl = 0x5C0
    Spfctl = 0x5C1
    Slvpredctl = 0x5C2
    Smblockctl = 0x5C3
    Srnctl = 0x5C4
    Scachebase = 0x5C5
    PmacfgBase = 0x7C0
    PmaaddrBase = 0x7C8
    Mbmc = 0xBC2

    Hgatp_Mode_len = 4
    Hgatp_Vmid_len = 16
    Hgatp_Addr_len = 44
    Satp_Mode_len = 4
    Satp_Asid_len = 16
    Satp_Addr_len = 44

    IRQ_USIP = 0
    IRQ_SSIP = 1
    IRQ_VSSIP = 2
    IRQ_MSIP = 3
    IRQ_UTIP = 4
    IRQ_STIP = 5
    IRQ_VSTIP = 6
    IRQ_MTIP = 7
    IRQ_UEIP = 8
    IRQ_SEIP = 9
    IRQ_VSEIP = 10
    IRQ_MEIP = 11
    IRQ_SGEIP = 12
    IRQ_DEBUG = 17

    ModeM = 0x3
    ModeH = 0x2
    ModeS = 0x1
    ModeU = 0x0
    IntPriority = (
        IRQ_DEBUG, IRQ_MEIP, IRQ_MSIP, IRQ_MTIP,
        IRQ_SEIP, IRQ_SSIP, IRQ_STIP, IRQ_UEIP, IRQ_USIP, IRQ_UTIP,
        IRQ_VSEIP, IRQ_VSSIP, IRQ_VSTIP, IRQ_SGEIP,
    )

    # Compute a SATP/PMA width mask. / 计算 SATP/PMA 位宽掩码。
    @staticmethod
    # Compute the width mask / 计算位宽掩码
    def satp_part_wmask(max_length: int, length: int) -> int:
        """Return the low ``length`` bits of a ``max_length`` mask. / 返回 max_length 掩码的低 length 位。"""

        if not 0 < length <= max_length:
            raise ValueError("length must be in (0, max_length]")
        return (1 << length) - 1

    # Check architectural CSR access permissions. / 检查架构 CSR 访问权限。
    @staticmethod
    # Check architectural CSR access / 检查架构 CSR 访问
    def csrAccessPermissionCheck(addr: int, wen: bool, mode: int,
                                 virt: bool, hasH: bool) -> int:
        """Return 0 normal, 1 illegal, or 2 virtual instruction. / 返回 0 正常、1 非法或 2 虚拟指令。"""

        read_only = ((addr >> 10) & 0x3) == 0x3
        lowest = (addr >> 8) & 0x3
        privilege = CSRConst.ModeH if mode == CSRConst.ModeS else mode
        if lowest == CSRConst.ModeH and not hasH:
            return 1
        if read_only and wen:
            return 1
        if privilege < lowest:
            return 2 if virt and lowest <= CSRConst.ModeH else 1
        return 0

    # Check performance-counter permissions. / 检查性能计数器权限。
    @staticmethod
    # Check performance-counter access / 检查性能计数器访问
    def perfcntPermissionCheck(addr: int, mode: int,
                               mmask: int, smask: int) -> bool:
        """Return whether the selected counter is accessible. / 返回选定计数器是否可访问。"""

        index = 1 << (addr & 31)
        if mode == CSRConst.ModeM:
            return True
        if mode == CSRConst.ModeS:
            return bool(index & mmask)
        return bool(index & mmask & smask)

    # Check debug CSR permissions. / 检查调试 CSR 权限。
    @staticmethod
    # Check debug access / 检查调试访问
    def dcsrPermissionCheck(addr: int, mModeCanWrite: bool,
                            debug: bool) -> bool:
        """Return whether a DCSR access is permitted. / 返回 DCSR 访问是否允许。"""

        is_debug_reg = ((addr >> 4) & 0xFF) == 0x7B
        return bool(mModeCanWrite or not is_debug_reg or debug)

    # Check trigger CSR permissions. / 检查触发器 CSR 权限。
    @staticmethod
    # Check trigger access / 检查触发器访问
    def triggerPermissionCheck(addr: int, mModeCanWrite: bool,
                               debug: bool) -> bool:
        """Return whether a trigger access is permitted. / 返回触发器访问是否允许。"""

        is_trigger_reg = ((addr >> 4) & 0xFF) == 0x7A
        return bool(mModeCanWrite or not is_trigger_reg or debug)


# Provide snake-case spellings for Python callers. / 为 Python 调用者提供下划线拼写。
# Alias wrappers retain the source semantics without importing sibling modules.
# Provide the snake-case CSR access spelling / 提供下划线 CSR 访问拼写
def csr_access_permission_check(addr: int, wen: bool, mode: int,
                                virt: bool, has_h: bool) -> int:
    """Call the V2 CSR permission checker. / 调用 V2 CSR 权限检查器。"""

    return CSRConst.csrAccessPermissionCheck(addr, wen, mode, virt, has_h)


# Check a performance counter through CSRConst. / 通过 CSRConst 检查性能计数器。
def perfcnt_permission_check(addr: int, mode: int,
                             mmask: int, smask: int) -> bool:
    """Call the V2 performance-counter checker. / 调用 V2 性能计数器检查器。"""

    return CSRConst.perfcntPermissionCheck(addr, mode, mmask, smask)


# Check debug access through CSRConst. / 通过 CSRConst 检查调试访问。
def dcsr_permission_check(addr: int, m_mode_can_write: bool,
                          debug: bool) -> bool:
    """Call the V2 debug permission checker. / 调用 V2 调试权限检查器。"""

    return CSRConst.dcsrPermissionCheck(addr, m_mode_can_write, debug)


# Check trigger access through CSRConst. / 通过 CSRConst 检查触发器访问。
def trigger_permission_check(addr: int, m_mode_can_write: bool,
                             debug: bool) -> bool:
    """Call the V2 trigger permission checker. / 调用 V2 触发器权限检查器。"""

    return CSRConst.triggerPermissionCheck(addr, m_mode_can_write, debug)


# Emit a tiny deterministic probe for the constant-only closure. / 为常量闭包输出微型确定性探针。
class CSRProbe(Elaboratable):
    """Expose a constant marker for Verilog contract checks. / 暴露用于 Verilog 契约检查的常量标记。"""

    # Declare the marker port. / 声明标记端口。
    def __init__(self) -> None:
        """Create the marker signal. / 创建标记信号。"""

        self.marker = Signal(name="marker")

    # Drive the marker in combinational logic. / 以组合逻辑驱动标记。
    def elaborate(self, platform: Any) -> Module:
        """Return the constant probe module. / 返回常量探针模块。"""

        del platform
        module = Module()
        module.d.comb += self.marker.eq(1)
        return module


# =============================================================================
# Public Adapter
# =============================================================================
# Build a deterministic constant-table probe. / 构建确定性的常量表探针。
def build_verilog(configuration: Any = None,
                  injected_dependencies: dict[str, Any] | None = None) -> str:
    """Emit a probe while keeping CSR values available in Python. / 输出探针并保留 Python CSR 值。"""

    del configuration, injected_dependencies
    from amaranth.back import verilog

    top = CSRProbe()
    return verilog.convert(top, name="CSRs", ports=[top.marker], emit_src=False)


# =============================================================================
# Direct Entry
# =============================================================================
# Print generated constant-table probe. / 打印生成的常量表探针。
def main() -> None:
    """Print deterministic Verilog output. / 打印确定性的 Verilog 输出。"""

    print(build_verilog(None, {}))


if __name__ == "__main__":
    main()
