"""Implement the V2 ROB, rename, and trace aggregate with exact ANSI ports.
以精确 ANSI 端口实现 V2 ROB、重命名与追踪聚合模块。
"""

from __future__ import annotations

from typing import Any

from amaranth import Array, ClockDomain, Const, Elaboratable, Mux, Module, Signal
from amaranth.back import verilog

__all__ = [
    'COVERED_MODULES',
    'PORT_SPECS',
    'RobRenameTraceFamily',
    'build_verilog',
    'main',
]

COVERED_MODULES = (
    "ExceptionGen",
    "DiffRatStateBuffer",
    "diff_rat_state_bank_320x776",
    "stateBankTags_320x3",
    "RenameBuffer",
    "SnapshotGenerator",
    "CompressUnit",
    "Trace",
    "TraceBuffer",
)
PortSpec = tuple[str, str, int]

PORT_SPECS: dict[str, tuple[PortSpec, ...]] = {
    'ExceptionGen': (
        ('clock', 'input', 1),
        ('reset', 'input', 1),
        ('io_redirect_valid', 'input', 1),
        ('io_redirect_bits_robIdx_flag', 'input', 1),
        ('io_redirect_bits_robIdx_value', 'input', 8),
        ('io_redirect_bits_level', 'input', 1),
        ('io_flush', 'input', 1),
        ('io_enq_0_valid', 'input', 1),
        ('io_enq_0_bits_robIdx_flag', 'input', 1),
        ('io_enq_0_bits_robIdx_value', 'input', 8),
        ('io_enq_0_bits_ftqPtr_value', 'input', 6),
        ('io_enq_0_bits_ftqOffset', 'input', 4),
        ('io_enq_0_bits_hasException', 'input', 1),
        ('io_enq_0_bits_exceptionVec_0', 'input', 1),
        ('io_enq_0_bits_exceptionVec_1', 'input', 1),
        ('io_enq_0_bits_exceptionVec_2', 'input', 1),
        ('io_enq_0_bits_exceptionVec_3', 'input', 1),
        ('io_enq_0_bits_exceptionVec_12', 'input', 1),
        ('io_enq_0_bits_exceptionVec_20', 'input', 1),
        ('io_enq_0_bits_exceptionVec_22', 'input', 1),
        ('io_enq_0_bits_isFetchMalAddr', 'input', 1),
        ('io_enq_0_bits_satpFlushFirstFetchFault', 'input', 1),
        ('io_enq_0_bits_flushPipe', 'input', 1),
        ('io_enq_0_bits_isVset', 'input', 1),
        ('io_enq_0_bits_singleStep', 'input', 1),
        ('io_enq_0_bits_crossPageIPFFix', 'input', 1),
        ('io_enq_0_bits_trigger', 'input', 4),
        ('io_enq_1_valid', 'input', 1),
        ('io_enq_1_bits_robIdx_flag', 'input', 1),
        ('io_enq_1_bits_robIdx_value', 'input', 8),
        ('io_enq_1_bits_ftqPtr_value', 'input', 6),
        ('io_enq_1_bits_ftqOffset', 'input', 4),
        ('io_enq_1_bits_hasException', 'input', 1),
        ('io_enq_1_bits_exceptionVec_0', 'input', 1),
        ('io_enq_1_bits_exceptionVec_1', 'input', 1),
        ('io_enq_1_bits_exceptionVec_2', 'input', 1),
        ('io_enq_1_bits_exceptionVec_3', 'input', 1),
        ('io_enq_1_bits_exceptionVec_12', 'input', 1),
        ('io_enq_1_bits_exceptionVec_20', 'input', 1),
        ('io_enq_1_bits_exceptionVec_22', 'input', 1),
        ('io_enq_1_bits_isFetchMalAddr', 'input', 1),
        ('io_enq_1_bits_satpFlushFirstFetchFault', 'input', 1),
        ('io_enq_1_bits_flushPipe', 'input', 1),
        ('io_enq_1_bits_isVset', 'input', 1),
        ('io_enq_1_bits_singleStep', 'input', 1),
        ('io_enq_1_bits_crossPageIPFFix', 'input', 1),
        ('io_enq_1_bits_trigger', 'input', 4),
        ('io_enq_2_valid', 'input', 1),
        ('io_enq_2_bits_robIdx_flag', 'input', 1),
        ('io_enq_2_bits_robIdx_value', 'input', 8),
        ('io_enq_2_bits_ftqPtr_value', 'input', 6),
        ('io_enq_2_bits_ftqOffset', 'input', 4),
        ('io_enq_2_bits_hasException', 'input', 1),
        ('io_enq_2_bits_exceptionVec_0', 'input', 1),
        ('io_enq_2_bits_exceptionVec_1', 'input', 1),
        ('io_enq_2_bits_exceptionVec_2', 'input', 1),
        ('io_enq_2_bits_exceptionVec_3', 'input', 1),
        ('io_enq_2_bits_exceptionVec_12', 'input', 1),
        ('io_enq_2_bits_exceptionVec_20', 'input', 1),
        ('io_enq_2_bits_exceptionVec_22', 'input', 1),
        ('io_enq_2_bits_isFetchMalAddr', 'input', 1),
        ('io_enq_2_bits_satpFlushFirstFetchFault', 'input', 1),
        ('io_enq_2_bits_flushPipe', 'input', 1),
        ('io_enq_2_bits_isVset', 'input', 1),
        ('io_enq_2_bits_singleStep', 'input', 1),
        ('io_enq_2_bits_crossPageIPFFix', 'input', 1),
        ('io_enq_2_bits_trigger', 'input', 4),
        ('io_enq_3_valid', 'input', 1),
        ('io_enq_3_bits_robIdx_flag', 'input', 1),
        ('io_enq_3_bits_robIdx_value', 'input', 8),
        ('io_enq_3_bits_ftqPtr_value', 'input', 6),
        ('io_enq_3_bits_ftqOffset', 'input', 4),
        ('io_enq_3_bits_hasException', 'input', 1),
        ('io_enq_3_bits_exceptionVec_0', 'input', 1),
        ('io_enq_3_bits_exceptionVec_1', 'input', 1),
        ('io_enq_3_bits_exceptionVec_2', 'input', 1),
        ('io_enq_3_bits_exceptionVec_3', 'input', 1),
        ('io_enq_3_bits_exceptionVec_12', 'input', 1),
        ('io_enq_3_bits_exceptionVec_20', 'input', 1),
        ('io_enq_3_bits_exceptionVec_22', 'input', 1),
        ('io_enq_3_bits_isFetchMalAddr', 'input', 1),
        ('io_enq_3_bits_satpFlushFirstFetchFault', 'input', 1),
        ('io_enq_3_bits_flushPipe', 'input', 1),
        ('io_enq_3_bits_isVset', 'input', 1),
        ('io_enq_3_bits_singleStep', 'input', 1),
        ('io_enq_3_bits_crossPageIPFFix', 'input', 1),
        ('io_enq_3_bits_trigger', 'input', 4),
        ('io_enq_4_valid', 'input', 1),
        ('io_enq_4_bits_robIdx_flag', 'input', 1),
        ('io_enq_4_bits_robIdx_value', 'input', 8),
        ('io_enq_4_bits_ftqPtr_value', 'input', 6),
        ('io_enq_4_bits_ftqOffset', 'input', 4),
        ('io_enq_4_bits_hasException', 'input', 1),
        ('io_enq_4_bits_exceptionVec_0', 'input', 1),
        ('io_enq_4_bits_exceptionVec_1', 'input', 1),
        ('io_enq_4_bits_exceptionVec_2', 'input', 1),
        ('io_enq_4_bits_exceptionVec_3', 'input', 1),
        ('io_enq_4_bits_exceptionVec_12', 'input', 1),
        ('io_enq_4_bits_exceptionVec_20', 'input', 1),
        ('io_enq_4_bits_exceptionVec_22', 'input', 1),
        ('io_enq_4_bits_isFetchMalAddr', 'input', 1),
        ('io_enq_4_bits_satpFlushFirstFetchFault', 'input', 1),
        ('io_enq_4_bits_flushPipe', 'input', 1),
        ('io_enq_4_bits_isVset', 'input', 1),
        ('io_enq_4_bits_singleStep', 'input', 1),
        ('io_enq_4_bits_crossPageIPFFix', 'input', 1),
        ('io_enq_4_bits_trigger', 'input', 4),
        ('io_enq_5_valid', 'input', 1),
        ('io_enq_5_bits_robIdx_flag', 'input', 1),
        ('io_enq_5_bits_robIdx_value', 'input', 8),
        ('io_enq_5_bits_ftqPtr_value', 'input', 6),
        ('io_enq_5_bits_ftqOffset', 'input', 4),
        ('io_enq_5_bits_hasException', 'input', 1),
        ('io_enq_5_bits_exceptionVec_0', 'input', 1),
        ('io_enq_5_bits_exceptionVec_1', 'input', 1),
        ('io_enq_5_bits_exceptionVec_2', 'input', 1),
        ('io_enq_5_bits_exceptionVec_3', 'input', 1),
        ('io_enq_5_bits_exceptionVec_12', 'input', 1),
        ('io_enq_5_bits_exceptionVec_20', 'input', 1),
        ('io_enq_5_bits_exceptionVec_22', 'input', 1),
        ('io_enq_5_bits_isFetchMalAddr', 'input', 1),
        ('io_enq_5_bits_satpFlushFirstFetchFault', 'input', 1),
        ('io_enq_5_bits_flushPipe', 'input', 1),
        ('io_enq_5_bits_isVset', 'input', 1),
        ('io_enq_5_bits_singleStep', 'input', 1),
        ('io_enq_5_bits_crossPageIPFFix', 'input', 1),
        ('io_enq_5_bits_trigger', 'input', 4),
        ('io_wb_0_valid', 'input', 1),
        ('io_wb_0_bits_robIdx_flag', 'input', 1),
        ('io_wb_0_bits_robIdx_value', 'input', 8),
        ('io_wb_0_bits_hasException', 'input', 1),
        ('io_wb_0_bits_exceptionVec_2', 'input', 1),
        ('io_wb_0_bits_exceptionVec_3', 'input', 1),
        ('io_wb_0_bits_exceptionVec_8', 'input', 1),
        ('io_wb_0_bits_exceptionVec_9', 'input', 1),
        ('io_wb_0_bits_exceptionVec_10', 'input', 1),
        ('io_wb_0_bits_exceptionVec_11', 'input', 1),
        ('io_wb_0_bits_exceptionVec_22', 'input', 1),
        ('io_wb_0_bits_flushPipe', 'input', 1),
        ('io_wb_0_bits_satpFlushPipe', 'input', 1),
        ('io_wb_1_valid', 'input', 1),
        ('io_wb_1_bits_robIdx_flag', 'input', 1),
        ('io_wb_1_bits_robIdx_value', 'input', 8),
        ('io_wb_1_bits_hasException', 'input', 1),
        ('io_wb_1_bits_exceptionVec_2', 'input', 1),
        ('io_wb_2_valid', 'input', 1),
        ('io_wb_2_bits_robIdx_flag', 'input', 1),
        ('io_wb_2_bits_robIdx_value', 'input', 8),
        ('io_wb_2_bits_hasException', 'input', 1),
        ('io_wb_2_bits_exceptionVec_2', 'input', 1),
        ('io_wb_3_bits_robIdx_flag', 'input', 1),
        ('io_wb_3_bits_robIdx_value', 'input', 8),
        ('io_wb_4_bits_robIdx_flag', 'input', 1),
        ('io_wb_4_bits_robIdx_value', 'input', 8),
        ('io_wb_5_bits_robIdx_flag', 'input', 1),
        ('io_wb_5_bits_robIdx_value', 'input', 8),
        ('io_wb_6_valid', 'input', 1),
        ('io_wb_6_bits_robIdx_flag', 'input', 1),
        ('io_wb_6_bits_robIdx_value', 'input', 8),
        ('io_wb_6_bits_hasException', 'input', 1),
        ('io_wb_6_bits_exceptionVec_0', 'input', 1),
        ('io_wb_6_bits_exceptionVec_1', 'input', 1),
        ('io_wb_6_bits_exceptionVec_2', 'input', 1),
        ('io_wb_6_bits_exceptionVec_3', 'input', 1),
        ('io_wb_6_bits_exceptionVec_4', 'input', 1),
        ('io_wb_6_bits_exceptionVec_5', 'input', 1),
        ('io_wb_6_bits_exceptionVec_6', 'input', 1),
        ('io_wb_6_bits_exceptionVec_7', 'input', 1),
        ('io_wb_6_bits_exceptionVec_8', 'input', 1),
        ('io_wb_6_bits_exceptionVec_9', 'input', 1),
        ('io_wb_6_bits_exceptionVec_10', 'input', 1),
        ('io_wb_6_bits_exceptionVec_11', 'input', 1),
        ('io_wb_6_bits_exceptionVec_12', 'input', 1),
        ('io_wb_6_bits_exceptionVec_13', 'input', 1),
        ('io_wb_6_bits_exceptionVec_14', 'input', 1),
        ('io_wb_6_bits_exceptionVec_15', 'input', 1),
        ('io_wb_6_bits_exceptionVec_16', 'input', 1),
        ('io_wb_6_bits_exceptionVec_17', 'input', 1),
        ('io_wb_6_bits_exceptionVec_18', 'input', 1),
        ('io_wb_6_bits_exceptionVec_19', 'input', 1),
        ('io_wb_6_bits_exceptionVec_20', 'input', 1),
        ('io_wb_6_bits_exceptionVec_21', 'input', 1),
        ('io_wb_6_bits_exceptionVec_22', 'input', 1),
        ('io_wb_6_bits_exceptionVec_23', 'input', 1),
        ('io_wb_6_bits_flushPipe', 'input', 1),
        ('io_wb_6_bits_trigger', 'input', 4),
        ('io_wb_7_valid', 'input', 1),
        ('io_wb_7_bits_robIdx_flag', 'input', 1),
        ('io_wb_7_bits_robIdx_value', 'input', 8),
        ('io_wb_7_bits_hasException', 'input', 1),
        ('io_wb_7_bits_exceptionVec_3', 'input', 1),
        ('io_wb_7_bits_exceptionVec_6', 'input', 1),
        ('io_wb_7_bits_exceptionVec_7', 'input', 1),
        ('io_wb_7_bits_exceptionVec_15', 'input', 1),
        ('io_wb_7_bits_exceptionVec_19', 'input', 1),
        ('io_wb_7_bits_exceptionVec_23', 'input', 1),
        ('io_wb_7_bits_trigger', 'input', 4),
        ('io_wb_8_valid', 'input', 1),
        ('io_wb_8_bits_robIdx_flag', 'input', 1),
        ('io_wb_8_bits_robIdx_value', 'input', 8),
        ('io_wb_8_bits_hasException', 'input', 1),
        ('io_wb_8_bits_exceptionVec_0', 'input', 1),
        ('io_wb_8_bits_exceptionVec_1', 'input', 1),
        ('io_wb_8_bits_exceptionVec_2', 'input', 1),
        ('io_wb_8_bits_exceptionVec_3', 'input', 1),
        ('io_wb_8_bits_exceptionVec_4', 'input', 1),
        ('io_wb_8_bits_exceptionVec_5', 'input', 1),
        ('io_wb_8_bits_exceptionVec_6', 'input', 1),
        ('io_wb_8_bits_exceptionVec_7', 'input', 1),
        ('io_wb_8_bits_exceptionVec_8', 'input', 1),
        ('io_wb_8_bits_exceptionVec_9', 'input', 1),
        ('io_wb_8_bits_exceptionVec_10', 'input', 1),
        ('io_wb_8_bits_exceptionVec_11', 'input', 1),
        ('io_wb_8_bits_exceptionVec_12', 'input', 1),
        ('io_wb_8_bits_exceptionVec_13', 'input', 1),
        ('io_wb_8_bits_exceptionVec_14', 'input', 1),
        ('io_wb_8_bits_exceptionVec_15', 'input', 1),
        ('io_wb_8_bits_exceptionVec_16', 'input', 1),
        ('io_wb_8_bits_exceptionVec_17', 'input', 1),
        ('io_wb_8_bits_exceptionVec_18', 'input', 1),
        ('io_wb_8_bits_exceptionVec_19', 'input', 1),
        ('io_wb_8_bits_exceptionVec_20', 'input', 1),
        ('io_wb_8_bits_exceptionVec_21', 'input', 1),
        ('io_wb_8_bits_exceptionVec_22', 'input', 1),
        ('io_wb_8_bits_exceptionVec_23', 'input', 1),
        ('io_wb_8_bits_flushPipe', 'input', 1),
        ('io_wb_8_bits_replayInst', 'input', 1),
        ('io_wb_8_bits_trigger', 'input', 4),
        ('io_wb_9_valid', 'input', 1),
        ('io_wb_9_bits_robIdx_flag', 'input', 1),
        ('io_wb_9_bits_robIdx_value', 'input', 8),
        ('io_wb_9_bits_hasException', 'input', 1),
        ('io_wb_9_bits_exceptionVec_3', 'input', 1),
        ('io_wb_9_bits_exceptionVec_4', 'input', 1),
        ('io_wb_9_bits_exceptionVec_5', 'input', 1),
        ('io_wb_9_bits_exceptionVec_13', 'input', 1),
        ('io_wb_9_bits_exceptionVec_19', 'input', 1),
        ('io_wb_9_bits_exceptionVec_21', 'input', 1),
        ('io_wb_9_bits_flushPipe', 'input', 1),
        ('io_wb_9_bits_replayInst', 'input', 1),
        ('io_wb_9_bits_trigger', 'input', 4),
        ('io_wb_10_valid', 'input', 1),
        ('io_wb_10_bits_robIdx_flag', 'input', 1),
        ('io_wb_10_bits_robIdx_value', 'input', 8),
        ('io_wb_10_bits_hasException', 'input', 1),
        ('io_wb_10_bits_exceptionVec_3', 'input', 1),
        ('io_wb_10_bits_exceptionVec_4', 'input', 1),
        ('io_wb_10_bits_exceptionVec_5', 'input', 1),
        ('io_wb_10_bits_exceptionVec_13', 'input', 1),
        ('io_wb_10_bits_exceptionVec_19', 'input', 1),
        ('io_wb_10_bits_exceptionVec_21', 'input', 1),
        ('io_wb_10_bits_flushPipe', 'input', 1),
        ('io_wb_10_bits_replayInst', 'input', 1),
        ('io_wb_10_bits_trigger', 'input', 4),
        ('io_wb_11_valid', 'input', 1),
        ('io_wb_11_bits_robIdx_flag', 'input', 1),
        ('io_wb_11_bits_robIdx_value', 'input', 8),
        ('io_wb_11_bits_hasException', 'input', 1),
        ('io_wb_11_bits_exceptionVec_0', 'input', 1),
        ('io_wb_11_bits_exceptionVec_1', 'input', 1),
        ('io_wb_11_bits_exceptionVec_2', 'input', 1),
        ('io_wb_11_bits_exceptionVec_3', 'input', 1),
        ('io_wb_11_bits_exceptionVec_4', 'input', 1),
        ('io_wb_11_bits_exceptionVec_5', 'input', 1),
        ('io_wb_11_bits_exceptionVec_6', 'input', 1),
        ('io_wb_11_bits_exceptionVec_7', 'input', 1),
        ('io_wb_11_bits_exceptionVec_8', 'input', 1),
        ('io_wb_11_bits_exceptionVec_9', 'input', 1),
        ('io_wb_11_bits_exceptionVec_10', 'input', 1),
        ('io_wb_11_bits_exceptionVec_11', 'input', 1),
        ('io_wb_11_bits_exceptionVec_12', 'input', 1),
        ('io_wb_11_bits_exceptionVec_13', 'input', 1),
        ('io_wb_11_bits_exceptionVec_14', 'input', 1),
        ('io_wb_11_bits_exceptionVec_15', 'input', 1),
        ('io_wb_11_bits_exceptionVec_16', 'input', 1),
        ('io_wb_11_bits_exceptionVec_17', 'input', 1),
        ('io_wb_11_bits_exceptionVec_18', 'input', 1),
        ('io_wb_11_bits_exceptionVec_19', 'input', 1),
        ('io_wb_11_bits_exceptionVec_20', 'input', 1),
        ('io_wb_11_bits_exceptionVec_21', 'input', 1),
        ('io_wb_11_bits_exceptionVec_22', 'input', 1),
        ('io_wb_11_bits_exceptionVec_23', 'input', 1),
        ('io_wb_11_bits_flushPipe', 'input', 1),
        ('io_wb_11_bits_replayInst', 'input', 1),
        ('io_wb_11_bits_trigger', 'input', 4),
        ('io_wb_11_bits_vstartEn', 'input', 1),
        ('io_wb_11_bits_vstart', 'input', 64),
        ('io_wb_11_bits_vuopIdx', 'input', 7),
        ('io_wb_11_bits_isVecLoad', 'input', 1),
        ('io_wb_11_bits_isVlm', 'input', 1),
        ('io_wb_11_bits_isStrided', 'input', 1),
        ('io_wb_11_bits_isIndexed', 'input', 1),
        ('io_wb_11_bits_isWhole', 'input', 1),
        ('io_wb_11_bits_nf', 'input', 3),
        ('io_wb_11_bits_vsew', 'input', 2),
        ('io_wb_11_bits_veew', 'input', 2),
        ('io_wb_11_bits_vlmul', 'input', 3),
        ('io_wb_12_valid', 'input', 1),
        ('io_wb_12_bits_robIdx_flag', 'input', 1),
        ('io_wb_12_bits_robIdx_value', 'input', 8),
        ('io_wb_12_bits_hasException', 'input', 1),
        ('io_wb_12_bits_exceptionVec_3', 'input', 1),
        ('io_wb_12_bits_exceptionVec_4', 'input', 1),
        ('io_wb_12_bits_exceptionVec_5', 'input', 1),
        ('io_wb_12_bits_exceptionVec_6', 'input', 1),
        ('io_wb_12_bits_exceptionVec_7', 'input', 1),
        ('io_wb_12_bits_exceptionVec_13', 'input', 1),
        ('io_wb_12_bits_exceptionVec_15', 'input', 1),
        ('io_wb_12_bits_exceptionVec_19', 'input', 1),
        ('io_wb_12_bits_exceptionVec_21', 'input', 1),
        ('io_wb_12_bits_exceptionVec_23', 'input', 1),
        ('io_wb_12_bits_flushPipe', 'input', 1),
        ('io_wb_12_bits_replayInst', 'input', 1),
        ('io_wb_12_bits_trigger', 'input', 4),
        ('io_wb_12_bits_vstartEn', 'input', 1),
        ('io_wb_12_bits_vstart', 'input', 64),
        ('io_wb_12_bits_vuopIdx', 'input', 7),
        ('io_wb_12_bits_isVecLoad', 'input', 1),
        ('io_wb_12_bits_isVlm', 'input', 1),
        ('io_wb_12_bits_isStrided', 'input', 1),
        ('io_wb_12_bits_isIndexed', 'input', 1),
        ('io_wb_12_bits_isWhole', 'input', 1),
        ('io_wb_12_bits_nf', 'input', 3),
        ('io_wb_12_bits_vsew', 'input', 2),
        ('io_wb_12_bits_veew', 'input', 2),
        ('io_wb_12_bits_vlmul', 'input', 3),
        ('io_state_valid', 'output', 1),
        ('io_state_bits_robIdx_flag', 'output', 1),
        ('io_state_bits_robIdx_value', 'output', 8),
        ('io_state_bits_ftqPtr_value', 'output', 6),
        ('io_state_bits_ftqOffset', 'output', 4),
        ('io_state_bits_hasException', 'output', 1),
        ('io_state_bits_isEnqExcp', 'output', 1),
        ('io_state_bits_exceptionVec_0', 'output', 1),
        ('io_state_bits_exceptionVec_1', 'output', 1),
        ('io_state_bits_exceptionVec_2', 'output', 1),
        ('io_state_bits_exceptionVec_3', 'output', 1),
        ('io_state_bits_exceptionVec_4', 'output', 1),
        ('io_state_bits_exceptionVec_5', 'output', 1),
        ('io_state_bits_exceptionVec_6', 'output', 1),
        ('io_state_bits_exceptionVec_7', 'output', 1),
        ('io_state_bits_exceptionVec_8', 'output', 1),
        ('io_state_bits_exceptionVec_9', 'output', 1),
        ('io_state_bits_exceptionVec_10', 'output', 1),
        ('io_state_bits_exceptionVec_11', 'output', 1),
        ('io_state_bits_exceptionVec_12', 'output', 1),
        ('io_state_bits_exceptionVec_13', 'output', 1),
        ('io_state_bits_exceptionVec_14', 'output', 1),
        ('io_state_bits_exceptionVec_15', 'output', 1),
        ('io_state_bits_exceptionVec_16', 'output', 1),
        ('io_state_bits_exceptionVec_17', 'output', 1),
        ('io_state_bits_exceptionVec_18', 'output', 1),
        ('io_state_bits_exceptionVec_19', 'output', 1),
        ('io_state_bits_exceptionVec_20', 'output', 1),
        ('io_state_bits_exceptionVec_21', 'output', 1),
        ('io_state_bits_exceptionVec_22', 'output', 1),
        ('io_state_bits_exceptionVec_23', 'output', 1),
        ('io_state_bits_isFetchMalAddr', 'output', 1),
        ('io_state_bits_satpFlushFirstFetchFault', 'output', 1),
        ('io_state_bits_flushPipe', 'output', 1),
        ('io_state_bits_satpFlushPipe', 'output', 1),
        ('io_state_bits_isVset', 'output', 1),
        ('io_state_bits_replayInst', 'output', 1),
        ('io_state_bits_singleStep', 'output', 1),
        ('io_state_bits_crossPageIPFFix', 'output', 1),
        ('io_state_bits_trigger', 'output', 4),
        ('io_state_bits_vstartEn', 'output', 1),
        ('io_state_bits_vstart', 'output', 64),
        ('io_state_bits_isVecLoad', 'output', 1),
        ('io_state_bits_isVlm', 'output', 1),
        ('io_state_bits_isStrided', 'output', 1),
        ('io_state_bits_isIndexed', 'output', 1),
        ('io_state_bits_isWhole', 'output', 1),
        ('io_state_bits_nf', 'output', 3),
        ('io_state_bits_vsew', 'output', 2),
        ('io_state_bits_veew', 'output', 2),
        ('io_state_bits_vlmul', 'output', 3),
    ),
    'DiffRatStateBuffer': (
        ('clock', 'input', 1),
        ('reset', 'input', 1),
        ('io_diffRatBase_intRat_0', 'input', 8),
        ('io_diffRatBase_intRat_1', 'input', 8),
        ('io_diffRatBase_intRat_2', 'input', 8),
        ('io_diffRatBase_intRat_3', 'input', 8),
        ('io_diffRatBase_intRat_4', 'input', 8),
        ('io_diffRatBase_intRat_5', 'input', 8),
        ('io_diffRatBase_intRat_6', 'input', 8),
        ('io_diffRatBase_intRat_7', 'input', 8),
        ('io_diffRatBase_intRat_8', 'input', 8),
        ('io_diffRatBase_intRat_9', 'input', 8),
        ('io_diffRatBase_intRat_10', 'input', 8),
        ('io_diffRatBase_intRat_11', 'input', 8),
        ('io_diffRatBase_intRat_12', 'input', 8),
        ('io_diffRatBase_intRat_13', 'input', 8),
        ('io_diffRatBase_intRat_14', 'input', 8),
        ('io_diffRatBase_intRat_15', 'input', 8),
        ('io_diffRatBase_intRat_16', 'input', 8),
        ('io_diffRatBase_intRat_17', 'input', 8),
        ('io_diffRatBase_intRat_18', 'input', 8),
        ('io_diffRatBase_intRat_19', 'input', 8),
        ('io_diffRatBase_intRat_20', 'input', 8),
        ('io_diffRatBase_intRat_21', 'input', 8),
        ('io_diffRatBase_intRat_22', 'input', 8),
        ('io_diffRatBase_intRat_23', 'input', 8),
        ('io_diffRatBase_intRat_24', 'input', 8),
        ('io_diffRatBase_intRat_25', 'input', 8),
        ('io_diffRatBase_intRat_26', 'input', 8),
        ('io_diffRatBase_intRat_27', 'input', 8),
        ('io_diffRatBase_intRat_28', 'input', 8),
        ('io_diffRatBase_intRat_29', 'input', 8),
        ('io_diffRatBase_intRat_30', 'input', 8),
        ('io_diffRatBase_intRat_31', 'input', 8),
        ('io_diffRatBase_fpRat_0', 'input', 8),
        ('io_diffRatBase_fpRat_1', 'input', 8),
        ('io_diffRatBase_fpRat_2', 'input', 8),
        ('io_diffRatBase_fpRat_3', 'input', 8),
        ('io_diffRatBase_fpRat_4', 'input', 8),
        ('io_diffRatBase_fpRat_5', 'input', 8),
        ('io_diffRatBase_fpRat_6', 'input', 8),
        ('io_diffRatBase_fpRat_7', 'input', 8),
        ('io_diffRatBase_fpRat_8', 'input', 8),
        ('io_diffRatBase_fpRat_9', 'input', 8),
        ('io_diffRatBase_fpRat_10', 'input', 8),
        ('io_diffRatBase_fpRat_11', 'input', 8),
        ('io_diffRatBase_fpRat_12', 'input', 8),
        ('io_diffRatBase_fpRat_13', 'input', 8),
        ('io_diffRatBase_fpRat_14', 'input', 8),
        ('io_diffRatBase_fpRat_15', 'input', 8),
        ('io_diffRatBase_fpRat_16', 'input', 8),
        ('io_diffRatBase_fpRat_17', 'input', 8),
        ('io_diffRatBase_fpRat_18', 'input', 8),
        ('io_diffRatBase_fpRat_19', 'input', 8),
        ('io_diffRatBase_fpRat_20', 'input', 8),
        ('io_diffRatBase_fpRat_21', 'input', 8),
        ('io_diffRatBase_fpRat_22', 'input', 8),
        ('io_diffRatBase_fpRat_23', 'input', 8),
        ('io_diffRatBase_fpRat_24', 'input', 8),
        ('io_diffRatBase_fpRat_25', 'input', 8),
        ('io_diffRatBase_fpRat_26', 'input', 8),
        ('io_diffRatBase_fpRat_27', 'input', 8),
        ('io_diffRatBase_fpRat_28', 'input', 8),
        ('io_diffRatBase_fpRat_29', 'input', 8),
        ('io_diffRatBase_fpRat_30', 'input', 8),
        ('io_diffRatBase_fpRat_31', 'input', 8),
        ('io_diffRatBase_vecRat_0', 'input', 8),
        ('io_diffRatBase_vecRat_1', 'input', 8),
        ('io_diffRatBase_vecRat_2', 'input', 8),
        ('io_diffRatBase_vecRat_3', 'input', 8),
        ('io_diffRatBase_vecRat_4', 'input', 8),
        ('io_diffRatBase_vecRat_5', 'input', 8),
        ('io_diffRatBase_vecRat_6', 'input', 8),
        ('io_diffRatBase_vecRat_7', 'input', 8),
        ('io_diffRatBase_vecRat_8', 'input', 8),
        ('io_diffRatBase_vecRat_9', 'input', 8),
        ('io_diffRatBase_vecRat_10', 'input', 8),
        ('io_diffRatBase_vecRat_11', 'input', 8),
        ('io_diffRatBase_vecRat_12', 'input', 8),
        ('io_diffRatBase_vecRat_13', 'input', 8),
        ('io_diffRatBase_vecRat_14', 'input', 8),
        ('io_diffRatBase_vecRat_15', 'input', 8),
        ('io_diffRatBase_vecRat_16', 'input', 8),
        ('io_diffRatBase_vecRat_17', 'input', 8),
        ('io_diffRatBase_vecRat_18', 'input', 8),
        ('io_diffRatBase_vecRat_19', 'input', 8),
        ('io_diffRatBase_vecRat_20', 'input', 8),
        ('io_diffRatBase_vecRat_21', 'input', 8),
        ('io_diffRatBase_vecRat_22', 'input', 8),
        ('io_diffRatBase_vecRat_23', 'input', 8),
        ('io_diffRatBase_vecRat_24', 'input', 8),
        ('io_diffRatBase_vecRat_25', 'input', 8),
        ('io_diffRatBase_vecRat_26', 'input', 8),
        ('io_diffRatBase_vecRat_27', 'input', 8),
        ('io_diffRatBase_vecRat_28', 'input', 8),
        ('io_diffRatBase_vecRat_29', 'input', 8),
        ('io_diffRatBase_vecRat_30', 'input', 8),
        ('io_diffRatBase_v0Rat_0', 'input', 8),
        ('io_diffRatBase_vlRat_0', 'input', 8),
        ('io_renameUpdates_0_valid', 'input', 1),
        ('io_renameUpdates_0_bits_robIdx_flag', 'input', 1),
        ('io_renameUpdates_0_bits_robIdx_value', 'input', 8),
        ('io_renameUpdates_0_bits_lastUop', 'input', 1),
        ('io_renameUpdates_0_bits_ldest', 'input', 6),
        ('io_renameUpdates_0_bits_pdest', 'input', 8),
        ('io_renameUpdates_0_bits_rfWen', 'input', 1),
        ('io_renameUpdates_0_bits_fpWen', 'input', 1),
        ('io_renameUpdates_0_bits_vecWen', 'input', 1),
        ('io_renameUpdates_0_bits_v0Wen', 'input', 1),
        ('io_renameUpdates_0_bits_vlWen', 'input', 1),
        ('io_renameUpdates_1_valid', 'input', 1),
        ('io_renameUpdates_1_bits_robIdx_flag', 'input', 1),
        ('io_renameUpdates_1_bits_robIdx_value', 'input', 8),
        ('io_renameUpdates_1_bits_lastUop', 'input', 1),
        ('io_renameUpdates_1_bits_ldest', 'input', 6),
        ('io_renameUpdates_1_bits_pdest', 'input', 8),
        ('io_renameUpdates_1_bits_rfWen', 'input', 1),
        ('io_renameUpdates_1_bits_fpWen', 'input', 1),
        ('io_renameUpdates_1_bits_vecWen', 'input', 1),
        ('io_renameUpdates_1_bits_v0Wen', 'input', 1),
        ('io_renameUpdates_1_bits_vlWen', 'input', 1),
        ('io_renameUpdates_2_valid', 'input', 1),
        ('io_renameUpdates_2_bits_robIdx_flag', 'input', 1),
        ('io_renameUpdates_2_bits_robIdx_value', 'input', 8),
        ('io_renameUpdates_2_bits_lastUop', 'input', 1),
        ('io_renameUpdates_2_bits_ldest', 'input', 6),
        ('io_renameUpdates_2_bits_pdest', 'input', 8),
        ('io_renameUpdates_2_bits_rfWen', 'input', 1),
        ('io_renameUpdates_2_bits_fpWen', 'input', 1),
        ('io_renameUpdates_2_bits_vecWen', 'input', 1),
        ('io_renameUpdates_2_bits_v0Wen', 'input', 1),
        ('io_renameUpdates_2_bits_vlWen', 'input', 1),
        ('io_renameUpdates_3_valid', 'input', 1),
        ('io_renameUpdates_3_bits_robIdx_flag', 'input', 1),
        ('io_renameUpdates_3_bits_robIdx_value', 'input', 8),
        ('io_renameUpdates_3_bits_lastUop', 'input', 1),
        ('io_renameUpdates_3_bits_ldest', 'input', 6),
        ('io_renameUpdates_3_bits_pdest', 'input', 8),
        ('io_renameUpdates_3_bits_rfWen', 'input', 1),
        ('io_renameUpdates_3_bits_fpWen', 'input', 1),
        ('io_renameUpdates_3_bits_vecWen', 'input', 1),
        ('io_renameUpdates_3_bits_v0Wen', 'input', 1),
        ('io_renameUpdates_3_bits_vlWen', 'input', 1),
        ('io_renameUpdates_4_valid', 'input', 1),
        ('io_renameUpdates_4_bits_robIdx_flag', 'input', 1),
        ('io_renameUpdates_4_bits_robIdx_value', 'input', 8),
        ('io_renameUpdates_4_bits_lastUop', 'input', 1),
        ('io_renameUpdates_4_bits_ldest', 'input', 6),
        ('io_renameUpdates_4_bits_pdest', 'input', 8),
        ('io_renameUpdates_4_bits_rfWen', 'input', 1),
        ('io_renameUpdates_4_bits_fpWen', 'input', 1),
        ('io_renameUpdates_4_bits_vecWen', 'input', 1),
        ('io_renameUpdates_4_bits_v0Wen', 'input', 1),
        ('io_renameUpdates_4_bits_vlWen', 'input', 1),
        ('io_renameUpdates_5_valid', 'input', 1),
        ('io_renameUpdates_5_bits_robIdx_flag', 'input', 1),
        ('io_renameUpdates_5_bits_robIdx_value', 'input', 8),
        ('io_renameUpdates_5_bits_lastUop', 'input', 1),
        ('io_renameUpdates_5_bits_ldest', 'input', 6),
        ('io_renameUpdates_5_bits_pdest', 'input', 8),
        ('io_renameUpdates_5_bits_rfWen', 'input', 1),
        ('io_renameUpdates_5_bits_fpWen', 'input', 1),
        ('io_renameUpdates_5_bits_vecWen', 'input', 1),
        ('io_renameUpdates_5_bits_v0Wen', 'input', 1),
        ('io_renameUpdates_5_bits_vlWen', 'input', 1),
        ('io_commitRobIdx_valid', 'input', 1),
        ('io_commitRobIdx_bits_flag', 'input', 1),
        ('io_commitRobIdx_bits_value', 'input', 8),
        ('io_diffRat_intRat_0', 'output', 8),
        ('io_diffRat_intRat_1', 'output', 8),
        ('io_diffRat_intRat_2', 'output', 8),
        ('io_diffRat_intRat_3', 'output', 8),
        ('io_diffRat_intRat_4', 'output', 8),
        ('io_diffRat_intRat_5', 'output', 8),
        ('io_diffRat_intRat_6', 'output', 8),
        ('io_diffRat_intRat_7', 'output', 8),
        ('io_diffRat_intRat_8', 'output', 8),
        ('io_diffRat_intRat_9', 'output', 8),
        ('io_diffRat_intRat_10', 'output', 8),
        ('io_diffRat_intRat_11', 'output', 8),
        ('io_diffRat_intRat_12', 'output', 8),
        ('io_diffRat_intRat_13', 'output', 8),
        ('io_diffRat_intRat_14', 'output', 8),
        ('io_diffRat_intRat_15', 'output', 8),
        ('io_diffRat_intRat_16', 'output', 8),
        ('io_diffRat_intRat_17', 'output', 8),
        ('io_diffRat_intRat_18', 'output', 8),
        ('io_diffRat_intRat_19', 'output', 8),
        ('io_diffRat_intRat_20', 'output', 8),
        ('io_diffRat_intRat_21', 'output', 8),
        ('io_diffRat_intRat_22', 'output', 8),
        ('io_diffRat_intRat_23', 'output', 8),
        ('io_diffRat_intRat_24', 'output', 8),
        ('io_diffRat_intRat_25', 'output', 8),
        ('io_diffRat_intRat_26', 'output', 8),
        ('io_diffRat_intRat_27', 'output', 8),
        ('io_diffRat_intRat_28', 'output', 8),
        ('io_diffRat_intRat_29', 'output', 8),
        ('io_diffRat_intRat_30', 'output', 8),
        ('io_diffRat_intRat_31', 'output', 8),
        ('io_diffRat_fpRat_0', 'output', 8),
        ('io_diffRat_fpRat_1', 'output', 8),
        ('io_diffRat_fpRat_2', 'output', 8),
        ('io_diffRat_fpRat_3', 'output', 8),
        ('io_diffRat_fpRat_4', 'output', 8),
        ('io_diffRat_fpRat_5', 'output', 8),
        ('io_diffRat_fpRat_6', 'output', 8),
        ('io_diffRat_fpRat_7', 'output', 8),
        ('io_diffRat_fpRat_8', 'output', 8),
        ('io_diffRat_fpRat_9', 'output', 8),
        ('io_diffRat_fpRat_10', 'output', 8),
        ('io_diffRat_fpRat_11', 'output', 8),
        ('io_diffRat_fpRat_12', 'output', 8),
        ('io_diffRat_fpRat_13', 'output', 8),
        ('io_diffRat_fpRat_14', 'output', 8),
        ('io_diffRat_fpRat_15', 'output', 8),
        ('io_diffRat_fpRat_16', 'output', 8),
        ('io_diffRat_fpRat_17', 'output', 8),
        ('io_diffRat_fpRat_18', 'output', 8),
        ('io_diffRat_fpRat_19', 'output', 8),
        ('io_diffRat_fpRat_20', 'output', 8),
        ('io_diffRat_fpRat_21', 'output', 8),
        ('io_diffRat_fpRat_22', 'output', 8),
        ('io_diffRat_fpRat_23', 'output', 8),
        ('io_diffRat_fpRat_24', 'output', 8),
        ('io_diffRat_fpRat_25', 'output', 8),
        ('io_diffRat_fpRat_26', 'output', 8),
        ('io_diffRat_fpRat_27', 'output', 8),
        ('io_diffRat_fpRat_28', 'output', 8),
        ('io_diffRat_fpRat_29', 'output', 8),
        ('io_diffRat_fpRat_30', 'output', 8),
        ('io_diffRat_fpRat_31', 'output', 8),
        ('io_diffRat_vecRat_0', 'output', 8),
        ('io_diffRat_vecRat_1', 'output', 8),
        ('io_diffRat_vecRat_2', 'output', 8),
        ('io_diffRat_vecRat_3', 'output', 8),
        ('io_diffRat_vecRat_4', 'output', 8),
        ('io_diffRat_vecRat_5', 'output', 8),
        ('io_diffRat_vecRat_6', 'output', 8),
        ('io_diffRat_vecRat_7', 'output', 8),
        ('io_diffRat_vecRat_8', 'output', 8),
        ('io_diffRat_vecRat_9', 'output', 8),
        ('io_diffRat_vecRat_10', 'output', 8),
        ('io_diffRat_vecRat_11', 'output', 8),
        ('io_diffRat_vecRat_12', 'output', 8),
        ('io_diffRat_vecRat_13', 'output', 8),
        ('io_diffRat_vecRat_14', 'output', 8),
        ('io_diffRat_vecRat_15', 'output', 8),
        ('io_diffRat_vecRat_16', 'output', 8),
        ('io_diffRat_vecRat_17', 'output', 8),
        ('io_diffRat_vecRat_18', 'output', 8),
        ('io_diffRat_vecRat_19', 'output', 8),
        ('io_diffRat_vecRat_20', 'output', 8),
        ('io_diffRat_vecRat_21', 'output', 8),
        ('io_diffRat_vecRat_22', 'output', 8),
        ('io_diffRat_vecRat_23', 'output', 8),
        ('io_diffRat_vecRat_24', 'output', 8),
        ('io_diffRat_vecRat_25', 'output', 8),
        ('io_diffRat_vecRat_26', 'output', 8),
        ('io_diffRat_vecRat_27', 'output', 8),
        ('io_diffRat_vecRat_28', 'output', 8),
        ('io_diffRat_vecRat_29', 'output', 8),
        ('io_diffRat_vecRat_30', 'output', 8),
        ('io_diffRat_v0Rat_0', 'output', 8),
        ('io_diffRat_vlRat_0', 'output', 8),
    ),
    'diff_rat_state_bank_320x776': (
        ('R0_addr', 'input', 9),
        ('R0_en', 'input', 1),
        ('R0_clk', 'input', 1),
        ('R0_data', 'output', 776),
        ('W0_addr', 'input', 9),
        ('W0_en', 'input', 1),
        ('W0_clk', 'input', 1),
        ('W0_data', 'input', 776),
    ),
    'stateBankTags_320x3': (
        ('R0_addr', 'input', 9),
        ('R0_en', 'input', 1),
        ('R0_clk', 'input', 1),
        ('R0_data', 'output', 3),
        ('W0_addr', 'input', 9),
        ('W0_en', 'input', 1),
        ('W0_clk', 'input', 1),
        ('W0_data', 'input', 3),
        ('W1_addr', 'input', 9),
        ('W1_en', 'input', 1),
        ('W1_clk', 'input', 1),
        ('W1_data', 'input', 3),
        ('W2_addr', 'input', 9),
        ('W2_en', 'input', 1),
        ('W2_clk', 'input', 1),
        ('W2_data', 'input', 3),
        ('W3_addr', 'input', 9),
        ('W3_en', 'input', 1),
        ('W3_clk', 'input', 1),
        ('W3_data', 'input', 3),
        ('W4_addr', 'input', 9),
        ('W4_en', 'input', 1),
        ('W4_clk', 'input', 1),
        ('W4_data', 'input', 3),
        ('W5_addr', 'input', 9),
        ('W5_en', 'input', 1),
        ('W5_clk', 'input', 1),
        ('W5_data', 'input', 3),
    ),
    'RenameBuffer': (
        ('clock', 'input', 1),
        ('reset', 'input', 1),
        ('io_redirect_valid', 'input', 1),
        ('io_req_0_valid', 'input', 1),
        ('io_req_0_bits_ldest', 'input', 6),
        ('io_req_0_bits_rfWen', 'input', 1),
        ('io_req_0_bits_fpWen', 'input', 1),
        ('io_req_0_bits_vecWen', 'input', 1),
        ('io_req_0_bits_v0Wen', 'input', 1),
        ('io_req_0_bits_vlWen', 'input', 1),
        ('io_req_0_bits_isMove', 'input', 1),
        ('io_req_0_bits_pdest', 'input', 8),
        ('io_req_1_valid', 'input', 1),
        ('io_req_1_bits_ldest', 'input', 6),
        ('io_req_1_bits_rfWen', 'input', 1),
        ('io_req_1_bits_fpWen', 'input', 1),
        ('io_req_1_bits_vecWen', 'input', 1),
        ('io_req_1_bits_v0Wen', 'input', 1),
        ('io_req_1_bits_vlWen', 'input', 1),
        ('io_req_1_bits_isMove', 'input', 1),
        ('io_req_1_bits_pdest', 'input', 8),
        ('io_req_2_valid', 'input', 1),
        ('io_req_2_bits_ldest', 'input', 6),
        ('io_req_2_bits_rfWen', 'input', 1),
        ('io_req_2_bits_fpWen', 'input', 1),
        ('io_req_2_bits_vecWen', 'input', 1),
        ('io_req_2_bits_v0Wen', 'input', 1),
        ('io_req_2_bits_vlWen', 'input', 1),
        ('io_req_2_bits_isMove', 'input', 1),
        ('io_req_2_bits_pdest', 'input', 8),
        ('io_req_3_valid', 'input', 1),
        ('io_req_3_bits_ldest', 'input', 6),
        ('io_req_3_bits_rfWen', 'input', 1),
        ('io_req_3_bits_fpWen', 'input', 1),
        ('io_req_3_bits_vecWen', 'input', 1),
        ('io_req_3_bits_v0Wen', 'input', 1),
        ('io_req_3_bits_vlWen', 'input', 1),
        ('io_req_3_bits_isMove', 'input', 1),
        ('io_req_3_bits_pdest', 'input', 8),
        ('io_req_4_valid', 'input', 1),
        ('io_req_4_bits_ldest', 'input', 6),
        ('io_req_4_bits_rfWen', 'input', 1),
        ('io_req_4_bits_fpWen', 'input', 1),
        ('io_req_4_bits_vecWen', 'input', 1),
        ('io_req_4_bits_v0Wen', 'input', 1),
        ('io_req_4_bits_vlWen', 'input', 1),
        ('io_req_4_bits_isMove', 'input', 1),
        ('io_req_4_bits_pdest', 'input', 8),
        ('io_req_5_valid', 'input', 1),
        ('io_req_5_bits_ldest', 'input', 6),
        ('io_req_5_bits_rfWen', 'input', 1),
        ('io_req_5_bits_fpWen', 'input', 1),
        ('io_req_5_bits_vecWen', 'input', 1),
        ('io_req_5_bits_v0Wen', 'input', 1),
        ('io_req_5_bits_vlWen', 'input', 1),
        ('io_req_5_bits_isMove', 'input', 1),
        ('io_req_5_bits_pdest', 'input', 8),
        ('io_fromRob_walkSize', 'input', 8),
        ('io_fromRob_walkEnd', 'input', 1),
        ('io_fromRob_commitSize', 'input', 8),
        ('io_fromRob_vecLoadExcp_valid', 'input', 1),
        ('io_snpt_snptEnq', 'input', 1),
        ('io_snpt_snptDeq', 'input', 1),
        ('io_snpt_useSnpt', 'input', 1),
        ('io_snpt_snptSelect', 'input', 2),
        ('io_snpt_flushVec_0', 'input', 1),
        ('io_snpt_flushVec_1', 'input', 1),
        ('io_snpt_flushVec_2', 'input', 1),
        ('io_snpt_flushVec_3', 'input', 1),
        ('io_canEnq', 'output', 1),
        ('io_canEnqForDispatch', 'output', 1),
        ('io_commits_isCommit', 'output', 1),
        ('io_commits_commitValid_0', 'output', 1),
        ('io_commits_commitValid_1', 'output', 1),
        ('io_commits_commitValid_2', 'output', 1),
        ('io_commits_commitValid_3', 'output', 1),
        ('io_commits_commitValid_4', 'output', 1),
        ('io_commits_commitValid_5', 'output', 1),
        ('io_commits_isWalk', 'output', 1),
        ('io_commits_walkValid_0', 'output', 1),
        ('io_commits_walkValid_1', 'output', 1),
        ('io_commits_walkValid_2', 'output', 1),
        ('io_commits_walkValid_3', 'output', 1),
        ('io_commits_walkValid_4', 'output', 1),
        ('io_commits_walkValid_5', 'output', 1),
        ('io_commits_info_0_ldest', 'output', 6),
        ('io_commits_info_0_pdest', 'output', 8),
        ('io_commits_info_0_rfWen', 'output', 1),
        ('io_commits_info_0_fpWen', 'output', 1),
        ('io_commits_info_0_vecWen', 'output', 1),
        ('io_commits_info_0_v0Wen', 'output', 1),
        ('io_commits_info_0_vlWen', 'output', 1),
        ('io_commits_info_0_isMove', 'output', 1),
        ('io_commits_info_1_ldest', 'output', 6),
        ('io_commits_info_1_pdest', 'output', 8),
        ('io_commits_info_1_rfWen', 'output', 1),
        ('io_commits_info_1_fpWen', 'output', 1),
        ('io_commits_info_1_vecWen', 'output', 1),
        ('io_commits_info_1_v0Wen', 'output', 1),
        ('io_commits_info_1_vlWen', 'output', 1),
        ('io_commits_info_1_isMove', 'output', 1),
        ('io_commits_info_2_ldest', 'output', 6),
        ('io_commits_info_2_pdest', 'output', 8),
        ('io_commits_info_2_rfWen', 'output', 1),
        ('io_commits_info_2_fpWen', 'output', 1),
        ('io_commits_info_2_vecWen', 'output', 1),
        ('io_commits_info_2_v0Wen', 'output', 1),
        ('io_commits_info_2_vlWen', 'output', 1),
        ('io_commits_info_2_isMove', 'output', 1),
        ('io_commits_info_3_ldest', 'output', 6),
        ('io_commits_info_3_pdest', 'output', 8),
        ('io_commits_info_3_rfWen', 'output', 1),
        ('io_commits_info_3_fpWen', 'output', 1),
        ('io_commits_info_3_vecWen', 'output', 1),
        ('io_commits_info_3_v0Wen', 'output', 1),
        ('io_commits_info_3_vlWen', 'output', 1),
        ('io_commits_info_3_isMove', 'output', 1),
        ('io_commits_info_4_ldest', 'output', 6),
        ('io_commits_info_4_pdest', 'output', 8),
        ('io_commits_info_4_rfWen', 'output', 1),
        ('io_commits_info_4_fpWen', 'output', 1),
        ('io_commits_info_4_vecWen', 'output', 1),
        ('io_commits_info_4_v0Wen', 'output', 1),
        ('io_commits_info_4_vlWen', 'output', 1),
        ('io_commits_info_4_isMove', 'output', 1),
        ('io_commits_info_5_ldest', 'output', 6),
        ('io_commits_info_5_pdest', 'output', 8),
        ('io_commits_info_5_rfWen', 'output', 1),
        ('io_commits_info_5_fpWen', 'output', 1),
        ('io_commits_info_5_vecWen', 'output', 1),
        ('io_commits_info_5_v0Wen', 'output', 1),
        ('io_commits_info_5_vlWen', 'output', 1),
        ('io_commits_info_5_isMove', 'output', 1),
        ('io_status_walkEnd', 'output', 1),
        ('io_status_commitEnd', 'output', 1),
        ('io_toVecExcpMod_logicPhyRegMap_0_valid', 'output', 1),
        ('io_toVecExcpMod_logicPhyRegMap_0_bits_lreg', 'output', 6),
        ('io_toVecExcpMod_logicPhyRegMap_0_bits_preg', 'output', 7),
        ('io_toVecExcpMod_logicPhyRegMap_1_valid', 'output', 1),
        ('io_toVecExcpMod_logicPhyRegMap_1_bits_lreg', 'output', 6),
        ('io_toVecExcpMod_logicPhyRegMap_1_bits_preg', 'output', 7),
        ('io_toVecExcpMod_logicPhyRegMap_2_valid', 'output', 1),
        ('io_toVecExcpMod_logicPhyRegMap_2_bits_lreg', 'output', 6),
        ('io_toVecExcpMod_logicPhyRegMap_2_bits_preg', 'output', 7),
        ('io_toVecExcpMod_logicPhyRegMap_3_valid', 'output', 1),
        ('io_toVecExcpMod_logicPhyRegMap_3_bits_lreg', 'output', 6),
        ('io_toVecExcpMod_logicPhyRegMap_3_bits_preg', 'output', 7),
        ('io_toVecExcpMod_logicPhyRegMap_4_valid', 'output', 1),
        ('io_toVecExcpMod_logicPhyRegMap_4_bits_lreg', 'output', 6),
        ('io_toVecExcpMod_logicPhyRegMap_4_bits_preg', 'output', 7),
        ('io_toVecExcpMod_logicPhyRegMap_5_valid', 'output', 1),
        ('io_toVecExcpMod_logicPhyRegMap_5_bits_lreg', 'output', 6),
        ('io_toVecExcpMod_logicPhyRegMap_5_bits_preg', 'output', 7),
    ),
    'SnapshotGenerator': (
        ('clock', 'input', 1),
        ('reset', 'input', 1),
        ('io_enq', 'input', 1),
        ('io_enqData_flag', 'input', 1),
        ('io_enqData_value', 'input', 8),
        ('io_deq', 'input', 1),
        ('io_redirect', 'input', 1),
        ('io_flushVec_0', 'input', 1),
        ('io_flushVec_1', 'input', 1),
        ('io_flushVec_2', 'input', 1),
        ('io_flushVec_3', 'input', 1),
        ('io_snapshots_0_flag', 'output', 1),
        ('io_snapshots_0_value', 'output', 8),
        ('io_snapshots_1_flag', 'output', 1),
        ('io_snapshots_1_value', 'output', 8),
        ('io_snapshots_2_flag', 'output', 1),
        ('io_snapshots_2_value', 'output', 8),
        ('io_snapshots_3_flag', 'output', 1),
        ('io_snapshots_3_value', 'output', 8),
    ),
    'CompressUnit': (
        ('io_in_0_valid', 'input', 1),
        ('io_in_0_bits_exceptionVec_0', 'input', 1),
        ('io_in_0_bits_exceptionVec_1', 'input', 1),
        ('io_in_0_bits_exceptionVec_2', 'input', 1),
        ('io_in_0_bits_exceptionVec_3', 'input', 1),
        ('io_in_0_bits_exceptionVec_4', 'input', 1),
        ('io_in_0_bits_exceptionVec_5', 'input', 1),
        ('io_in_0_bits_exceptionVec_6', 'input', 1),
        ('io_in_0_bits_exceptionVec_7', 'input', 1),
        ('io_in_0_bits_exceptionVec_8', 'input', 1),
        ('io_in_0_bits_exceptionVec_9', 'input', 1),
        ('io_in_0_bits_exceptionVec_10', 'input', 1),
        ('io_in_0_bits_exceptionVec_11', 'input', 1),
        ('io_in_0_bits_exceptionVec_12', 'input', 1),
        ('io_in_0_bits_exceptionVec_13', 'input', 1),
        ('io_in_0_bits_exceptionVec_14', 'input', 1),
        ('io_in_0_bits_exceptionVec_15', 'input', 1),
        ('io_in_0_bits_exceptionVec_16', 'input', 1),
        ('io_in_0_bits_exceptionVec_17', 'input', 1),
        ('io_in_0_bits_exceptionVec_18', 'input', 1),
        ('io_in_0_bits_exceptionVec_19', 'input', 1),
        ('io_in_0_bits_exceptionVec_20', 'input', 1),
        ('io_in_0_bits_exceptionVec_21', 'input', 1),
        ('io_in_0_bits_exceptionVec_22', 'input', 1),
        ('io_in_0_bits_exceptionVec_23', 'input', 1),
        ('io_in_0_bits_trigger', 'input', 4),
        ('io_in_0_bits_canRobCompress', 'input', 1),
        ('io_in_0_bits_lastUop', 'input', 1),
        ('io_in_0_bits_commitType', 'input', 3),
        ('io_in_1_valid', 'input', 1),
        ('io_in_1_bits_exceptionVec_0', 'input', 1),
        ('io_in_1_bits_exceptionVec_1', 'input', 1),
        ('io_in_1_bits_exceptionVec_2', 'input', 1),
        ('io_in_1_bits_exceptionVec_3', 'input', 1),
        ('io_in_1_bits_exceptionVec_4', 'input', 1),
        ('io_in_1_bits_exceptionVec_5', 'input', 1),
        ('io_in_1_bits_exceptionVec_6', 'input', 1),
        ('io_in_1_bits_exceptionVec_7', 'input', 1),
        ('io_in_1_bits_exceptionVec_8', 'input', 1),
        ('io_in_1_bits_exceptionVec_9', 'input', 1),
        ('io_in_1_bits_exceptionVec_10', 'input', 1),
        ('io_in_1_bits_exceptionVec_11', 'input', 1),
        ('io_in_1_bits_exceptionVec_12', 'input', 1),
        ('io_in_1_bits_exceptionVec_13', 'input', 1),
        ('io_in_1_bits_exceptionVec_14', 'input', 1),
        ('io_in_1_bits_exceptionVec_15', 'input', 1),
        ('io_in_1_bits_exceptionVec_16', 'input', 1),
        ('io_in_1_bits_exceptionVec_17', 'input', 1),
        ('io_in_1_bits_exceptionVec_18', 'input', 1),
        ('io_in_1_bits_exceptionVec_19', 'input', 1),
        ('io_in_1_bits_exceptionVec_20', 'input', 1),
        ('io_in_1_bits_exceptionVec_21', 'input', 1),
        ('io_in_1_bits_exceptionVec_22', 'input', 1),
        ('io_in_1_bits_exceptionVec_23', 'input', 1),
        ('io_in_1_bits_trigger', 'input', 4),
        ('io_in_1_bits_canRobCompress', 'input', 1),
        ('io_in_1_bits_lastUop', 'input', 1),
        ('io_in_1_bits_commitType', 'input', 3),
        ('io_in_2_valid', 'input', 1),
        ('io_in_2_bits_exceptionVec_0', 'input', 1),
        ('io_in_2_bits_exceptionVec_1', 'input', 1),
        ('io_in_2_bits_exceptionVec_2', 'input', 1),
        ('io_in_2_bits_exceptionVec_3', 'input', 1),
        ('io_in_2_bits_exceptionVec_4', 'input', 1),
        ('io_in_2_bits_exceptionVec_5', 'input', 1),
        ('io_in_2_bits_exceptionVec_6', 'input', 1),
        ('io_in_2_bits_exceptionVec_7', 'input', 1),
        ('io_in_2_bits_exceptionVec_8', 'input', 1),
        ('io_in_2_bits_exceptionVec_9', 'input', 1),
        ('io_in_2_bits_exceptionVec_10', 'input', 1),
        ('io_in_2_bits_exceptionVec_11', 'input', 1),
        ('io_in_2_bits_exceptionVec_12', 'input', 1),
        ('io_in_2_bits_exceptionVec_13', 'input', 1),
        ('io_in_2_bits_exceptionVec_14', 'input', 1),
        ('io_in_2_bits_exceptionVec_15', 'input', 1),
        ('io_in_2_bits_exceptionVec_16', 'input', 1),
        ('io_in_2_bits_exceptionVec_17', 'input', 1),
        ('io_in_2_bits_exceptionVec_18', 'input', 1),
        ('io_in_2_bits_exceptionVec_19', 'input', 1),
        ('io_in_2_bits_exceptionVec_20', 'input', 1),
        ('io_in_2_bits_exceptionVec_21', 'input', 1),
        ('io_in_2_bits_exceptionVec_22', 'input', 1),
        ('io_in_2_bits_exceptionVec_23', 'input', 1),
        ('io_in_2_bits_trigger', 'input', 4),
        ('io_in_2_bits_canRobCompress', 'input', 1),
        ('io_in_2_bits_lastUop', 'input', 1),
        ('io_in_2_bits_commitType', 'input', 3),
        ('io_in_3_valid', 'input', 1),
        ('io_in_3_bits_exceptionVec_0', 'input', 1),
        ('io_in_3_bits_exceptionVec_1', 'input', 1),
        ('io_in_3_bits_exceptionVec_2', 'input', 1),
        ('io_in_3_bits_exceptionVec_3', 'input', 1),
        ('io_in_3_bits_exceptionVec_4', 'input', 1),
        ('io_in_3_bits_exceptionVec_5', 'input', 1),
        ('io_in_3_bits_exceptionVec_6', 'input', 1),
        ('io_in_3_bits_exceptionVec_7', 'input', 1),
        ('io_in_3_bits_exceptionVec_8', 'input', 1),
        ('io_in_3_bits_exceptionVec_9', 'input', 1),
        ('io_in_3_bits_exceptionVec_10', 'input', 1),
        ('io_in_3_bits_exceptionVec_11', 'input', 1),
        ('io_in_3_bits_exceptionVec_12', 'input', 1),
        ('io_in_3_bits_exceptionVec_13', 'input', 1),
        ('io_in_3_bits_exceptionVec_14', 'input', 1),
        ('io_in_3_bits_exceptionVec_15', 'input', 1),
        ('io_in_3_bits_exceptionVec_16', 'input', 1),
        ('io_in_3_bits_exceptionVec_17', 'input', 1),
        ('io_in_3_bits_exceptionVec_18', 'input', 1),
        ('io_in_3_bits_exceptionVec_19', 'input', 1),
        ('io_in_3_bits_exceptionVec_20', 'input', 1),
        ('io_in_3_bits_exceptionVec_21', 'input', 1),
        ('io_in_3_bits_exceptionVec_22', 'input', 1),
        ('io_in_3_bits_exceptionVec_23', 'input', 1),
        ('io_in_3_bits_trigger', 'input', 4),
        ('io_in_3_bits_canRobCompress', 'input', 1),
        ('io_in_3_bits_lastUop', 'input', 1),
        ('io_in_3_bits_commitType', 'input', 3),
        ('io_in_4_valid', 'input', 1),
        ('io_in_4_bits_exceptionVec_0', 'input', 1),
        ('io_in_4_bits_exceptionVec_1', 'input', 1),
        ('io_in_4_bits_exceptionVec_2', 'input', 1),
        ('io_in_4_bits_exceptionVec_3', 'input', 1),
        ('io_in_4_bits_exceptionVec_4', 'input', 1),
        ('io_in_4_bits_exceptionVec_5', 'input', 1),
        ('io_in_4_bits_exceptionVec_6', 'input', 1),
        ('io_in_4_bits_exceptionVec_7', 'input', 1),
        ('io_in_4_bits_exceptionVec_8', 'input', 1),
        ('io_in_4_bits_exceptionVec_9', 'input', 1),
        ('io_in_4_bits_exceptionVec_10', 'input', 1),
        ('io_in_4_bits_exceptionVec_11', 'input', 1),
        ('io_in_4_bits_exceptionVec_12', 'input', 1),
        ('io_in_4_bits_exceptionVec_13', 'input', 1),
        ('io_in_4_bits_exceptionVec_14', 'input', 1),
        ('io_in_4_bits_exceptionVec_15', 'input', 1),
        ('io_in_4_bits_exceptionVec_16', 'input', 1),
        ('io_in_4_bits_exceptionVec_17', 'input', 1),
        ('io_in_4_bits_exceptionVec_18', 'input', 1),
        ('io_in_4_bits_exceptionVec_19', 'input', 1),
        ('io_in_4_bits_exceptionVec_20', 'input', 1),
        ('io_in_4_bits_exceptionVec_21', 'input', 1),
        ('io_in_4_bits_exceptionVec_22', 'input', 1),
        ('io_in_4_bits_exceptionVec_23', 'input', 1),
        ('io_in_4_bits_trigger', 'input', 4),
        ('io_in_4_bits_canRobCompress', 'input', 1),
        ('io_in_4_bits_lastUop', 'input', 1),
        ('io_in_4_bits_commitType', 'input', 3),
        ('io_in_5_valid', 'input', 1),
        ('io_in_5_bits_exceptionVec_0', 'input', 1),
        ('io_in_5_bits_exceptionVec_1', 'input', 1),
        ('io_in_5_bits_exceptionVec_2', 'input', 1),
        ('io_in_5_bits_exceptionVec_3', 'input', 1),
        ('io_in_5_bits_exceptionVec_4', 'input', 1),
        ('io_in_5_bits_exceptionVec_5', 'input', 1),
        ('io_in_5_bits_exceptionVec_6', 'input', 1),
        ('io_in_5_bits_exceptionVec_7', 'input', 1),
        ('io_in_5_bits_exceptionVec_8', 'input', 1),
        ('io_in_5_bits_exceptionVec_9', 'input', 1),
        ('io_in_5_bits_exceptionVec_10', 'input', 1),
        ('io_in_5_bits_exceptionVec_11', 'input', 1),
        ('io_in_5_bits_exceptionVec_12', 'input', 1),
        ('io_in_5_bits_exceptionVec_13', 'input', 1),
        ('io_in_5_bits_exceptionVec_14', 'input', 1),
        ('io_in_5_bits_exceptionVec_15', 'input', 1),
        ('io_in_5_bits_exceptionVec_16', 'input', 1),
        ('io_in_5_bits_exceptionVec_17', 'input', 1),
        ('io_in_5_bits_exceptionVec_18', 'input', 1),
        ('io_in_5_bits_exceptionVec_19', 'input', 1),
        ('io_in_5_bits_exceptionVec_20', 'input', 1),
        ('io_in_5_bits_exceptionVec_21', 'input', 1),
        ('io_in_5_bits_exceptionVec_22', 'input', 1),
        ('io_in_5_bits_exceptionVec_23', 'input', 1),
        ('io_in_5_bits_trigger', 'input', 4),
        ('io_in_5_bits_canRobCompress', 'input', 1),
        ('io_in_5_bits_lastUop', 'input', 1),
        ('io_in_5_bits_commitType', 'input', 3),
        ('io_out_needRobFlags_0', 'output', 1),
        ('io_out_needRobFlags_1', 'output', 1),
        ('io_out_needRobFlags_2', 'output', 1),
        ('io_out_needRobFlags_3', 'output', 1),
        ('io_out_needRobFlags_4', 'output', 1),
        ('io_out_needRobFlags_5', 'output', 1),
        ('io_out_instrSizes_0', 'output', 3),
        ('io_out_instrSizes_1', 'output', 3),
        ('io_out_instrSizes_2', 'output', 3),
        ('io_out_instrSizes_3', 'output', 3),
        ('io_out_instrSizes_4', 'output', 3),
        ('io_out_instrSizes_5', 'output', 3),
        ('io_out_masks_0', 'output', 6),
        ('io_out_masks_1', 'output', 6),
        ('io_out_masks_2', 'output', 6),
        ('io_out_masks_3', 'output', 6),
        ('io_out_masks_4', 'output', 6),
        ('io_out_masks_5', 'output', 6),
        ('io_out_canCompressVec_0', 'output', 1),
        ('io_out_canCompressVec_1', 'output', 1),
        ('io_out_canCompressVec_2', 'output', 1),
        ('io_out_canCompressVec_3', 'output', 1),
        ('io_out_canCompressVec_4', 'output', 1),
        ('io_out_canCompressVec_5', 'output', 1),
    ),
    'Trace': (
        ('clock', 'input', 1),
        ('reset', 'input', 1),
        ('io_in_fromEncoder_enable', 'input', 1),
        ('io_in_fromEncoder_stall', 'input', 1),
        ('io_in_fromRob_blocks_0_valid', 'input', 1),
        ('io_in_fromRob_blocks_0_bits_ftqIdx_value', 'input', 6),
        ('io_in_fromRob_blocks_0_bits_ftqOffset', 'input', 4),
        ('io_in_fromRob_blocks_0_bits_tracePipe_itype', 'input', 4),
        ('io_in_fromRob_blocks_0_bits_tracePipe_iretire', 'input', 4),
        ('io_in_fromRob_blocks_0_bits_tracePipe_ilastsize', 'input', 1),
        ('io_in_fromRob_blocks_1_valid', 'input', 1),
        ('io_in_fromRob_blocks_1_bits_ftqIdx_value', 'input', 6),
        ('io_in_fromRob_blocks_1_bits_ftqOffset', 'input', 4),
        ('io_in_fromRob_blocks_1_bits_tracePipe_itype', 'input', 4),
        ('io_in_fromRob_blocks_1_bits_tracePipe_iretire', 'input', 4),
        ('io_in_fromRob_blocks_1_bits_tracePipe_ilastsize', 'input', 1),
        ('io_in_fromRob_blocks_2_valid', 'input', 1),
        ('io_in_fromRob_blocks_2_bits_ftqIdx_value', 'input', 6),
        ('io_in_fromRob_blocks_2_bits_ftqOffset', 'input', 4),
        ('io_in_fromRob_blocks_2_bits_tracePipe_itype', 'input', 4),
        ('io_in_fromRob_blocks_2_bits_tracePipe_iretire', 'input', 4),
        ('io_in_fromRob_blocks_2_bits_tracePipe_ilastsize', 'input', 1),
        ('io_in_fromRob_blocks_3_valid', 'input', 1),
        ('io_in_fromRob_blocks_3_bits_ftqIdx_value', 'input', 6),
        ('io_in_fromRob_blocks_3_bits_ftqOffset', 'input', 4),
        ('io_in_fromRob_blocks_3_bits_tracePipe_itype', 'input', 4),
        ('io_in_fromRob_blocks_3_bits_tracePipe_iretire', 'input', 4),
        ('io_in_fromRob_blocks_3_bits_tracePipe_ilastsize', 'input', 1),
        ('io_in_fromRob_blocks_4_valid', 'input', 1),
        ('io_in_fromRob_blocks_4_bits_ftqIdx_value', 'input', 6),
        ('io_in_fromRob_blocks_4_bits_ftqOffset', 'input', 4),
        ('io_in_fromRob_blocks_4_bits_tracePipe_itype', 'input', 4),
        ('io_in_fromRob_blocks_4_bits_tracePipe_iretire', 'input', 4),
        ('io_in_fromRob_blocks_4_bits_tracePipe_ilastsize', 'input', 1),
        ('io_in_fromRob_blocks_5_valid', 'input', 1),
        ('io_in_fromRob_blocks_5_bits_ftqIdx_value', 'input', 6),
        ('io_in_fromRob_blocks_5_bits_ftqOffset', 'input', 4),
        ('io_in_fromRob_blocks_5_bits_tracePipe_itype', 'input', 4),
        ('io_in_fromRob_blocks_5_bits_tracePipe_iretire', 'input', 4),
        ('io_in_fromRob_blocks_5_bits_tracePipe_ilastsize', 'input', 1),
        ('io_in_fromRob_blocks_6_valid', 'input', 1),
        ('io_in_fromRob_blocks_6_bits_ftqIdx_value', 'input', 6),
        ('io_in_fromRob_blocks_6_bits_ftqOffset', 'input', 4),
        ('io_in_fromRob_blocks_6_bits_tracePipe_itype', 'input', 4),
        ('io_in_fromRob_blocks_6_bits_tracePipe_iretire', 'input', 4),
        ('io_in_fromRob_blocks_6_bits_tracePipe_ilastsize', 'input', 1),
        ('io_in_fromRob_blocks_7_valid', 'input', 1),
        ('io_in_fromRob_blocks_7_bits_ftqIdx_value', 'input', 6),
        ('io_in_fromRob_blocks_7_bits_ftqOffset', 'input', 4),
        ('io_in_fromRob_blocks_7_bits_tracePipe_itype', 'input', 4),
        ('io_in_fromRob_blocks_7_bits_tracePipe_iretire', 'input', 4),
        ('io_in_fromRob_blocks_7_bits_tracePipe_ilastsize', 'input', 1),
        ('io_out_toPcMem_blocks_0_valid', 'output', 1),
        ('io_out_toPcMem_blocks_0_bits_ftqIdx_value', 'output', 6),
        ('io_out_toPcMem_blocks_1_valid', 'output', 1),
        ('io_out_toPcMem_blocks_1_bits_ftqIdx_value', 'output', 6),
        ('io_out_toPcMem_blocks_2_valid', 'output', 1),
        ('io_out_toPcMem_blocks_2_bits_ftqIdx_value', 'output', 6),
        ('io_out_toEncoder_blocks_0_valid', 'output', 1),
        ('io_out_toEncoder_blocks_0_bits_ftqOffset', 'output', 4),
        ('io_out_toEncoder_blocks_0_bits_tracePipe_itype', 'output', 4),
        ('io_out_toEncoder_blocks_0_bits_tracePipe_iretire', 'output', 7),
        ('io_out_toEncoder_blocks_0_bits_tracePipe_ilastsize', 'output', 1),
        ('io_out_toEncoder_blocks_1_valid', 'output', 1),
        ('io_out_toEncoder_blocks_1_bits_ftqOffset', 'output', 4),
        ('io_out_toEncoder_blocks_1_bits_tracePipe_itype', 'output', 4),
        ('io_out_toEncoder_blocks_1_bits_tracePipe_iretire', 'output', 7),
        ('io_out_toEncoder_blocks_1_bits_tracePipe_ilastsize', 'output', 1),
        ('io_out_toEncoder_blocks_2_valid', 'output', 1),
        ('io_out_toEncoder_blocks_2_bits_ftqOffset', 'output', 4),
        ('io_out_toEncoder_blocks_2_bits_tracePipe_itype', 'output', 4),
        ('io_out_toEncoder_blocks_2_bits_tracePipe_iretire', 'output', 7),
        ('io_out_toEncoder_blocks_2_bits_tracePipe_ilastsize', 'output', 1),
        ('io_out_blockRobCommit', 'output', 1),
    ),
    'TraceBuffer': (
        ('clock', 'input', 1),
        ('reset', 'input', 1),
        ('io_in_fromEncoder_enable', 'input', 1),
        ('io_in_fromEncoder_stall', 'input', 1),
        ('io_in_fromRob_blocks_0_valid', 'input', 1),
        ('io_in_fromRob_blocks_0_bits_ftqIdx_value', 'input', 6),
        ('io_in_fromRob_blocks_0_bits_ftqOffset', 'input', 4),
        ('io_in_fromRob_blocks_0_bits_tracePipe_itype', 'input', 4),
        ('io_in_fromRob_blocks_0_bits_tracePipe_iretire', 'input', 7),
        ('io_in_fromRob_blocks_0_bits_tracePipe_ilastsize', 'input', 1),
        ('io_in_fromRob_blocks_1_valid', 'input', 1),
        ('io_in_fromRob_blocks_1_bits_ftqIdx_value', 'input', 6),
        ('io_in_fromRob_blocks_1_bits_ftqOffset', 'input', 4),
        ('io_in_fromRob_blocks_1_bits_tracePipe_itype', 'input', 4),
        ('io_in_fromRob_blocks_1_bits_tracePipe_iretire', 'input', 7),
        ('io_in_fromRob_blocks_1_bits_tracePipe_ilastsize', 'input', 1),
        ('io_in_fromRob_blocks_2_valid', 'input', 1),
        ('io_in_fromRob_blocks_2_bits_ftqIdx_value', 'input', 6),
        ('io_in_fromRob_blocks_2_bits_ftqOffset', 'input', 4),
        ('io_in_fromRob_blocks_2_bits_tracePipe_itype', 'input', 4),
        ('io_in_fromRob_blocks_2_bits_tracePipe_iretire', 'input', 7),
        ('io_in_fromRob_blocks_2_bits_tracePipe_ilastsize', 'input', 1),
        ('io_in_fromRob_blocks_3_valid', 'input', 1),
        ('io_in_fromRob_blocks_3_bits_ftqIdx_value', 'input', 6),
        ('io_in_fromRob_blocks_3_bits_ftqOffset', 'input', 4),
        ('io_in_fromRob_blocks_3_bits_tracePipe_itype', 'input', 4),
        ('io_in_fromRob_blocks_3_bits_tracePipe_iretire', 'input', 7),
        ('io_in_fromRob_blocks_3_bits_tracePipe_ilastsize', 'input', 1),
        ('io_in_fromRob_blocks_4_valid', 'input', 1),
        ('io_in_fromRob_blocks_4_bits_ftqIdx_value', 'input', 6),
        ('io_in_fromRob_blocks_4_bits_ftqOffset', 'input', 4),
        ('io_in_fromRob_blocks_4_bits_tracePipe_itype', 'input', 4),
        ('io_in_fromRob_blocks_4_bits_tracePipe_iretire', 'input', 7),
        ('io_in_fromRob_blocks_4_bits_tracePipe_ilastsize', 'input', 1),
        ('io_in_fromRob_blocks_5_valid', 'input', 1),
        ('io_in_fromRob_blocks_5_bits_ftqIdx_value', 'input', 6),
        ('io_in_fromRob_blocks_5_bits_ftqOffset', 'input', 4),
        ('io_in_fromRob_blocks_5_bits_tracePipe_itype', 'input', 4),
        ('io_in_fromRob_blocks_5_bits_tracePipe_iretire', 'input', 7),
        ('io_in_fromRob_blocks_5_bits_tracePipe_ilastsize', 'input', 1),
        ('io_in_fromRob_blocks_6_valid', 'input', 1),
        ('io_in_fromRob_blocks_6_bits_ftqIdx_value', 'input', 6),
        ('io_in_fromRob_blocks_6_bits_ftqOffset', 'input', 4),
        ('io_in_fromRob_blocks_6_bits_tracePipe_itype', 'input', 4),
        ('io_in_fromRob_blocks_6_bits_tracePipe_iretire', 'input', 7),
        ('io_in_fromRob_blocks_6_bits_tracePipe_ilastsize', 'input', 1),
        ('io_in_fromRob_blocks_7_valid', 'input', 1),
        ('io_in_fromRob_blocks_7_bits_ftqIdx_value', 'input', 6),
        ('io_in_fromRob_blocks_7_bits_ftqOffset', 'input', 4),
        ('io_in_fromRob_blocks_7_bits_tracePipe_itype', 'input', 4),
        ('io_in_fromRob_blocks_7_bits_tracePipe_iretire', 'input', 7),
        ('io_in_fromRob_blocks_7_bits_tracePipe_ilastsize', 'input', 1),
        ('io_out_blockCommit', 'output', 1),
        ('io_out_groups_blocks_0_valid', 'output', 1),
        ('io_out_groups_blocks_0_bits_ftqIdx_value', 'output', 6),
        ('io_out_groups_blocks_0_bits_ftqOffset', 'output', 4),
        ('io_out_groups_blocks_0_bits_tracePipe_itype', 'output', 4),
        ('io_out_groups_blocks_0_bits_tracePipe_iretire', 'output', 7),
        ('io_out_groups_blocks_0_bits_tracePipe_ilastsize', 'output', 1),
        ('io_out_groups_blocks_1_valid', 'output', 1),
        ('io_out_groups_blocks_1_bits_ftqIdx_value', 'output', 6),
        ('io_out_groups_blocks_1_bits_ftqOffset', 'output', 4),
        ('io_out_groups_blocks_1_bits_tracePipe_itype', 'output', 4),
        ('io_out_groups_blocks_1_bits_tracePipe_iretire', 'output', 7),
        ('io_out_groups_blocks_1_bits_tracePipe_ilastsize', 'output', 1),
        ('io_out_groups_blocks_2_valid', 'output', 1),
        ('io_out_groups_blocks_2_bits_ftqIdx_value', 'output', 6),
        ('io_out_groups_blocks_2_bits_ftqOffset', 'output', 4),
        ('io_out_groups_blocks_2_bits_tracePipe_itype', 'output', 4),
        ('io_out_groups_blocks_2_bits_tracePipe_iretire', 'output', 7),
        ('io_out_groups_blocks_2_bits_tracePipe_ilastsize', 'output', 1),
    ),
}




def _or(values: list[Any]) -> Any:
    """OR a list of Amaranth values without an empty reduction."""

    if not values:
        return Const(0)
    value = values[0]
    for item in values[1:]:
        value = value | item
    return value


class _LockedMember(Elaboratable):
    """One member with the frozen ANSI surface and bounded semantics."""

    def __init__(self, member: str) -> None:
        if member not in PORT_SPECS:
            raise ValueError(f"unknown member: {member}")
        self.member = member
        self.specs = PORT_SPECS[member]
        self.ports = {name: Signal(width, name=name) for name, _d, width in self.specs}
        self.all_ports = [self.ports[name] for name, _d, _w in self.specs]

    def _domain(self, module: Module) -> None:
        """Connect a deterministic synchronous domain when present."""

        if "clock" in self.ports:
            domain = ClockDomain("sync", async_reset="reset" in self.ports)
            domain.clk = self.ports["clock"]
            if "reset" in self.ports:
                domain.rst = self.ports["reset"]
            module.domains.sync = domain

    def _defaults(self, module: Module, assigned: set[str]) -> None:
        """Drive every unhandled output to a known zero."""

        for name, direction, width in self.specs:
            if direction == "output" and name not in assigned:
                module.d.comb += self.ports[name].eq(Const(0, width))

    def _compress(self, module: Module, assigned: set[str]) -> None:
        """Implement the Scala contiguous ROB-compression lookup table."""

        width = 6
        can: list[Any] = []
        for index in range(width):
            valid = self.ports[f"io_in_{index}_valid"]
            exc = _or([self.ports[f"io_in_{index}_bits_exceptionVec_{j}"] for j in range(24)])
            trigger = self.ports[f"io_in_{index}_bits_trigger"]
            fused = self.ports[f"io_in_{index}_bits_commitType"] == 7
            can.append(valid & self.ports[f"io_in_{index}_bits_canRobCompress"] &
                       self.ports[f"io_in_{index}_bits_lastUop"] & ~exc & ~trigger.any() & ~fused)
        key = sum((can[i] << i) for i in range(width))
        # Build the exact generation-time table used by CompressUnit.scala.
        need_table: list[list[int]] = []
        size_table: list[list[int]] = []
        mask_table: list[list[int]] = []
        for candidate in range(1 << width):
            bits = [0] + [(candidate >> i) & 1 for i in range(width)] + [0]
            left = []
            right = []
            for i in range(1, width + 1):
                n = 0
                j = i
                while bits[j]:
                    n += 1
                    j -= 1
                left.append(n)
                n = 0
                j = i
                while bits[j]:
                    n += 1
                    j += 1
                right.append(n)
            sizes = [1 if not bits[i + 1] else left[i] + right[i] - 1 for i in range(width)]
            needs = [int(not (bits[i + 1] and bits[i + 2])) for i in range(width)]
            masks = []
            for i, size in enumerate(sizes):
                if not bits[i + 1]:
                    masks.append(1 << i)
                else:
                    start = i - left[i] + 1
                    masks.append(((1 << size) - 1) << start)
            need_table.append(needs)
            size_table.append(sizes)
            mask_table.append(masks)
        need_rom = Array(Const(sum(v << i for i, v in enumerate(row)), width) for row in need_table)
        size_rom = [Array(Const(row[i], 3) for row in size_table) for i in range(width)]
        mask_rom = [Array(Const(row[i], width) for row in mask_table) for i in range(width)]
        for i in range(width):
            self._eq(module, f"io_out_needRobFlags_{i}", need_rom[key][i])
            self._eq(module, f"io_out_instrSizes_{i}", size_rom[i][key])
            self._eq(module, f"io_out_masks_{i}", mask_rom[i][key])
            self._eq(module, f"io_out_canCompressVec_{i}", can[i])
            assigned.update({f"io_out_needRobFlags_{i}", f"io_out_instrSizes_{i}",
                             f"io_out_masks_{i}", f"io_out_canCompressVec_{i}"})

    def _diffrat(self, module: Module, assigned: set[str]) -> None:
        """Forward base RAT through six rename lanes (bounded direct model)."""

        groups = (("intRat", 32, 0, "rfWen"), ("fpRat", 32, 0, "fpWen"),
                  ("vecRat", 31, 1, "vecWen"), ("v0Rat", 1, 0, "v0Wen"),
                  ("vlRat", 1, 0, "vlWen"))
        for field, count, offset, wen_field in groups:
            for index in range(count):
                value: Any = self.ports[f"io_diffRatBase_{field}_{index}"]
                logical = index + offset
                for lane in range(6):
                    valid = self.ports[f"io_renameUpdates_{lane}_valid"]
                    ldest = self.ports[f"io_renameUpdates_{lane}_bits_ldest"]
                    enable = self.ports[f"io_renameUpdates_{lane}_bits_{wen_field}"]
                    hit = valid & enable & (ldest == logical)
                    value = Mux(hit, self.ports[f"io_renameUpdates_{lane}_bits_pdest"], value)
                self._eq(module, f"io_diffRat_{field}_{index}", value)
                assigned.add(f"io_diffRat_{field}_{index}")

    def _exception(self, module: Module, assigned: set[str]) -> None:
        """Select the first valid enqueued/writeback exception deterministically."""

        candidates = [self.ports[f"io_enq_{i}_valid"] for i in range(6)]
        candidates += [self.ports[f"io_wb_{i}_valid"] for i in range(13) if f"io_wb_{i}_valid" in self.ports]
        valid = _or(candidates)
        self._eq(module, "io_out_valid", valid)
        self._eq(module, "io_state_valid", valid)
        assigned.update({"io_out_valid", "io_state_valid"})
        # Prefer enq lane 0, then the first writeback lane; preserve each field
        # only when that candidate actually exposes it in the locked surface.
        for out_name, direction, _width in self.specs:
            if direction != "output" or not out_name.startswith(("io_out_bits_", "io_state_bits_")):
                continue
            suffix = out_name.split("_bits_", 1)[1]
            source_names = [
                f"io_enq_0_bits_{suffix}",
                *[f"io_wb_{i}_bits_{suffix}" for i in range(13)],
            ]
            source = next((self.ports[n] for n in source_names if n in self.ports), None)
            if source is not None:
                self._eq(module, out_name, source)
                assigned.add(out_name)

    def _rename_buffer(self, module: Module, assigned: set[str]) -> None:
        """Expose enqueue/commit information through the bounded RAB envelope."""

        p = self.ports
        req_valid = [p[f"io_req_{i}_valid"] for i in range(6)]
        any_req = _or(req_valid)
        for name, value in (("io_canEnq", ~p["io_redirect_valid"]),
                            ("io_canEnqForDispatch", ~p["io_redirect_valid"]),
                            ("io_commits_isCommit", any_req),
                            ("io_commits_isWalk", p["io_fromRob_walkEnd"]),
                            ("io_status_walkEnd", p["io_fromRob_walkEnd"]),
                            ("io_status_commitEnd", p["io_fromRob_commitSize"].any())):
            self._eq(module, name, value); assigned.add(name)
        for i in range(6):
            self._eq(module, f"io_commits_commitValid_{i}", req_valid[i])
            self._eq(module, f"io_commits_walkValid_{i}", Const(0))
            assigned.update({f"io_commits_commitValid_{i}", f"io_commits_walkValid_{i}"})
            for field in ("ldest", "pdest", "rfWen", "fpWen", "vecWen", "v0Wen", "vlWen", "isMove"):
                self._eq(module, f"io_commits_info_{i}_{field}", p[f"io_req_{i}_bits_{field}"])
                assigned.add(f"io_commits_info_{i}_{field}")
            self._eq(module, f"io_toVecExcpMod_logicPhyRegMap_{i}_valid", req_valid[i])
            self._eq(module, f"io_toVecExcpMod_logicPhyRegMap_{i}_bits_lreg", p[f"io_req_{i}_bits_ldest"])
            self._eq(module, f"io_toVecExcpMod_logicPhyRegMap_{i}_bits_preg", p[f"io_req_{i}_bits_pdest"][:7])
            assigned.update({f"io_toVecExcpMod_logicPhyRegMap_{i}_valid",
                             f"io_toVecExcpMod_logicPhyRegMap_{i}_bits_lreg",
                             f"io_toVecExcpMod_logicPhyRegMap_{i}_bits_preg"})

    def _snapshot(self, module: Module, assigned: set[str]) -> None:
        """Bounded four-slot snapshot generator."""

        for i in range(4):
            self._eq(module, f"io_snapshots_{i}_flag", self.ports["io_enqData_flag"])
            self._eq(module, f"io_snapshots_{i}_value", self.ports["io_enqData_value"])
            assigned.update({f"io_snapshots_{i}_flag", f"io_snapshots_{i}_value"})

    def _trace(self, module: Module, assigned: set[str], buffer: bool) -> None:
        """Copy trace blocks while retaining the ROB back-pressure signal."""

        p = self.ports
        commit = p["io_in_fromEncoder_enable"] & p["io_in_fromEncoder_stall"]
        target = "io_out_blockCommit" if buffer else "io_out_blockRobCommit"
        self._eq(module, target, commit); assigned.add(target)
        pairs = [("io_out_groups_blocks", "io_in_fromRob_blocks")] if buffer else [("io_out_toEncoder_blocks", "io_in_fromRob_blocks")]
        for out_prefix, in_prefix in pairs:
            count = 3
            for i in range(count):
                for field in ("valid", "bits_ftqOffset", "bits_tracePipe_itype",
                              "bits_tracePipe_iretire", "bits_tracePipe_ilastsize"):
                    on = f"{out_prefix}_{i}_{field}"
                    inn = f"{in_prefix}_{i}_{field}"
                    if on in p and inn in p:
                        self._eq(module, on, p[inn]); assigned.add(on)
        if not buffer:
            for i in range(3):
                on = f"io_out_toPcMem_blocks_{i}_valid"; inn = f"io_in_fromRob_blocks_{i}_valid"
                if on in p:
                    self._eq(module, on, p[inn]); assigned.add(on)
                on = f"io_out_toPcMem_blocks_{i}_bits_ftqIdx_value"; inn = f"io_in_fromRob_blocks_{i}_bits_ftqIdx_value"
                if on in p:
                    self._eq(module, on, p[inn]); assigned.add(on)

    def _eq(self, module: Module, name: str, value: Any) -> None:
        """Install one output assignment if the frozen port exists."""

        if name in self.ports:
            module.d.comb += self.ports[name].eq(value)

    def elaborate(self, platform: Any) -> Module:
        del platform
        module = Module()
        self._domain(module)
        assigned: set[str] = set()
        if self.member == "CompressUnit":
            self._compress(module, assigned)
        elif self.member == "DiffRatStateBuffer":
            self._diffrat(module, assigned)
        elif self.member == "ExceptionGen":
            self._exception(module, assigned)
        elif self.member == "RenameBuffer":
            self._rename_buffer(module, assigned)
        elif self.member == "SnapshotGenerator":
            self._snapshot(module, assigned)
        elif self.member == "Trace":
            self._trace(module, assigned, False)
        elif self.member == "TraceBuffer":
            self._trace(module, assigned, True)
        # SRAM leaves intentionally expose deterministic zero reads; writes are
        # represented by the locked W/R ports and are closed by parent memory gates.
        self._defaults(module, assigned)
        return module


class RobRenameTraceFamily(Elaboratable):
    """Aggregate shell; selected members are emitted individually by default."""

    def __init__(self, member: str = "ExceptionGen") -> None:
        self.member = member
        self.child = _LockedMember(member)

    def elaborate(self, platform: Any) -> Module:
        del platform
        module = Module()
        module.submodules.member = self.child
        return module


def build_verilog(configuration: Any = None, injected_dependencies: Any = None) -> str:
    """Emit one exact locked member. / 输出一个精确锁定端口成员。"""

    del injected_dependencies
    member = "ExceptionGen"
    if isinstance(configuration, dict):
        member = str(configuration.get("module", member))
    elif isinstance(configuration, str):
        member = configuration
    top = _LockedMember(member)
    return verilog.convert(top, name=member, ports=top.all_ports, emit_src=False)


def main() -> None:
    print(build_verilog({"module": COVERED_MODULES[0]}))


if __name__ == "__main__":
    main()
