"""UHSC V2 difftest architectural-state family aggregate.
昆明湖 V2 difftest architectural-state family 聚合。

All selected state/event leaves retain their exact locked ANSI surfaces.  The
bounded implementation is deterministic and reset-safe; complete difftest
event semantics remain a top-level reference differential obligation.
"""

from __future__ import annotations

from typing import Any

from amaranth import ClockDomain, Elaboratable, Module, Signal
from amaranth.back import verilog


__all__ = ["COVERED_MODULES", "DifftestStateFamily", "build_verilog", "main"]
COVERED_MODULES = ("DiffExtArchEvent", "DiffExtArchFpRenameTable", "DiffExtArchIntRenameTable", "DiffExtArchVecRenameTable", "DiffExtCSRState", "DiffExtCriticalErrorEvent", "DiffExtDebugMode", "DiffExtFpCSRState", "DiffExtHCSRState", "DiffExtInstrCommit", "DiffExtLrScEvent", "DiffExtMhpmeventOverflowEvent", "DiffExtNonRegInterruptPendingEvent", "DiffExtPhyFpRegState", "DiffExtPhyIntRegState", "DiffExtPhyVecRegState", "DiffExtSyncAIAEvent", "DiffExtSyncCustomMflushpwrEvent", "DiffExtTrapEvent", "DiffExtTriggerCSRState", "DiffExtVecCSRState")
SOURCE_PATHS = ("upstream/difftest/src/main/scala/difftest/ArchEvent.scala", "upstream/difftest/src/main/scala/difftest/CSRState.scala", "upstream/difftest/src/main/scala/difftest/InstrCommit.scala", "upstream/difftest/src/main/scala/difftest/TrapEvent.scala")

# BEGIN LOCKED PORT CATALOG
LOCKED_PORT_SPECS: dict[str, tuple[tuple[str, str, int], ...]] = {
    "DiffExtArchEvent": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "enable",
            "input",
            1,
        ),
        (
            "io_valid",
            "input",
            1,
        ),
        (
            "io_interrupt",
            "input",
            32,
        ),
        (
            "io_exception",
            "input",
            32,
        ),
        (
            "io_exceptionPC",
            "input",
            64,
        ),
        (
            "io_exceptionInst",
            "input",
            32,
        ),
        (
            "io_hasNMI",
            "input",
            1,
        ),
        (
            "io_virtualInterruptIsHvictlInject",
            "input",
            1,
        ),
        (
            "io_irToHS",
            "input",
            1,
        ),
        (
            "io_irToVS",
            "input",
            1,
        ),
        (
            "io_coreid",
            "input",
            8,
        ),
    ),
    "DiffExtArchFpRenameTable": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "enable",
            "input",
            1,
        ),
        (
            "io_value_0",
            "input",
            8,
        ),
        (
            "io_value_1",
            "input",
            8,
        ),
        (
            "io_value_2",
            "input",
            8,
        ),
        (
            "io_value_3",
            "input",
            8,
        ),
        (
            "io_value_4",
            "input",
            8,
        ),
        (
            "io_value_5",
            "input",
            8,
        ),
        (
            "io_value_6",
            "input",
            8,
        ),
        (
            "io_value_7",
            "input",
            8,
        ),
        (
            "io_value_8",
            "input",
            8,
        ),
        (
            "io_value_9",
            "input",
            8,
        ),
        (
            "io_value_10",
            "input",
            8,
        ),
        (
            "io_value_11",
            "input",
            8,
        ),
        (
            "io_value_12",
            "input",
            8,
        ),
        (
            "io_value_13",
            "input",
            8,
        ),
        (
            "io_value_14",
            "input",
            8,
        ),
        (
            "io_value_15",
            "input",
            8,
        ),
        (
            "io_value_16",
            "input",
            8,
        ),
        (
            "io_value_17",
            "input",
            8,
        ),
        (
            "io_value_18",
            "input",
            8,
        ),
        (
            "io_value_19",
            "input",
            8,
        ),
        (
            "io_value_20",
            "input",
            8,
        ),
        (
            "io_value_21",
            "input",
            8,
        ),
        (
            "io_value_22",
            "input",
            8,
        ),
        (
            "io_value_23",
            "input",
            8,
        ),
        (
            "io_value_24",
            "input",
            8,
        ),
        (
            "io_value_25",
            "input",
            8,
        ),
        (
            "io_value_26",
            "input",
            8,
        ),
        (
            "io_value_27",
            "input",
            8,
        ),
        (
            "io_value_28",
            "input",
            8,
        ),
        (
            "io_value_29",
            "input",
            8,
        ),
        (
            "io_value_30",
            "input",
            8,
        ),
        (
            "io_value_31",
            "input",
            8,
        ),
        (
            "io_coreid",
            "input",
            8,
        ),
    ),
    "DiffExtArchIntRenameTable": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "enable",
            "input",
            1,
        ),
        (
            "io_value_0",
            "input",
            8,
        ),
        (
            "io_value_1",
            "input",
            8,
        ),
        (
            "io_value_2",
            "input",
            8,
        ),
        (
            "io_value_3",
            "input",
            8,
        ),
        (
            "io_value_4",
            "input",
            8,
        ),
        (
            "io_value_5",
            "input",
            8,
        ),
        (
            "io_value_6",
            "input",
            8,
        ),
        (
            "io_value_7",
            "input",
            8,
        ),
        (
            "io_value_8",
            "input",
            8,
        ),
        (
            "io_value_9",
            "input",
            8,
        ),
        (
            "io_value_10",
            "input",
            8,
        ),
        (
            "io_value_11",
            "input",
            8,
        ),
        (
            "io_value_12",
            "input",
            8,
        ),
        (
            "io_value_13",
            "input",
            8,
        ),
        (
            "io_value_14",
            "input",
            8,
        ),
        (
            "io_value_15",
            "input",
            8,
        ),
        (
            "io_value_16",
            "input",
            8,
        ),
        (
            "io_value_17",
            "input",
            8,
        ),
        (
            "io_value_18",
            "input",
            8,
        ),
        (
            "io_value_19",
            "input",
            8,
        ),
        (
            "io_value_20",
            "input",
            8,
        ),
        (
            "io_value_21",
            "input",
            8,
        ),
        (
            "io_value_22",
            "input",
            8,
        ),
        (
            "io_value_23",
            "input",
            8,
        ),
        (
            "io_value_24",
            "input",
            8,
        ),
        (
            "io_value_25",
            "input",
            8,
        ),
        (
            "io_value_26",
            "input",
            8,
        ),
        (
            "io_value_27",
            "input",
            8,
        ),
        (
            "io_value_28",
            "input",
            8,
        ),
        (
            "io_value_29",
            "input",
            8,
        ),
        (
            "io_value_30",
            "input",
            8,
        ),
        (
            "io_value_31",
            "input",
            8,
        ),
        (
            "io_coreid",
            "input",
            8,
        ),
    ),
    "DiffExtArchVecRenameTable": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "enable",
            "input",
            1,
        ),
        (
            "io_value_0",
            "input",
            9,
        ),
        (
            "io_value_1",
            "input",
            9,
        ),
        (
            "io_value_2",
            "input",
            9,
        ),
        (
            "io_value_3",
            "input",
            9,
        ),
        (
            "io_value_4",
            "input",
            9,
        ),
        (
            "io_value_5",
            "input",
            9,
        ),
        (
            "io_value_6",
            "input",
            9,
        ),
        (
            "io_value_7",
            "input",
            9,
        ),
        (
            "io_value_8",
            "input",
            9,
        ),
        (
            "io_value_9",
            "input",
            9,
        ),
        (
            "io_value_10",
            "input",
            9,
        ),
        (
            "io_value_11",
            "input",
            9,
        ),
        (
            "io_value_12",
            "input",
            9,
        ),
        (
            "io_value_13",
            "input",
            9,
        ),
        (
            "io_value_14",
            "input",
            9,
        ),
        (
            "io_value_15",
            "input",
            9,
        ),
        (
            "io_value_16",
            "input",
            9,
        ),
        (
            "io_value_17",
            "input",
            9,
        ),
        (
            "io_value_18",
            "input",
            9,
        ),
        (
            "io_value_19",
            "input",
            9,
        ),
        (
            "io_value_20",
            "input",
            9,
        ),
        (
            "io_value_21",
            "input",
            9,
        ),
        (
            "io_value_22",
            "input",
            9,
        ),
        (
            "io_value_23",
            "input",
            9,
        ),
        (
            "io_value_24",
            "input",
            9,
        ),
        (
            "io_value_25",
            "input",
            9,
        ),
        (
            "io_value_26",
            "input",
            9,
        ),
        (
            "io_value_27",
            "input",
            9,
        ),
        (
            "io_value_28",
            "input",
            9,
        ),
        (
            "io_value_29",
            "input",
            9,
        ),
        (
            "io_value_30",
            "input",
            9,
        ),
        (
            "io_value_31",
            "input",
            9,
        ),
        (
            "io_value_32",
            "input",
            9,
        ),
        (
            "io_value_33",
            "input",
            9,
        ),
        (
            "io_value_34",
            "input",
            9,
        ),
        (
            "io_value_35",
            "input",
            9,
        ),
        (
            "io_value_36",
            "input",
            9,
        ),
        (
            "io_value_37",
            "input",
            9,
        ),
        (
            "io_value_38",
            "input",
            9,
        ),
        (
            "io_value_39",
            "input",
            9,
        ),
        (
            "io_value_40",
            "input",
            9,
        ),
        (
            "io_value_41",
            "input",
            9,
        ),
        (
            "io_value_42",
            "input",
            9,
        ),
        (
            "io_value_43",
            "input",
            9,
        ),
        (
            "io_value_44",
            "input",
            9,
        ),
        (
            "io_value_45",
            "input",
            9,
        ),
        (
            "io_value_46",
            "input",
            9,
        ),
        (
            "io_value_47",
            "input",
            9,
        ),
        (
            "io_value_48",
            "input",
            9,
        ),
        (
            "io_value_49",
            "input",
            9,
        ),
        (
            "io_value_50",
            "input",
            9,
        ),
        (
            "io_value_51",
            "input",
            9,
        ),
        (
            "io_value_52",
            "input",
            9,
        ),
        (
            "io_value_53",
            "input",
            9,
        ),
        (
            "io_value_54",
            "input",
            9,
        ),
        (
            "io_value_55",
            "input",
            9,
        ),
        (
            "io_value_56",
            "input",
            9,
        ),
        (
            "io_value_57",
            "input",
            9,
        ),
        (
            "io_value_58",
            "input",
            9,
        ),
        (
            "io_value_59",
            "input",
            9,
        ),
        (
            "io_value_60",
            "input",
            9,
        ),
        (
            "io_value_61",
            "input",
            9,
        ),
        (
            "io_value_62",
            "input",
            9,
        ),
        (
            "io_value_63",
            "input",
            9,
        ),
        (
            "io_coreid",
            "input",
            8,
        ),
    ),
    "DiffExtCSRState": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "enable",
            "input",
            1,
        ),
        (
            "io_privilegeMode",
            "input",
            64,
        ),
        (
            "io_mstatus",
            "input",
            64,
        ),
        (
            "io_sstatus",
            "input",
            64,
        ),
        (
            "io_mepc",
            "input",
            64,
        ),
        (
            "io_sepc",
            "input",
            64,
        ),
        (
            "io_mtval",
            "input",
            64,
        ),
        (
            "io_stval",
            "input",
            64,
        ),
        (
            "io_mtvec",
            "input",
            64,
        ),
        (
            "io_stvec",
            "input",
            64,
        ),
        (
            "io_mcause",
            "input",
            64,
        ),
        (
            "io_scause",
            "input",
            64,
        ),
        (
            "io_satp",
            "input",
            64,
        ),
        (
            "io_mip",
            "input",
            64,
        ),
        (
            "io_mie",
            "input",
            64,
        ),
        (
            "io_mscratch",
            "input",
            64,
        ),
        (
            "io_sscratch",
            "input",
            64,
        ),
        (
            "io_mideleg",
            "input",
            64,
        ),
        (
            "io_medeleg",
            "input",
            64,
        ),
        (
            "io_coreid",
            "input",
            8,
        ),
    ),
    "DiffExtCriticalErrorEvent": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "enable",
            "input",
            1,
        ),
        (
            "io_valid",
            "input",
            1,
        ),
        (
            "io_criticalError",
            "input",
            1,
        ),
        (
            "io_coreid",
            "input",
            8,
        ),
    ),
    "DiffExtDebugMode": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "enable",
            "input",
            1,
        ),
        (
            "io_debugMode",
            "input",
            1,
        ),
        (
            "io_dcsr",
            "input",
            64,
        ),
        (
            "io_dpc",
            "input",
            64,
        ),
        (
            "io_dscratch0",
            "input",
            64,
        ),
        (
            "io_dscratch1",
            "input",
            64,
        ),
        (
            "io_coreid",
            "input",
            8,
        ),
    ),
    "DiffExtFpCSRState": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "enable",
            "input",
            1,
        ),
        (
            "io_fcsr",
            "input",
            64,
        ),
        (
            "io_coreid",
            "input",
            8,
        ),
    ),
    "DiffExtHCSRState": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "enable",
            "input",
            1,
        ),
        (
            "io_virtMode",
            "input",
            64,
        ),
        (
            "io_mtval2",
            "input",
            64,
        ),
        (
            "io_mtinst",
            "input",
            64,
        ),
        (
            "io_hstatus",
            "input",
            64,
        ),
        (
            "io_hideleg",
            "input",
            64,
        ),
        (
            "io_hedeleg",
            "input",
            64,
        ),
        (
            "io_hcounteren",
            "input",
            64,
        ),
        (
            "io_htval",
            "input",
            64,
        ),
        (
            "io_htinst",
            "input",
            64,
        ),
        (
            "io_hgatp",
            "input",
            64,
        ),
        (
            "io_vsstatus",
            "input",
            64,
        ),
        (
            "io_vstvec",
            "input",
            64,
        ),
        (
            "io_vsepc",
            "input",
            64,
        ),
        (
            "io_vscause",
            "input",
            64,
        ),
        (
            "io_vstval",
            "input",
            64,
        ),
        (
            "io_vsatp",
            "input",
            64,
        ),
        (
            "io_vsscratch",
            "input",
            64,
        ),
        (
            "io_coreid",
            "input",
            8,
        ),
    ),
    "DiffExtInstrCommit": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "enable",
            "input",
            1,
        ),
        (
            "io_valid",
            "input",
            1,
        ),
        (
            "io_skip",
            "input",
            1,
        ),
        (
            "io_isRVC",
            "input",
            1,
        ),
        (
            "io_rfwen",
            "input",
            1,
        ),
        (
            "io_fpwen",
            "input",
            1,
        ),
        (
            "io_vecwen",
            "input",
            1,
        ),
        (
            "io_v0wen",
            "input",
            1,
        ),
        (
            "io_wpdest",
            "input",
            9,
        ),
        (
            "io_wdest",
            "input",
            8,
        ),
        (
            "io_otherwpdest_0",
            "input",
            9,
        ),
        (
            "io_otherwpdest_1",
            "input",
            9,
        ),
        (
            "io_otherwpdest_2",
            "input",
            9,
        ),
        (
            "io_otherwpdest_3",
            "input",
            9,
        ),
        (
            "io_otherwpdest_4",
            "input",
            9,
        ),
        (
            "io_otherwpdest_5",
            "input",
            9,
        ),
        (
            "io_otherwpdest_6",
            "input",
            9,
        ),
        (
            "io_otherwpdest_7",
            "input",
            9,
        ),
        (
            "io_otherwpdest_8",
            "input",
            9,
        ),
        (
            "io_otherwpdest_9",
            "input",
            9,
        ),
        (
            "io_otherwpdest_10",
            "input",
            9,
        ),
        (
            "io_otherwpdest_11",
            "input",
            9,
        ),
        (
            "io_otherwpdest_12",
            "input",
            9,
        ),
        (
            "io_otherwpdest_13",
            "input",
            9,
        ),
        (
            "io_otherwpdest_14",
            "input",
            9,
        ),
        (
            "io_otherwpdest_15",
            "input",
            9,
        ),
        (
            "io_pc",
            "input",
            64,
        ),
        (
            "io_instr",
            "input",
            32,
        ),
        (
            "io_robIdx",
            "input",
            10,
        ),
        (
            "io_lqIdx",
            "input",
            7,
        ),
        (
            "io_sqIdx",
            "input",
            7,
        ),
        (
            "io_isLoad",
            "input",
            1,
        ),
        (
            "io_isStore",
            "input",
            1,
        ),
        (
            "io_nFused",
            "input",
            8,
        ),
        (
            "io_special",
            "input",
            8,
        ),
        (
            "io_coreid",
            "input",
            8,
        ),
        (
            "io_index",
            "input",
            8,
        ),
    ),
    "DiffExtLrScEvent": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "enable",
            "input",
            1,
        ),
        (
            "io_valid",
            "input",
            1,
        ),
        (
            "io_success",
            "input",
            1,
        ),
        (
            "io_coreid",
            "input",
            8,
        ),
    ),
    "DiffExtMhpmeventOverflowEvent": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "enable",
            "input",
            1,
        ),
        (
            "io_valid",
            "input",
            1,
        ),
        (
            "io_mhpmeventOverflow",
            "input",
            64,
        ),
        (
            "io_coreid",
            "input",
            8,
        ),
    ),
    "DiffExtNonRegInterruptPendingEvent": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "enable",
            "input",
            1,
        ),
        (
            "io_valid",
            "input",
            1,
        ),
        (
            "io_platformIRPMeip",
            "input",
            1,
        ),
        (
            "io_platformIRPMtip",
            "input",
            1,
        ),
        (
            "io_platformIRPMsip",
            "input",
            1,
        ),
        (
            "io_platformIRPSeip",
            "input",
            1,
        ),
        (
            "io_platformIRPStip",
            "input",
            1,
        ),
        (
            "io_platformIRPVseip",
            "input",
            1,
        ),
        (
            "io_platformIRPVstip",
            "input",
            1,
        ),
        (
            "io_fromAIAMeip",
            "input",
            1,
        ),
        (
            "io_fromAIASeip",
            "input",
            1,
        ),
        (
            "io_localCounterOverflowInterruptReq",
            "input",
            1,
        ),
        (
            "io_coreid",
            "input",
            8,
        ),
    ),
    "DiffExtPhyFpRegState": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "enable",
            "input",
            1,
        ),
        (
            "io_value_0",
            "input",
            64,
        ),
        (
            "io_value_1",
            "input",
            64,
        ),
        (
            "io_value_2",
            "input",
            64,
        ),
        (
            "io_value_3",
            "input",
            64,
        ),
        (
            "io_value_4",
            "input",
            64,
        ),
        (
            "io_value_5",
            "input",
            64,
        ),
        (
            "io_value_6",
            "input",
            64,
        ),
        (
            "io_value_7",
            "input",
            64,
        ),
        (
            "io_value_8",
            "input",
            64,
        ),
        (
            "io_value_9",
            "input",
            64,
        ),
        (
            "io_value_10",
            "input",
            64,
        ),
        (
            "io_value_11",
            "input",
            64,
        ),
        (
            "io_value_12",
            "input",
            64,
        ),
        (
            "io_value_13",
            "input",
            64,
        ),
        (
            "io_value_14",
            "input",
            64,
        ),
        (
            "io_value_15",
            "input",
            64,
        ),
        (
            "io_value_16",
            "input",
            64,
        ),
        (
            "io_value_17",
            "input",
            64,
        ),
        (
            "io_value_18",
            "input",
            64,
        ),
        (
            "io_value_19",
            "input",
            64,
        ),
        (
            "io_value_20",
            "input",
            64,
        ),
        (
            "io_value_21",
            "input",
            64,
        ),
        (
            "io_value_22",
            "input",
            64,
        ),
        (
            "io_value_23",
            "input",
            64,
        ),
        (
            "io_value_24",
            "input",
            64,
        ),
        (
            "io_value_25",
            "input",
            64,
        ),
        (
            "io_value_26",
            "input",
            64,
        ),
        (
            "io_value_27",
            "input",
            64,
        ),
        (
            "io_value_28",
            "input",
            64,
        ),
        (
            "io_value_29",
            "input",
            64,
        ),
        (
            "io_value_30",
            "input",
            64,
        ),
        (
            "io_value_31",
            "input",
            64,
        ),
        (
            "io_value_32",
            "input",
            64,
        ),
        (
            "io_value_33",
            "input",
            64,
        ),
        (
            "io_value_34",
            "input",
            64,
        ),
        (
            "io_value_35",
            "input",
            64,
        ),
        (
            "io_value_36",
            "input",
            64,
        ),
        (
            "io_value_37",
            "input",
            64,
        ),
        (
            "io_value_38",
            "input",
            64,
        ),
        (
            "io_value_39",
            "input",
            64,
        ),
        (
            "io_value_40",
            "input",
            64,
        ),
        (
            "io_value_41",
            "input",
            64,
        ),
        (
            "io_value_42",
            "input",
            64,
        ),
        (
            "io_value_43",
            "input",
            64,
        ),
        (
            "io_value_44",
            "input",
            64,
        ),
        (
            "io_value_45",
            "input",
            64,
        ),
        (
            "io_value_46",
            "input",
            64,
        ),
        (
            "io_value_47",
            "input",
            64,
        ),
        (
            "io_value_48",
            "input",
            64,
        ),
        (
            "io_value_49",
            "input",
            64,
        ),
        (
            "io_value_50",
            "input",
            64,
        ),
        (
            "io_value_51",
            "input",
            64,
        ),
        (
            "io_value_52",
            "input",
            64,
        ),
        (
            "io_value_53",
            "input",
            64,
        ),
        (
            "io_value_54",
            "input",
            64,
        ),
        (
            "io_value_55",
            "input",
            64,
        ),
        (
            "io_value_56",
            "input",
            64,
        ),
        (
            "io_value_57",
            "input",
            64,
        ),
        (
            "io_value_58",
            "input",
            64,
        ),
        (
            "io_value_59",
            "input",
            64,
        ),
        (
            "io_value_60",
            "input",
            64,
        ),
        (
            "io_value_61",
            "input",
            64,
        ),
        (
            "io_value_62",
            "input",
            64,
        ),
        (
            "io_value_63",
            "input",
            64,
        ),
        (
            "io_value_64",
            "input",
            64,
        ),
        (
            "io_value_65",
            "input",
            64,
        ),
        (
            "io_value_66",
            "input",
            64,
        ),
        (
            "io_value_67",
            "input",
            64,
        ),
        (
            "io_value_68",
            "input",
            64,
        ),
        (
            "io_value_69",
            "input",
            64,
        ),
        (
            "io_value_70",
            "input",
            64,
        ),
        (
            "io_value_71",
            "input",
            64,
        ),
        (
            "io_value_72",
            "input",
            64,
        ),
        (
            "io_value_73",
            "input",
            64,
        ),
        (
            "io_value_74",
            "input",
            64,
        ),
        (
            "io_value_75",
            "input",
            64,
        ),
        (
            "io_value_76",
            "input",
            64,
        ),
        (
            "io_value_77",
            "input",
            64,
        ),
        (
            "io_value_78",
            "input",
            64,
        ),
        (
            "io_value_79",
            "input",
            64,
        ),
        (
            "io_value_80",
            "input",
            64,
        ),
        (
            "io_value_81",
            "input",
            64,
        ),
        (
            "io_value_82",
            "input",
            64,
        ),
        (
            "io_value_83",
            "input",
            64,
        ),
        (
            "io_value_84",
            "input",
            64,
        ),
        (
            "io_value_85",
            "input",
            64,
        ),
        (
            "io_value_86",
            "input",
            64,
        ),
        (
            "io_value_87",
            "input",
            64,
        ),
        (
            "io_value_88",
            "input",
            64,
        ),
        (
            "io_value_89",
            "input",
            64,
        ),
        (
            "io_value_90",
            "input",
            64,
        ),
        (
            "io_value_91",
            "input",
            64,
        ),
        (
            "io_value_92",
            "input",
            64,
        ),
        (
            "io_value_93",
            "input",
            64,
        ),
        (
            "io_value_94",
            "input",
            64,
        ),
        (
            "io_value_95",
            "input",
            64,
        ),
        (
            "io_value_96",
            "input",
            64,
        ),
        (
            "io_value_97",
            "input",
            64,
        ),
        (
            "io_value_98",
            "input",
            64,
        ),
        (
            "io_value_99",
            "input",
            64,
        ),
        (
            "io_value_100",
            "input",
            64,
        ),
        (
            "io_value_101",
            "input",
            64,
        ),
        (
            "io_value_102",
            "input",
            64,
        ),
        (
            "io_value_103",
            "input",
            64,
        ),
        (
            "io_value_104",
            "input",
            64,
        ),
        (
            "io_value_105",
            "input",
            64,
        ),
        (
            "io_value_106",
            "input",
            64,
        ),
        (
            "io_value_107",
            "input",
            64,
        ),
        (
            "io_value_108",
            "input",
            64,
        ),
        (
            "io_value_109",
            "input",
            64,
        ),
        (
            "io_value_110",
            "input",
            64,
        ),
        (
            "io_value_111",
            "input",
            64,
        ),
        (
            "io_value_112",
            "input",
            64,
        ),
        (
            "io_value_113",
            "input",
            64,
        ),
        (
            "io_value_114",
            "input",
            64,
        ),
        (
            "io_value_115",
            "input",
            64,
        ),
        (
            "io_value_116",
            "input",
            64,
        ),
        (
            "io_value_117",
            "input",
            64,
        ),
        (
            "io_value_118",
            "input",
            64,
        ),
        (
            "io_value_119",
            "input",
            64,
        ),
        (
            "io_value_120",
            "input",
            64,
        ),
        (
            "io_value_121",
            "input",
            64,
        ),
        (
            "io_value_122",
            "input",
            64,
        ),
        (
            "io_value_123",
            "input",
            64,
        ),
        (
            "io_value_124",
            "input",
            64,
        ),
        (
            "io_value_125",
            "input",
            64,
        ),
        (
            "io_value_126",
            "input",
            64,
        ),
        (
            "io_value_127",
            "input",
            64,
        ),
        (
            "io_value_128",
            "input",
            64,
        ),
        (
            "io_value_129",
            "input",
            64,
        ),
        (
            "io_value_130",
            "input",
            64,
        ),
        (
            "io_value_131",
            "input",
            64,
        ),
        (
            "io_value_132",
            "input",
            64,
        ),
        (
            "io_value_133",
            "input",
            64,
        ),
        (
            "io_value_134",
            "input",
            64,
        ),
        (
            "io_value_135",
            "input",
            64,
        ),
        (
            "io_value_136",
            "input",
            64,
        ),
        (
            "io_value_137",
            "input",
            64,
        ),
        (
            "io_value_138",
            "input",
            64,
        ),
        (
            "io_value_139",
            "input",
            64,
        ),
        (
            "io_value_140",
            "input",
            64,
        ),
        (
            "io_value_141",
            "input",
            64,
        ),
        (
            "io_value_142",
            "input",
            64,
        ),
        (
            "io_value_143",
            "input",
            64,
        ),
        (
            "io_value_144",
            "input",
            64,
        ),
        (
            "io_value_145",
            "input",
            64,
        ),
        (
            "io_value_146",
            "input",
            64,
        ),
        (
            "io_value_147",
            "input",
            64,
        ),
        (
            "io_value_148",
            "input",
            64,
        ),
        (
            "io_value_149",
            "input",
            64,
        ),
        (
            "io_value_150",
            "input",
            64,
        ),
        (
            "io_value_151",
            "input",
            64,
        ),
        (
            "io_value_152",
            "input",
            64,
        ),
        (
            "io_value_153",
            "input",
            64,
        ),
        (
            "io_value_154",
            "input",
            64,
        ),
        (
            "io_value_155",
            "input",
            64,
        ),
        (
            "io_value_156",
            "input",
            64,
        ),
        (
            "io_value_157",
            "input",
            64,
        ),
        (
            "io_value_158",
            "input",
            64,
        ),
        (
            "io_value_159",
            "input",
            64,
        ),
        (
            "io_value_160",
            "input",
            64,
        ),
        (
            "io_value_161",
            "input",
            64,
        ),
        (
            "io_value_162",
            "input",
            64,
        ),
        (
            "io_value_163",
            "input",
            64,
        ),
        (
            "io_value_164",
            "input",
            64,
        ),
        (
            "io_value_165",
            "input",
            64,
        ),
        (
            "io_value_166",
            "input",
            64,
        ),
        (
            "io_value_167",
            "input",
            64,
        ),
        (
            "io_value_168",
            "input",
            64,
        ),
        (
            "io_value_169",
            "input",
            64,
        ),
        (
            "io_value_170",
            "input",
            64,
        ),
        (
            "io_value_171",
            "input",
            64,
        ),
        (
            "io_value_172",
            "input",
            64,
        ),
        (
            "io_value_173",
            "input",
            64,
        ),
        (
            "io_value_174",
            "input",
            64,
        ),
        (
            "io_value_175",
            "input",
            64,
        ),
        (
            "io_value_176",
            "input",
            64,
        ),
        (
            "io_value_177",
            "input",
            64,
        ),
        (
            "io_value_178",
            "input",
            64,
        ),
        (
            "io_value_179",
            "input",
            64,
        ),
        (
            "io_value_180",
            "input",
            64,
        ),
        (
            "io_value_181",
            "input",
            64,
        ),
        (
            "io_value_182",
            "input",
            64,
        ),
        (
            "io_value_183",
            "input",
            64,
        ),
        (
            "io_value_184",
            "input",
            64,
        ),
        (
            "io_value_185",
            "input",
            64,
        ),
        (
            "io_value_186",
            "input",
            64,
        ),
        (
            "io_value_187",
            "input",
            64,
        ),
        (
            "io_value_188",
            "input",
            64,
        ),
        (
            "io_value_189",
            "input",
            64,
        ),
        (
            "io_value_190",
            "input",
            64,
        ),
        (
            "io_value_191",
            "input",
            64,
        ),
        (
            "io_coreid",
            "input",
            8,
        ),
    ),
    "DiffExtPhyIntRegState": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "enable",
            "input",
            1,
        ),
        (
            "io_value_0",
            "input",
            64,
        ),
        (
            "io_value_1",
            "input",
            64,
        ),
        (
            "io_value_2",
            "input",
            64,
        ),
        (
            "io_value_3",
            "input",
            64,
        ),
        (
            "io_value_4",
            "input",
            64,
        ),
        (
            "io_value_5",
            "input",
            64,
        ),
        (
            "io_value_6",
            "input",
            64,
        ),
        (
            "io_value_7",
            "input",
            64,
        ),
        (
            "io_value_8",
            "input",
            64,
        ),
        (
            "io_value_9",
            "input",
            64,
        ),
        (
            "io_value_10",
            "input",
            64,
        ),
        (
            "io_value_11",
            "input",
            64,
        ),
        (
            "io_value_12",
            "input",
            64,
        ),
        (
            "io_value_13",
            "input",
            64,
        ),
        (
            "io_value_14",
            "input",
            64,
        ),
        (
            "io_value_15",
            "input",
            64,
        ),
        (
            "io_value_16",
            "input",
            64,
        ),
        (
            "io_value_17",
            "input",
            64,
        ),
        (
            "io_value_18",
            "input",
            64,
        ),
        (
            "io_value_19",
            "input",
            64,
        ),
        (
            "io_value_20",
            "input",
            64,
        ),
        (
            "io_value_21",
            "input",
            64,
        ),
        (
            "io_value_22",
            "input",
            64,
        ),
        (
            "io_value_23",
            "input",
            64,
        ),
        (
            "io_value_24",
            "input",
            64,
        ),
        (
            "io_value_25",
            "input",
            64,
        ),
        (
            "io_value_26",
            "input",
            64,
        ),
        (
            "io_value_27",
            "input",
            64,
        ),
        (
            "io_value_28",
            "input",
            64,
        ),
        (
            "io_value_29",
            "input",
            64,
        ),
        (
            "io_value_30",
            "input",
            64,
        ),
        (
            "io_value_31",
            "input",
            64,
        ),
        (
            "io_value_32",
            "input",
            64,
        ),
        (
            "io_value_33",
            "input",
            64,
        ),
        (
            "io_value_34",
            "input",
            64,
        ),
        (
            "io_value_35",
            "input",
            64,
        ),
        (
            "io_value_36",
            "input",
            64,
        ),
        (
            "io_value_37",
            "input",
            64,
        ),
        (
            "io_value_38",
            "input",
            64,
        ),
        (
            "io_value_39",
            "input",
            64,
        ),
        (
            "io_value_40",
            "input",
            64,
        ),
        (
            "io_value_41",
            "input",
            64,
        ),
        (
            "io_value_42",
            "input",
            64,
        ),
        (
            "io_value_43",
            "input",
            64,
        ),
        (
            "io_value_44",
            "input",
            64,
        ),
        (
            "io_value_45",
            "input",
            64,
        ),
        (
            "io_value_46",
            "input",
            64,
        ),
        (
            "io_value_47",
            "input",
            64,
        ),
        (
            "io_value_48",
            "input",
            64,
        ),
        (
            "io_value_49",
            "input",
            64,
        ),
        (
            "io_value_50",
            "input",
            64,
        ),
        (
            "io_value_51",
            "input",
            64,
        ),
        (
            "io_value_52",
            "input",
            64,
        ),
        (
            "io_value_53",
            "input",
            64,
        ),
        (
            "io_value_54",
            "input",
            64,
        ),
        (
            "io_value_55",
            "input",
            64,
        ),
        (
            "io_value_56",
            "input",
            64,
        ),
        (
            "io_value_57",
            "input",
            64,
        ),
        (
            "io_value_58",
            "input",
            64,
        ),
        (
            "io_value_59",
            "input",
            64,
        ),
        (
            "io_value_60",
            "input",
            64,
        ),
        (
            "io_value_61",
            "input",
            64,
        ),
        (
            "io_value_62",
            "input",
            64,
        ),
        (
            "io_value_63",
            "input",
            64,
        ),
        (
            "io_value_64",
            "input",
            64,
        ),
        (
            "io_value_65",
            "input",
            64,
        ),
        (
            "io_value_66",
            "input",
            64,
        ),
        (
            "io_value_67",
            "input",
            64,
        ),
        (
            "io_value_68",
            "input",
            64,
        ),
        (
            "io_value_69",
            "input",
            64,
        ),
        (
            "io_value_70",
            "input",
            64,
        ),
        (
            "io_value_71",
            "input",
            64,
        ),
        (
            "io_value_72",
            "input",
            64,
        ),
        (
            "io_value_73",
            "input",
            64,
        ),
        (
            "io_value_74",
            "input",
            64,
        ),
        (
            "io_value_75",
            "input",
            64,
        ),
        (
            "io_value_76",
            "input",
            64,
        ),
        (
            "io_value_77",
            "input",
            64,
        ),
        (
            "io_value_78",
            "input",
            64,
        ),
        (
            "io_value_79",
            "input",
            64,
        ),
        (
            "io_value_80",
            "input",
            64,
        ),
        (
            "io_value_81",
            "input",
            64,
        ),
        (
            "io_value_82",
            "input",
            64,
        ),
        (
            "io_value_83",
            "input",
            64,
        ),
        (
            "io_value_84",
            "input",
            64,
        ),
        (
            "io_value_85",
            "input",
            64,
        ),
        (
            "io_value_86",
            "input",
            64,
        ),
        (
            "io_value_87",
            "input",
            64,
        ),
        (
            "io_value_88",
            "input",
            64,
        ),
        (
            "io_value_89",
            "input",
            64,
        ),
        (
            "io_value_90",
            "input",
            64,
        ),
        (
            "io_value_91",
            "input",
            64,
        ),
        (
            "io_value_92",
            "input",
            64,
        ),
        (
            "io_value_93",
            "input",
            64,
        ),
        (
            "io_value_94",
            "input",
            64,
        ),
        (
            "io_value_95",
            "input",
            64,
        ),
        (
            "io_value_96",
            "input",
            64,
        ),
        (
            "io_value_97",
            "input",
            64,
        ),
        (
            "io_value_98",
            "input",
            64,
        ),
        (
            "io_value_99",
            "input",
            64,
        ),
        (
            "io_value_100",
            "input",
            64,
        ),
        (
            "io_value_101",
            "input",
            64,
        ),
        (
            "io_value_102",
            "input",
            64,
        ),
        (
            "io_value_103",
            "input",
            64,
        ),
        (
            "io_value_104",
            "input",
            64,
        ),
        (
            "io_value_105",
            "input",
            64,
        ),
        (
            "io_value_106",
            "input",
            64,
        ),
        (
            "io_value_107",
            "input",
            64,
        ),
        (
            "io_value_108",
            "input",
            64,
        ),
        (
            "io_value_109",
            "input",
            64,
        ),
        (
            "io_value_110",
            "input",
            64,
        ),
        (
            "io_value_111",
            "input",
            64,
        ),
        (
            "io_value_112",
            "input",
            64,
        ),
        (
            "io_value_113",
            "input",
            64,
        ),
        (
            "io_value_114",
            "input",
            64,
        ),
        (
            "io_value_115",
            "input",
            64,
        ),
        (
            "io_value_116",
            "input",
            64,
        ),
        (
            "io_value_117",
            "input",
            64,
        ),
        (
            "io_value_118",
            "input",
            64,
        ),
        (
            "io_value_119",
            "input",
            64,
        ),
        (
            "io_value_120",
            "input",
            64,
        ),
        (
            "io_value_121",
            "input",
            64,
        ),
        (
            "io_value_122",
            "input",
            64,
        ),
        (
            "io_value_123",
            "input",
            64,
        ),
        (
            "io_value_124",
            "input",
            64,
        ),
        (
            "io_value_125",
            "input",
            64,
        ),
        (
            "io_value_126",
            "input",
            64,
        ),
        (
            "io_value_127",
            "input",
            64,
        ),
        (
            "io_value_128",
            "input",
            64,
        ),
        (
            "io_value_129",
            "input",
            64,
        ),
        (
            "io_value_130",
            "input",
            64,
        ),
        (
            "io_value_131",
            "input",
            64,
        ),
        (
            "io_value_132",
            "input",
            64,
        ),
        (
            "io_value_133",
            "input",
            64,
        ),
        (
            "io_value_134",
            "input",
            64,
        ),
        (
            "io_value_135",
            "input",
            64,
        ),
        (
            "io_value_136",
            "input",
            64,
        ),
        (
            "io_value_137",
            "input",
            64,
        ),
        (
            "io_value_138",
            "input",
            64,
        ),
        (
            "io_value_139",
            "input",
            64,
        ),
        (
            "io_value_140",
            "input",
            64,
        ),
        (
            "io_value_141",
            "input",
            64,
        ),
        (
            "io_value_142",
            "input",
            64,
        ),
        (
            "io_value_143",
            "input",
            64,
        ),
        (
            "io_value_144",
            "input",
            64,
        ),
        (
            "io_value_145",
            "input",
            64,
        ),
        (
            "io_value_146",
            "input",
            64,
        ),
        (
            "io_value_147",
            "input",
            64,
        ),
        (
            "io_value_148",
            "input",
            64,
        ),
        (
            "io_value_149",
            "input",
            64,
        ),
        (
            "io_value_150",
            "input",
            64,
        ),
        (
            "io_value_151",
            "input",
            64,
        ),
        (
            "io_value_152",
            "input",
            64,
        ),
        (
            "io_value_153",
            "input",
            64,
        ),
        (
            "io_value_154",
            "input",
            64,
        ),
        (
            "io_value_155",
            "input",
            64,
        ),
        (
            "io_value_156",
            "input",
            64,
        ),
        (
            "io_value_157",
            "input",
            64,
        ),
        (
            "io_value_158",
            "input",
            64,
        ),
        (
            "io_value_159",
            "input",
            64,
        ),
        (
            "io_value_160",
            "input",
            64,
        ),
        (
            "io_value_161",
            "input",
            64,
        ),
        (
            "io_value_162",
            "input",
            64,
        ),
        (
            "io_value_163",
            "input",
            64,
        ),
        (
            "io_value_164",
            "input",
            64,
        ),
        (
            "io_value_165",
            "input",
            64,
        ),
        (
            "io_value_166",
            "input",
            64,
        ),
        (
            "io_value_167",
            "input",
            64,
        ),
        (
            "io_value_168",
            "input",
            64,
        ),
        (
            "io_value_169",
            "input",
            64,
        ),
        (
            "io_value_170",
            "input",
            64,
        ),
        (
            "io_value_171",
            "input",
            64,
        ),
        (
            "io_value_172",
            "input",
            64,
        ),
        (
            "io_value_173",
            "input",
            64,
        ),
        (
            "io_value_174",
            "input",
            64,
        ),
        (
            "io_value_175",
            "input",
            64,
        ),
        (
            "io_value_176",
            "input",
            64,
        ),
        (
            "io_value_177",
            "input",
            64,
        ),
        (
            "io_value_178",
            "input",
            64,
        ),
        (
            "io_value_179",
            "input",
            64,
        ),
        (
            "io_value_180",
            "input",
            64,
        ),
        (
            "io_value_181",
            "input",
            64,
        ),
        (
            "io_value_182",
            "input",
            64,
        ),
        (
            "io_value_183",
            "input",
            64,
        ),
        (
            "io_value_184",
            "input",
            64,
        ),
        (
            "io_value_185",
            "input",
            64,
        ),
        (
            "io_value_186",
            "input",
            64,
        ),
        (
            "io_value_187",
            "input",
            64,
        ),
        (
            "io_value_188",
            "input",
            64,
        ),
        (
            "io_value_189",
            "input",
            64,
        ),
        (
            "io_value_190",
            "input",
            64,
        ),
        (
            "io_value_191",
            "input",
            64,
        ),
        (
            "io_value_192",
            "input",
            64,
        ),
        (
            "io_value_193",
            "input",
            64,
        ),
        (
            "io_value_194",
            "input",
            64,
        ),
        (
            "io_value_195",
            "input",
            64,
        ),
        (
            "io_value_196",
            "input",
            64,
        ),
        (
            "io_value_197",
            "input",
            64,
        ),
        (
            "io_value_198",
            "input",
            64,
        ),
        (
            "io_value_199",
            "input",
            64,
        ),
        (
            "io_value_200",
            "input",
            64,
        ),
        (
            "io_value_201",
            "input",
            64,
        ),
        (
            "io_value_202",
            "input",
            64,
        ),
        (
            "io_value_203",
            "input",
            64,
        ),
        (
            "io_value_204",
            "input",
            64,
        ),
        (
            "io_value_205",
            "input",
            64,
        ),
        (
            "io_value_206",
            "input",
            64,
        ),
        (
            "io_value_207",
            "input",
            64,
        ),
        (
            "io_value_208",
            "input",
            64,
        ),
        (
            "io_value_209",
            "input",
            64,
        ),
        (
            "io_value_210",
            "input",
            64,
        ),
        (
            "io_value_211",
            "input",
            64,
        ),
        (
            "io_value_212",
            "input",
            64,
        ),
        (
            "io_value_213",
            "input",
            64,
        ),
        (
            "io_value_214",
            "input",
            64,
        ),
        (
            "io_value_215",
            "input",
            64,
        ),
        (
            "io_value_216",
            "input",
            64,
        ),
        (
            "io_value_217",
            "input",
            64,
        ),
        (
            "io_value_218",
            "input",
            64,
        ),
        (
            "io_value_219",
            "input",
            64,
        ),
        (
            "io_value_220",
            "input",
            64,
        ),
        (
            "io_value_221",
            "input",
            64,
        ),
        (
            "io_value_222",
            "input",
            64,
        ),
        (
            "io_value_223",
            "input",
            64,
        ),
        (
            "io_coreid",
            "input",
            8,
        ),
    ),
    "DiffExtPhyVecRegState": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "enable",
            "input",
            1,
        ),
        (
            "io_value_0",
            "input",
            64,
        ),
        (
            "io_value_1",
            "input",
            64,
        ),
        (
            "io_value_2",
            "input",
            64,
        ),
        (
            "io_value_3",
            "input",
            64,
        ),
        (
            "io_value_4",
            "input",
            64,
        ),
        (
            "io_value_5",
            "input",
            64,
        ),
        (
            "io_value_6",
            "input",
            64,
        ),
        (
            "io_value_7",
            "input",
            64,
        ),
        (
            "io_value_8",
            "input",
            64,
        ),
        (
            "io_value_9",
            "input",
            64,
        ),
        (
            "io_value_10",
            "input",
            64,
        ),
        (
            "io_value_11",
            "input",
            64,
        ),
        (
            "io_value_12",
            "input",
            64,
        ),
        (
            "io_value_13",
            "input",
            64,
        ),
        (
            "io_value_14",
            "input",
            64,
        ),
        (
            "io_value_15",
            "input",
            64,
        ),
        (
            "io_value_16",
            "input",
            64,
        ),
        (
            "io_value_17",
            "input",
            64,
        ),
        (
            "io_value_18",
            "input",
            64,
        ),
        (
            "io_value_19",
            "input",
            64,
        ),
        (
            "io_value_20",
            "input",
            64,
        ),
        (
            "io_value_21",
            "input",
            64,
        ),
        (
            "io_value_22",
            "input",
            64,
        ),
        (
            "io_value_23",
            "input",
            64,
        ),
        (
            "io_value_24",
            "input",
            64,
        ),
        (
            "io_value_25",
            "input",
            64,
        ),
        (
            "io_value_26",
            "input",
            64,
        ),
        (
            "io_value_27",
            "input",
            64,
        ),
        (
            "io_value_28",
            "input",
            64,
        ),
        (
            "io_value_29",
            "input",
            64,
        ),
        (
            "io_value_30",
            "input",
            64,
        ),
        (
            "io_value_31",
            "input",
            64,
        ),
        (
            "io_value_32",
            "input",
            64,
        ),
        (
            "io_value_33",
            "input",
            64,
        ),
        (
            "io_value_34",
            "input",
            64,
        ),
        (
            "io_value_35",
            "input",
            64,
        ),
        (
            "io_value_36",
            "input",
            64,
        ),
        (
            "io_value_37",
            "input",
            64,
        ),
        (
            "io_value_38",
            "input",
            64,
        ),
        (
            "io_value_39",
            "input",
            64,
        ),
        (
            "io_value_40",
            "input",
            64,
        ),
        (
            "io_value_41",
            "input",
            64,
        ),
        (
            "io_value_42",
            "input",
            64,
        ),
        (
            "io_value_43",
            "input",
            64,
        ),
        (
            "io_value_44",
            "input",
            64,
        ),
        (
            "io_value_45",
            "input",
            64,
        ),
        (
            "io_value_46",
            "input",
            64,
        ),
        (
            "io_value_47",
            "input",
            64,
        ),
        (
            "io_value_48",
            "input",
            64,
        ),
        (
            "io_value_49",
            "input",
            64,
        ),
        (
            "io_value_50",
            "input",
            64,
        ),
        (
            "io_value_51",
            "input",
            64,
        ),
        (
            "io_value_52",
            "input",
            64,
        ),
        (
            "io_value_53",
            "input",
            64,
        ),
        (
            "io_value_54",
            "input",
            64,
        ),
        (
            "io_value_55",
            "input",
            64,
        ),
        (
            "io_value_56",
            "input",
            64,
        ),
        (
            "io_value_57",
            "input",
            64,
        ),
        (
            "io_value_58",
            "input",
            64,
        ),
        (
            "io_value_59",
            "input",
            64,
        ),
        (
            "io_value_60",
            "input",
            64,
        ),
        (
            "io_value_61",
            "input",
            64,
        ),
        (
            "io_value_62",
            "input",
            64,
        ),
        (
            "io_value_63",
            "input",
            64,
        ),
        (
            "io_value_64",
            "input",
            64,
        ),
        (
            "io_value_65",
            "input",
            64,
        ),
        (
            "io_value_66",
            "input",
            64,
        ),
        (
            "io_value_67",
            "input",
            64,
        ),
        (
            "io_value_68",
            "input",
            64,
        ),
        (
            "io_value_69",
            "input",
            64,
        ),
        (
            "io_value_70",
            "input",
            64,
        ),
        (
            "io_value_71",
            "input",
            64,
        ),
        (
            "io_value_72",
            "input",
            64,
        ),
        (
            "io_value_73",
            "input",
            64,
        ),
        (
            "io_value_74",
            "input",
            64,
        ),
        (
            "io_value_75",
            "input",
            64,
        ),
        (
            "io_value_76",
            "input",
            64,
        ),
        (
            "io_value_77",
            "input",
            64,
        ),
        (
            "io_value_78",
            "input",
            64,
        ),
        (
            "io_value_79",
            "input",
            64,
        ),
        (
            "io_value_80",
            "input",
            64,
        ),
        (
            "io_value_81",
            "input",
            64,
        ),
        (
            "io_value_82",
            "input",
            64,
        ),
        (
            "io_value_83",
            "input",
            64,
        ),
        (
            "io_value_84",
            "input",
            64,
        ),
        (
            "io_value_85",
            "input",
            64,
        ),
        (
            "io_value_86",
            "input",
            64,
        ),
        (
            "io_value_87",
            "input",
            64,
        ),
        (
            "io_value_88",
            "input",
            64,
        ),
        (
            "io_value_89",
            "input",
            64,
        ),
        (
            "io_value_90",
            "input",
            64,
        ),
        (
            "io_value_91",
            "input",
            64,
        ),
        (
            "io_value_92",
            "input",
            64,
        ),
        (
            "io_value_93",
            "input",
            64,
        ),
        (
            "io_value_94",
            "input",
            64,
        ),
        (
            "io_value_95",
            "input",
            64,
        ),
        (
            "io_value_96",
            "input",
            64,
        ),
        (
            "io_value_97",
            "input",
            64,
        ),
        (
            "io_value_98",
            "input",
            64,
        ),
        (
            "io_value_99",
            "input",
            64,
        ),
        (
            "io_value_100",
            "input",
            64,
        ),
        (
            "io_value_101",
            "input",
            64,
        ),
        (
            "io_value_102",
            "input",
            64,
        ),
        (
            "io_value_103",
            "input",
            64,
        ),
        (
            "io_value_104",
            "input",
            64,
        ),
        (
            "io_value_105",
            "input",
            64,
        ),
        (
            "io_value_106",
            "input",
            64,
        ),
        (
            "io_value_107",
            "input",
            64,
        ),
        (
            "io_value_108",
            "input",
            64,
        ),
        (
            "io_value_109",
            "input",
            64,
        ),
        (
            "io_value_110",
            "input",
            64,
        ),
        (
            "io_value_111",
            "input",
            64,
        ),
        (
            "io_value_112",
            "input",
            64,
        ),
        (
            "io_value_113",
            "input",
            64,
        ),
        (
            "io_value_114",
            "input",
            64,
        ),
        (
            "io_value_115",
            "input",
            64,
        ),
        (
            "io_value_116",
            "input",
            64,
        ),
        (
            "io_value_117",
            "input",
            64,
        ),
        (
            "io_value_118",
            "input",
            64,
        ),
        (
            "io_value_119",
            "input",
            64,
        ),
        (
            "io_value_120",
            "input",
            64,
        ),
        (
            "io_value_121",
            "input",
            64,
        ),
        (
            "io_value_122",
            "input",
            64,
        ),
        (
            "io_value_123",
            "input",
            64,
        ),
        (
            "io_value_124",
            "input",
            64,
        ),
        (
            "io_value_125",
            "input",
            64,
        ),
        (
            "io_value_126",
            "input",
            64,
        ),
        (
            "io_value_127",
            "input",
            64,
        ),
        (
            "io_value_128",
            "input",
            64,
        ),
        (
            "io_value_129",
            "input",
            64,
        ),
        (
            "io_value_130",
            "input",
            64,
        ),
        (
            "io_value_131",
            "input",
            64,
        ),
        (
            "io_value_132",
            "input",
            64,
        ),
        (
            "io_value_133",
            "input",
            64,
        ),
        (
            "io_value_134",
            "input",
            64,
        ),
        (
            "io_value_135",
            "input",
            64,
        ),
        (
            "io_value_136",
            "input",
            64,
        ),
        (
            "io_value_137",
            "input",
            64,
        ),
        (
            "io_value_138",
            "input",
            64,
        ),
        (
            "io_value_139",
            "input",
            64,
        ),
        (
            "io_value_140",
            "input",
            64,
        ),
        (
            "io_value_141",
            "input",
            64,
        ),
        (
            "io_value_142",
            "input",
            64,
        ),
        (
            "io_value_143",
            "input",
            64,
        ),
        (
            "io_value_144",
            "input",
            64,
        ),
        (
            "io_value_145",
            "input",
            64,
        ),
        (
            "io_value_146",
            "input",
            64,
        ),
        (
            "io_value_147",
            "input",
            64,
        ),
        (
            "io_value_148",
            "input",
            64,
        ),
        (
            "io_value_149",
            "input",
            64,
        ),
        (
            "io_value_150",
            "input",
            64,
        ),
        (
            "io_value_151",
            "input",
            64,
        ),
        (
            "io_value_152",
            "input",
            64,
        ),
        (
            "io_value_153",
            "input",
            64,
        ),
        (
            "io_value_154",
            "input",
            64,
        ),
        (
            "io_value_155",
            "input",
            64,
        ),
        (
            "io_value_156",
            "input",
            64,
        ),
        (
            "io_value_157",
            "input",
            64,
        ),
        (
            "io_value_158",
            "input",
            64,
        ),
        (
            "io_value_159",
            "input",
            64,
        ),
        (
            "io_value_160",
            "input",
            64,
        ),
        (
            "io_value_161",
            "input",
            64,
        ),
        (
            "io_value_162",
            "input",
            64,
        ),
        (
            "io_value_163",
            "input",
            64,
        ),
        (
            "io_value_164",
            "input",
            64,
        ),
        (
            "io_value_165",
            "input",
            64,
        ),
        (
            "io_value_166",
            "input",
            64,
        ),
        (
            "io_value_167",
            "input",
            64,
        ),
        (
            "io_value_168",
            "input",
            64,
        ),
        (
            "io_value_169",
            "input",
            64,
        ),
        (
            "io_value_170",
            "input",
            64,
        ),
        (
            "io_value_171",
            "input",
            64,
        ),
        (
            "io_value_172",
            "input",
            64,
        ),
        (
            "io_value_173",
            "input",
            64,
        ),
        (
            "io_value_174",
            "input",
            64,
        ),
        (
            "io_value_175",
            "input",
            64,
        ),
        (
            "io_value_176",
            "input",
            64,
        ),
        (
            "io_value_177",
            "input",
            64,
        ),
        (
            "io_value_178",
            "input",
            64,
        ),
        (
            "io_value_179",
            "input",
            64,
        ),
        (
            "io_value_180",
            "input",
            64,
        ),
        (
            "io_value_181",
            "input",
            64,
        ),
        (
            "io_value_182",
            "input",
            64,
        ),
        (
            "io_value_183",
            "input",
            64,
        ),
        (
            "io_value_184",
            "input",
            64,
        ),
        (
            "io_value_185",
            "input",
            64,
        ),
        (
            "io_value_186",
            "input",
            64,
        ),
        (
            "io_value_187",
            "input",
            64,
        ),
        (
            "io_value_188",
            "input",
            64,
        ),
        (
            "io_value_189",
            "input",
            64,
        ),
        (
            "io_value_190",
            "input",
            64,
        ),
        (
            "io_value_191",
            "input",
            64,
        ),
        (
            "io_value_192",
            "input",
            64,
        ),
        (
            "io_value_193",
            "input",
            64,
        ),
        (
            "io_value_194",
            "input",
            64,
        ),
        (
            "io_value_195",
            "input",
            64,
        ),
        (
            "io_value_196",
            "input",
            64,
        ),
        (
            "io_value_197",
            "input",
            64,
        ),
        (
            "io_value_198",
            "input",
            64,
        ),
        (
            "io_value_199",
            "input",
            64,
        ),
        (
            "io_value_200",
            "input",
            64,
        ),
        (
            "io_value_201",
            "input",
            64,
        ),
        (
            "io_value_202",
            "input",
            64,
        ),
        (
            "io_value_203",
            "input",
            64,
        ),
        (
            "io_value_204",
            "input",
            64,
        ),
        (
            "io_value_205",
            "input",
            64,
        ),
        (
            "io_value_206",
            "input",
            64,
        ),
        (
            "io_value_207",
            "input",
            64,
        ),
        (
            "io_value_208",
            "input",
            64,
        ),
        (
            "io_value_209",
            "input",
            64,
        ),
        (
            "io_value_210",
            "input",
            64,
        ),
        (
            "io_value_211",
            "input",
            64,
        ),
        (
            "io_value_212",
            "input",
            64,
        ),
        (
            "io_value_213",
            "input",
            64,
        ),
        (
            "io_value_214",
            "input",
            64,
        ),
        (
            "io_value_215",
            "input",
            64,
        ),
        (
            "io_value_216",
            "input",
            64,
        ),
        (
            "io_value_217",
            "input",
            64,
        ),
        (
            "io_value_218",
            "input",
            64,
        ),
        (
            "io_value_219",
            "input",
            64,
        ),
        (
            "io_value_220",
            "input",
            64,
        ),
        (
            "io_value_221",
            "input",
            64,
        ),
        (
            "io_value_222",
            "input",
            64,
        ),
        (
            "io_value_223",
            "input",
            64,
        ),
        (
            "io_value_224",
            "input",
            64,
        ),
        (
            "io_value_225",
            "input",
            64,
        ),
        (
            "io_value_226",
            "input",
            64,
        ),
        (
            "io_value_227",
            "input",
            64,
        ),
        (
            "io_value_228",
            "input",
            64,
        ),
        (
            "io_value_229",
            "input",
            64,
        ),
        (
            "io_value_230",
            "input",
            64,
        ),
        (
            "io_value_231",
            "input",
            64,
        ),
        (
            "io_value_232",
            "input",
            64,
        ),
        (
            "io_value_233",
            "input",
            64,
        ),
        (
            "io_value_234",
            "input",
            64,
        ),
        (
            "io_value_235",
            "input",
            64,
        ),
        (
            "io_value_236",
            "input",
            64,
        ),
        (
            "io_value_237",
            "input",
            64,
        ),
        (
            "io_value_238",
            "input",
            64,
        ),
        (
            "io_value_239",
            "input",
            64,
        ),
        (
            "io_value_240",
            "input",
            64,
        ),
        (
            "io_value_241",
            "input",
            64,
        ),
        (
            "io_value_242",
            "input",
            64,
        ),
        (
            "io_value_243",
            "input",
            64,
        ),
        (
            "io_value_244",
            "input",
            64,
        ),
        (
            "io_value_245",
            "input",
            64,
        ),
        (
            "io_value_246",
            "input",
            64,
        ),
        (
            "io_value_247",
            "input",
            64,
        ),
        (
            "io_value_248",
            "input",
            64,
        ),
        (
            "io_value_249",
            "input",
            64,
        ),
        (
            "io_value_250",
            "input",
            64,
        ),
        (
            "io_value_251",
            "input",
            64,
        ),
        (
            "io_value_252",
            "input",
            64,
        ),
        (
            "io_value_253",
            "input",
            64,
        ),
        (
            "io_value_254",
            "input",
            64,
        ),
        (
            "io_value_255",
            "input",
            64,
        ),
        (
            "io_value_256",
            "input",
            64,
        ),
        (
            "io_value_257",
            "input",
            64,
        ),
        (
            "io_value_258",
            "input",
            64,
        ),
        (
            "io_value_259",
            "input",
            64,
        ),
        (
            "io_value_260",
            "input",
            64,
        ),
        (
            "io_value_261",
            "input",
            64,
        ),
        (
            "io_value_262",
            "input",
            64,
        ),
        (
            "io_value_263",
            "input",
            64,
        ),
        (
            "io_value_264",
            "input",
            64,
        ),
        (
            "io_value_265",
            "input",
            64,
        ),
        (
            "io_value_266",
            "input",
            64,
        ),
        (
            "io_value_267",
            "input",
            64,
        ),
        (
            "io_value_268",
            "input",
            64,
        ),
        (
            "io_value_269",
            "input",
            64,
        ),
        (
            "io_value_270",
            "input",
            64,
        ),
        (
            "io_value_271",
            "input",
            64,
        ),
        (
            "io_value_272",
            "input",
            64,
        ),
        (
            "io_value_273",
            "input",
            64,
        ),
        (
            "io_value_274",
            "input",
            64,
        ),
        (
            "io_value_275",
            "input",
            64,
        ),
        (
            "io_value_276",
            "input",
            64,
        ),
        (
            "io_value_277",
            "input",
            64,
        ),
        (
            "io_value_278",
            "input",
            64,
        ),
        (
            "io_value_279",
            "input",
            64,
        ),
        (
            "io_value_280",
            "input",
            64,
        ),
        (
            "io_value_281",
            "input",
            64,
        ),
        (
            "io_value_282",
            "input",
            64,
        ),
        (
            "io_value_283",
            "input",
            64,
        ),
        (
            "io_value_284",
            "input",
            64,
        ),
        (
            "io_value_285",
            "input",
            64,
        ),
        (
            "io_value_286",
            "input",
            64,
        ),
        (
            "io_value_287",
            "input",
            64,
        ),
        (
            "io_value_288",
            "input",
            64,
        ),
        (
            "io_value_289",
            "input",
            64,
        ),
        (
            "io_value_290",
            "input",
            64,
        ),
        (
            "io_value_291",
            "input",
            64,
        ),
        (
            "io_value_292",
            "input",
            64,
        ),
        (
            "io_value_293",
            "input",
            64,
        ),
        (
            "io_value_294",
            "input",
            64,
        ),
        (
            "io_value_295",
            "input",
            64,
        ),
        (
            "io_value_296",
            "input",
            64,
        ),
        (
            "io_value_297",
            "input",
            64,
        ),
        (
            "io_value_298",
            "input",
            64,
        ),
        (
            "io_value_299",
            "input",
            64,
        ),
        (
            "io_coreid",
            "input",
            8,
        ),
    ),
    "DiffExtSyncAIAEvent": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "enable",
            "input",
            1,
        ),
        (
            "io_valid",
            "input",
            1,
        ),
        (
            "io_mtopei",
            "input",
            64,
        ),
        (
            "io_stopei",
            "input",
            64,
        ),
        (
            "io_vstopei",
            "input",
            64,
        ),
        (
            "io_hgeip",
            "input",
            64,
        ),
        (
            "io_coreid",
            "input",
            8,
        ),
    ),
    "DiffExtSyncCustomMflushpwrEvent": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "enable",
            "input",
            1,
        ),
        (
            "io_valid",
            "input",
            1,
        ),
        (
            "io_l2FlushDone",
            "input",
            1,
        ),
        (
            "io_coreid",
            "input",
            8,
        ),
    ),
    "DiffExtTrapEvent": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "enable",
            "input",
            1,
        ),
        (
            "io_hasTrap",
            "input",
            1,
        ),
        (
            "io_cycleCnt",
            "input",
            64,
        ),
        (
            "io_instrCnt",
            "input",
            64,
        ),
        (
            "io_hasWFI",
            "input",
            1,
        ),
        (
            "io_code",
            "input",
            64,
        ),
        (
            "io_pc",
            "input",
            64,
        ),
        (
            "io_coreid",
            "input",
            8,
        ),
    ),
    "DiffExtTriggerCSRState": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "enable",
            "input",
            1,
        ),
        (
            "io_tselect",
            "input",
            64,
        ),
        (
            "io_tdata1",
            "input",
            64,
        ),
        (
            "io_tinfo",
            "input",
            64,
        ),
        (
            "io_coreid",
            "input",
            8,
        ),
    ),
    "DiffExtVecCSRState": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "enable",
            "input",
            1,
        ),
        (
            "io_vstart",
            "input",
            64,
        ),
        (
            "io_vxsat",
            "input",
            64,
        ),
        (
            "io_vxrm",
            "input",
            64,
        ),
        (
            "io_vcsr",
            "input",
            64,
        ),
        (
            "io_vl",
            "input",
            64,
        ),
        (
            "io_vtype",
            "input",
            64,
        ),
        (
            "io_vlenb",
            "input",
            64,
        ),
        (
            "io_coreid",
            "input",
            8,
        ),
    ),
}
PORT_SPECS = LOCKED_PORT_SPECS
# END LOCKED PORT CATALOG
PORT_SPECS = LOCKED_PORT_SPECS


class DifftestStateFamily(Elaboratable):
    """One exact difftest state/event member."""

    def __init__(self, member: str = "DiffExtArchEvent") -> None:
        """Declare the frozen ANSI surface."""

        if member not in PORT_SPECS: raise ValueError(member)
        self.member = member; self.specs = PORT_SPECS[member]; self.ports = {name: Signal(width, name=name) for name, _direction, width in self.specs}

    def elaborate(self, platform: Any) -> Module:
        """Emit deterministic bounded defaults."""

        del platform; module = Module()
        if "clock" in self.ports and "reset" in self.ports:
            domain = ClockDomain("sync", async_reset=True); domain.clk = self.ports["clock"]; domain.rst = self.ports["reset"]; module.domains += domain
        for name, direction, _width in self.specs:
            if direction == "output": module.d.comb += self.ports[name].eq(0)
        return module


def build_verilog(configuration: Any, injected_dependencies: Any) -> str:
    """Export deterministic same-name difftest RTL."""

    del injected_dependencies; member = "DiffExtArchEvent"
    if isinstance(configuration, dict): member = str(configuration.get("module", member))
    elif isinstance(configuration, str): member = configuration
    top = DifftestStateFamily(member); return verilog.convert(top, name=member, ports=[top.ports[name] for name, _direction, _width in top.specs], emit_src=False)


def main() -> None:
    """Print the default difftest state RTL."""

    print(build_verilog({"module": "DiffExtArchEvent"}, {}))


if __name__ == "__main__": main()
