"""UHSC V2 debug-trigger family aggregate.
昆明湖 V2 调试触发器 family 聚合。

The locked V2 hierarchy emits Debug, MemTrigger, MemTrigger_3, and
VSegmentTrigger from the NewCSR debug source.  Exact ANSI ports are frozen in
an explicit catalog; bounded trigger predicates are implemented without
claiming the complete NewCSR parent closure.
"""

from __future__ import annotations

from typing import Any, cast

from amaranth import ClockDomain, Elaboratable, Module, Mux, Signal
from amaranth.back import verilog


# =============================================================================
# Module Contract
# =============================================================================
__all__ = ["COVERED_MODULES", "DebugFamily", "build_verilog", "main"]
COVERED_MODULES = ("Debug", "MemTrigger", "MemTrigger_3", "VSegmentTrigger")
SOURCE_PATHS = ("upstream/src/main/scala/xiangshan/backend/fu/NewCSR/Debug.scala",)

# BEGIN LOCKED PORT CATALOG
LOCKED_PORT_SPECS: dict[str, tuple[tuple[str, str, int], ...]] = {
    "Debug": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "io_in_trapInfo_valid",
            "input",
            1,
        ),
        (
            "io_in_trapInfo_bits_trapVec",
            "input",
            64,
        ),
        (
            "io_in_trapInfo_bits_isDebugIntr",
            "input",
            1,
        ),
        (
            "io_in_trapInfo_bits_isInterrupt",
            "input",
            1,
        ),
        (
            "io_in_trapInfo_bits_singleStep",
            "input",
            1,
        ),
        (
            "io_in_trapInfo_bits_trigger",
            "input",
            4,
        ),
        (
            "io_in_trapInfo_bits_criticalErrorState",
            "input",
            1,
        ),
        (
            "io_in_privState_PRVM",
            "input",
            2,
        ),
        (
            "io_in_privState_V",
            "input",
            1,
        ),
        (
            "io_in_debugMode",
            "input",
            1,
        ),
        (
            "io_in_dcsr_CETRIG",
            "input",
            1,
        ),
        (
            "io_in_dcsr_EBREAKVS",
            "input",
            1,
        ),
        (
            "io_in_dcsr_EBREAKVU",
            "input",
            1,
        ),
        (
            "io_in_dcsr_EBREAKM",
            "input",
            1,
        ),
        (
            "io_in_dcsr_EBREAKS",
            "input",
            1,
        ),
        (
            "io_in_dcsr_EBREAKU",
            "input",
            1,
        ),
        (
            "io_in_tselect_ALL",
            "input",
            2,
        ),
        (
            "io_in_tdata1Selected_DATA",
            "input",
            59,
        ),
        (
            "io_in_tdata2Selected_ALL",
            "input",
            64,
        ),
        (
            "io_in_tdata1Vec_0_TYPE",
            "input",
            4,
        ),
        (
            "io_in_tdata1Vec_0_DATA",
            "input",
            59,
        ),
        (
            "io_in_tdata1Vec_1_TYPE",
            "input",
            4,
        ),
        (
            "io_in_tdata1Vec_1_DATA",
            "input",
            59,
        ),
        (
            "io_in_tdata1Vec_2_TYPE",
            "input",
            4,
        ),
        (
            "io_in_tdata1Vec_2_DATA",
            "input",
            59,
        ),
        (
            "io_in_tdata1Vec_3_TYPE",
            "input",
            4,
        ),
        (
            "io_in_tdata1Vec_3_DATA",
            "input",
            59,
        ),
        (
            "io_in_triggerCanRaiseBpExp",
            "input",
            1,
        ),
        (
            "io_in_tdata1Update",
            "input",
            1,
        ),
        (
            "io_in_tdata2Update",
            "input",
            1,
        ),
        (
            "io_in_tdata1Wdata_TYPE",
            "input",
            4,
        ),
        (
            "io_in_tdata1Wdata_DATA",
            "input",
            59,
        ),
        (
            "io_out_triggerFrontendChange",
            "output",
            1,
        ),
        (
            "io_out_newTriggerChainIsLegal",
            "output",
            1,
        ),
        (
            "io_out_memTrigger_tUpdate_valid",
            "output",
            1,
        ),
        (
            "io_out_memTrigger_tUpdate_bits_addr",
            "output",
            2,
        ),
        (
            "io_out_memTrigger_tUpdate_bits_tdata_matchType",
            "output",
            2,
        ),
        (
            "io_out_memTrigger_tUpdate_bits_tdata_select",
            "output",
            1,
        ),
        (
            "io_out_memTrigger_tUpdate_bits_tdata_action",
            "output",
            4,
        ),
        (
            "io_out_memTrigger_tUpdate_bits_tdata_chain",
            "output",
            1,
        ),
        (
            "io_out_memTrigger_tUpdate_bits_tdata_store",
            "output",
            1,
        ),
        (
            "io_out_memTrigger_tUpdate_bits_tdata_load",
            "output",
            1,
        ),
        (
            "io_out_memTrigger_tUpdate_bits_tdata_tdata2",
            "output",
            64,
        ),
        (
            "io_out_memTrigger_tEnableVec_0",
            "output",
            1,
        ),
        (
            "io_out_memTrigger_tEnableVec_1",
            "output",
            1,
        ),
        (
            "io_out_memTrigger_tEnableVec_2",
            "output",
            1,
        ),
        (
            "io_out_memTrigger_tEnableVec_3",
            "output",
            1,
        ),
        (
            "io_out_memTrigger_debugMode",
            "output",
            1,
        ),
        (
            "io_out_memTrigger_triggerCanRaiseBpExp",
            "output",
            1,
        ),
        (
            "io_out_frontendTrigger_tUpdate_valid",
            "output",
            1,
        ),
        (
            "io_out_frontendTrigger_tUpdate_bits_addr",
            "output",
            2,
        ),
        (
            "io_out_frontendTrigger_tUpdate_bits_tdata_matchType",
            "output",
            2,
        ),
        (
            "io_out_frontendTrigger_tUpdate_bits_tdata_select",
            "output",
            1,
        ),
        (
            "io_out_frontendTrigger_tUpdate_bits_tdata_action",
            "output",
            4,
        ),
        (
            "io_out_frontendTrigger_tUpdate_bits_tdata_chain",
            "output",
            1,
        ),
        (
            "io_out_frontendTrigger_tUpdate_bits_tdata_tdata2",
            "output",
            64,
        ),
        (
            "io_out_frontendTrigger_tEnableVec_0",
            "output",
            1,
        ),
        (
            "io_out_frontendTrigger_tEnableVec_1",
            "output",
            1,
        ),
        (
            "io_out_frontendTrigger_tEnableVec_2",
            "output",
            1,
        ),
        (
            "io_out_frontendTrigger_tEnableVec_3",
            "output",
            1,
        ),
        (
            "io_out_frontendTrigger_debugMode",
            "output",
            1,
        ),
        (
            "io_out_frontendTrigger_triggerCanRaiseBpExp",
            "output",
            1,
        ),
        (
            "io_out_hasDebugTrap",
            "output",
            1,
        ),
        (
            "io_out_hasDebugIntr",
            "output",
            1,
        ),
        (
            "io_out_hasSingleStep",
            "output",
            1,
        ),
        (
            "io_out_triggerEnterDebugMode",
            "output",
            1,
        ),
        (
            "io_out_hasDebugEbreakException",
            "output",
            1,
        ),
        (
            "io_out_breakPoint",
            "output",
            1,
        ),
        (
            "io_out_criticalErrorStateEnterDebug",
            "output",
            1,
        ),
    ),
    "MemTrigger": (
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_0_matchType",
            "input",
            2,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_0_select",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_0_timing",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_0_action",
            "input",
            4,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_0_chain",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_0_load",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_0_tdata2",
            "input",
            64,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_1_matchType",
            "input",
            2,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_1_select",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_1_timing",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_1_action",
            "input",
            4,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_1_chain",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_1_load",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_1_tdata2",
            "input",
            64,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_2_matchType",
            "input",
            2,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_2_select",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_2_timing",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_2_action",
            "input",
            4,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_2_chain",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_2_load",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_2_tdata2",
            "input",
            64,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_3_matchType",
            "input",
            2,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_3_select",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_3_timing",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_3_action",
            "input",
            4,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_3_chain",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_3_load",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_3_tdata2",
            "input",
            64,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tEnableVec_0",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tEnableVec_1",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tEnableVec_2",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tEnableVec_3",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_debugMode",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_triggerCanRaiseBpExp",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromLoadStore_vaddr",
            "input",
            50,
        ),
        (
            "tdataVec_io_fromLoadStore_isVectorUnitStride",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromLoadStore_mask",
            "input",
            16,
        ),
        (
            "tdataVec_io_toLoadStore_triggerAction",
            "output",
            4,
        ),
        (
            "tdataVec_io_toLoadStore_triggerVaddr",
            "output",
            50,
        ),
        (
            "tdataVec_io_toLoadStore_triggerMask",
            "output",
            16,
        ),
        (
            "tdataVec_io_isPrf",
            "input",
            1,
        ),
    ),
    "MemTrigger_3": (
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_0_matchType",
            "input",
            2,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_0_select",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_0_timing",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_0_action",
            "input",
            4,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_0_chain",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_0_store",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_0_tdata2",
            "input",
            64,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_1_matchType",
            "input",
            2,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_1_select",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_1_timing",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_1_action",
            "input",
            4,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_1_chain",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_1_store",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_1_tdata2",
            "input",
            64,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_2_matchType",
            "input",
            2,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_2_select",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_2_timing",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_2_action",
            "input",
            4,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_2_chain",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_2_store",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_2_tdata2",
            "input",
            64,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_3_matchType",
            "input",
            2,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_3_select",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_3_timing",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_3_action",
            "input",
            4,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_3_chain",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_3_store",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_3_tdata2",
            "input",
            64,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tEnableVec_0",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tEnableVec_1",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tEnableVec_2",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tEnableVec_3",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_debugMode",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_triggerCanRaiseBpExp",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromLoadStore_vaddr",
            "input",
            50,
        ),
        (
            "tdataVec_io_fromLoadStore_isVectorUnitStride",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromLoadStore_mask",
            "input",
            16,
        ),
        (
            "tdataVec_io_toLoadStore_triggerAction",
            "output",
            4,
        ),
        (
            "tdataVec_io_toLoadStore_triggerVaddr",
            "output",
            50,
        ),
        (
            "tdataVec_io_isCbo",
            "input",
            1,
        ),
    ),
    "VSegmentTrigger": (
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_0_matchType",
            "input",
            2,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_0_select",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_0_timing",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_0_action",
            "input",
            4,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_0_chain",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_0_store",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_0_load",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_0_tdata2",
            "input",
            64,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_1_matchType",
            "input",
            2,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_1_select",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_1_timing",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_1_action",
            "input",
            4,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_1_chain",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_1_store",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_1_load",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_1_tdata2",
            "input",
            64,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_2_matchType",
            "input",
            2,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_2_select",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_2_timing",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_2_action",
            "input",
            4,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_2_chain",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_2_store",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_2_load",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_2_tdata2",
            "input",
            64,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_3_matchType",
            "input",
            2,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_3_select",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_3_timing",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_3_action",
            "input",
            4,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_3_chain",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_3_store",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_3_load",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tdataVec_3_tdata2",
            "input",
            64,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tEnableVec_0",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tEnableVec_1",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tEnableVec_2",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_tEnableVec_3",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_debugMode",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromCsrTrigger_triggerCanRaiseBpExp",
            "input",
            1,
        ),
        (
            "tdataVec_io_fromLoadStore_vaddr",
            "input",
            50,
        ),
        (
            "tdataVec_io_toLoadStore_triggerAction",
            "output",
            4,
        ),
        (
            "tdataVec_io_memType",
            "input",
            1,
        ),
    ),
}
PORT_SPECS = LOCKED_PORT_SPECS
# END LOCKED PORT CATALOG
PORT_SPECS = LOCKED_PORT_SPECS


# =============================================================================
# Implementation
# =============================================================================
class DebugFamily(Elaboratable):
    """One locked debug family member. / 一个锁定调试 family 成员。"""

    def __init__(self, member: str = "Debug") -> None:
        """Declare exact flattened ports. / 声明精确扁平端口。"""

        if member not in PORT_SPECS:
            raise ValueError(member)
        self.member = member
        self.specs = PORT_SPECS[member]
        self.ports = {name: Signal(width, name=name) for name, _direction, width in self.specs}

    def elaborate(self, platform: Any) -> Module:
        """Implement bounded debug entry and trigger defaults. / 实现有界调试进入和触发默认行为。"""

        del platform
        module = Module()
        if "clock" in self.ports and "reset" in self.ports:
            domain = ClockDomain("sync", async_reset=True); domain.clk = self.ports["clock"]; domain.rst = self.ports["reset"]; module.domains += domain
        for name, direction, _width in self.specs:
            if direction == "output":
                module.d.comb += self.ports[name].eq(0)
        if self.member == "Debug":
            intr = self.ports.get("io_in_trapInfo_bits_isDebugIntr")
            ebreak = self.ports.get("io_in_trapInfo_bits_trigger")
            if intr is not None and "io_out_hasDebugIntr" in self.ports:
                module.d.comb += self.ports["io_out_hasDebugIntr"].eq(intr)
            if ebreak is not None and "io_out_hasDebugTrap" in self.ports:
                module.d.comb += self.ports["io_out_hasDebugTrap"].eq(ebreak != 0)
            if "io_out_triggerEnterDebugMode" in self.ports:
                module.d.comb += self.ports["io_out_triggerEnterDebugMode"].eq(
                    cast(Any, self.ports.get("io_out_hasDebugIntr", Signal())) | cast(Any, self.ports.get("io_out_hasDebugTrap", Signal()))
                )
        else:
            # Trigger child surfaces forward the bounded load/store address and
            # selected action fields only when the source exposes them.
            address = self.ports.get("tdataVec_io_fromLoadStore_vaddr")
            target = self.ports.get("tdataVec_io_toLoadStore_triggerVaddr")
            if address is not None and target is not None:
                module.d.comb += target.eq(address)
            action = self.ports.get("tdataVec_io_fromCsrTrigger_tdataVec_0_action")
            out_action = self.ports.get("tdataVec_io_toLoadStore_triggerAction")
            if action is not None and out_action is not None:
                module.d.comb += out_action.eq(action)
        return module


# =============================================================================
# Public Adapter
# =============================================================================
def build_verilog(configuration: Any, injected_dependencies: Any) -> str:
    """Export one deterministic same-name debug member. / 导出确定性的同名调试成员。"""

    del injected_dependencies
    member = "Debug"
    if isinstance(configuration, dict): member = str(configuration.get("module", member))
    elif isinstance(configuration, str): member = configuration
    top = DebugFamily(member)
    return verilog.convert(top, name=member, ports=[top.ports[n] for n, _d, _w in top.specs], emit_src=False)


# =============================================================================
# Direct Entry
# =============================================================================
def main() -> None:
    """Print default Debug RTL. / 打印默认 Debug RTL。"""

    print(build_verilog({"module": "Debug"}, {}))


if __name__ == "__main__":
    main()
