"""UHSC V2 utility/protocol residual leaf family.

This source-grouped family replaces the broad residual compatibility subject
for arithmetic helpers, debug/JTAG, queues, clocks, LFSRs and vector plumbing.
Behavior beyond deterministic inactive defaults remains explicitly pending.
"""
from __future__ import annotations
from typing import Any
from amaranth import ClockDomain, Elaboratable, Module, Signal
from amaranth.back import verilog
COVERED_MODULES = ('CSA3to2', 'CSA3to2_20', 'CSA3to2_24', 'CSA4to2', 'CSA_Nto2With3to2MainPipeline', 'ClockGate', 'DebugTransportModuleJTAG', 'IDPool', 'JtagStateMachine', 'JtagTapController', 'MaxPeriodFibonacciLFSR', 'MaxPeriodFibonacciLFSR_3', 'OverrideableQueue', 'OverrideableQueue_1', 'TimeAsync', 'r4_qds_v2', 'r4_qds_v2_spec', 'skidBufferConnect', 'PrintCommitIDModule')
SOURCE_PATHS = ("upstream/rocket-chip/src/main/scala/util", "upstream/rocket-chip/src/main/scala/jtag", "upstream/src/main/scala/utils", "upstream/yunsuan/src/main/scala")
LOCKED_PORT_SPECS: dict[str, tuple[tuple[str, str, int], ...]] = {
    "CSA3to2": (
        ("io_in_a", "input", 107),
        ("io_in_b", "input", 107),
        ("io_in_c", "input", 107),
        ("io_out_sum", "output", 107),
        ("io_out_car", "output", 107),
    ),
    "CSA3to2_20": (
        ("io_in_a", "input", 200),
        ("io_in_b", "input", 200),
        ("io_in_c", "input", 200),
        ("io_out_sum", "output", 200),
        ("io_out_car", "output", 200),
    ),
    "CSA3to2_24": (
        ("io_in_a", "input", 72),
        ("io_in_b", "input", 72),
        ("io_in_c", "input", 72),
        ("io_out_sum", "output", 72),
        ("io_out_car", "output", 72),
    ),
    "CSA4to2": (
        ("io_in_a", "input", 107),
        ("io_in_b", "input", 107),
        ("io_in_c", "input", 107),
        ("io_in_d", "input", 107),
        ("io_out_sum", "output", 107),
        ("io_out_car", "output", 107),
    ),
    "CSA_Nto2With3to2MainPipeline": (
        ("clock", "input", 1),
        ("io_fire", "input", 1),
        ("io_in_0", "input", 107),
        ("io_in_1", "input", 107),
        ("io_in_2", "input", 107),
        ("io_in_3", "input", 107),
        ("io_in_4", "input", 107),
        ("io_in_5", "input", 107),
        ("io_in_6", "input", 107),
        ("io_in_7", "input", 107),
        ("io_in_8", "input", 107),
        ("io_in_9", "input", 107),
        ("io_in_10", "input", 107),
        ("io_in_11", "input", 107),
        ("io_in_12", "input", 107),
        ("io_in_13", "input", 107),
        ("io_in_14", "input", 107),
        ("io_in_15", "input", 107),
        ("io_in_16", "input", 107),
        ("io_in_17", "input", 107),
        ("io_in_18", "input", 107),
        ("io_in_19", "input", 107),
        ("io_in_20", "input", 107),
        ("io_in_21", "input", 107),
        ("io_in_22", "input", 107),
        ("io_in_23", "input", 107),
        ("io_in_24", "input", 107),
        ("io_in_25", "input", 107),
        ("io_in_26", "input", 107),
        ("io_out_sum", "output", 107),
        ("io_out_car", "output", 107),
    ),
    "ClockGate": (
    ),
    "DebugTransportModuleJTAG": (
        ("io_jtag_clock", "input", 1),
        ("io_jtag_reset", "input", 1),
        ("io_dmi_req_ready", "input", 1),
        ("io_dmi_req_valid", "output", 1),
        ("io_dmi_req_bits_addr", "output", 7),
        ("io_dmi_req_bits_data", "output", 32),
        ("io_dmi_req_bits_op", "output", 2),
        ("io_dmi_resp_ready", "output", 1),
        ("io_dmi_resp_valid", "input", 1),
        ("io_dmi_resp_bits_data", "input", 32),
        ("io_dmi_resp_bits_resp", "input", 2),
        ("io_jtag_TMS", "input", 1),
        ("io_jtag_TDI", "input", 1),
        ("io_jtag_TDO_data", "output", 1),
        ("io_jtag_TDO_driven", "output", 1),
        ("io_jtag_mfr_id", "input", 11),
        ("io_jtag_part_number", "input", 16),
        ("io_jtag_version", "input", 4),
    ),
    "IDPool": (
        ("clock", "input", 1),
        ("reset", "input", 1),
        ("io_free_valid", "input", 1),
        ("io_free_bits", "input", 3),
        ("io_alloc_ready", "input", 1),
        ("io_alloc_valid", "output", 1),
        ("io_alloc_bits", "output", 3),
    ),
    "JtagStateMachine": (
        ("clock", "input", 1),
        ("reset", "input", 1),
        ("io_tms", "input", 1),
        ("io_currState", "output", 4),
    ),
    "JtagTapController": (
        ("clock", "input", 1),
        ("reset", "input", 1),
        ("io_jtag_TMS", "input", 1),
        ("io_jtag_TDI", "input", 1),
        ("io_jtag_TDO_data", "output", 1),
        ("io_jtag_TDO_driven", "output", 1),
        ("io_control_jtag_reset", "input", 1),
        ("io_output_instruction", "output", 5),
        ("io_output_tapIsInTestLogicReset", "output", 1),
        ("io_dataChainOut_shift", "output", 1),
        ("io_dataChainOut_data", "output", 1),
        ("io_dataChainOut_capture", "output", 1),
        ("io_dataChainOut_update", "output", 1),
        ("io_dataChainIn_data", "input", 1),
    ),
    "MaxPeriodFibonacciLFSR": (
        ("clock", "input", 1),
        ("reset", "input", 1),
        ("io_out_0", "output", 1),
        ("io_out_1", "output", 1),
        ("io_out_2", "output", 1),
        ("io_out_3", "output", 1),
        ("io_out_4", "output", 1),
        ("io_out_5", "output", 1),
        ("io_out_6", "output", 1),
        ("io_out_7", "output", 1),
        ("io_out_8", "output", 1),
        ("io_out_9", "output", 1),
        ("io_out_10", "output", 1),
        ("io_out_11", "output", 1),
        ("io_out_12", "output", 1),
        ("io_out_13", "output", 1),
        ("io_out_14", "output", 1),
    ),
    "MaxPeriodFibonacciLFSR_3": (
        ("clock", "input", 1),
        ("reset", "input", 1),
        ("io_increment", "input", 1),
        ("io_out_0", "output", 1),
        ("io_out_1", "output", 1),
        ("io_out_2", "output", 1),
        ("io_out_3", "output", 1),
        ("io_out_4", "output", 1),
        ("io_out_5", "output", 1),
        ("io_out_6", "output", 1),
        ("io_out_7", "output", 1),
        ("io_out_8", "output", 1),
        ("io_out_9", "output", 1),
        ("io_out_10", "output", 1),
        ("io_out_11", "output", 1),
        ("io_out_12", "output", 1),
        ("io_out_13", "output", 1),
        ("io_out_14", "output", 1),
        ("io_out_15", "output", 1),
    ),
    "OverrideableQueue": (
        ("clock", "input", 1),
        ("reset", "input", 1),
        ("io_in_valid", "input", 1),
        ("io_in_bits_pht_index", "input", 5),
        ("io_in_bits_pht_tag", "input", 13),
        ("io_in_bits_region_paddr", "input", 40),
        ("io_in_bits_region_vaddr", "input", 40),
        ("io_in_bits_region_offset", "input", 4),
        ("io_out_ready", "input", 1),
        ("io_out_valid", "output", 1),
        ("io_out_bits_pht_index", "output", 5),
        ("io_out_bits_pht_tag", "output", 13),
        ("io_out_bits_region_paddr", "output", 40),
        ("io_out_bits_region_vaddr", "output", 40),
        ("io_out_bits_region_offset", "output", 4),
    ),
    "OverrideableQueue_1": (
        ("clock", "input", 1),
        ("reset", "input", 1),
        ("io_in_valid", "input", 1),
        ("io_in_bits_pht_index", "input", 5),
        ("io_in_bits_pht_tag", "input", 13),
        ("io_in_bits_region_bits", "input", 16),
        ("io_in_bits_region_bit_single", "input", 16),
        ("io_in_bits_region_offset", "input", 4),
        ("io_in_bits_access_cnt", "input", 4),
        ("io_in_bits_decr_mode", "input", 1),
        ("io_in_bits_single_update", "input", 1),
        ("io_in_bits_has_been_signal_updated", "input", 1),
        ("io_out_ready", "input", 1),
        ("io_out_valid", "output", 1),
        ("io_out_bits_pht_index", "output", 5),
        ("io_out_bits_pht_tag", "output", 13),
        ("io_out_bits_region_bits", "output", 16),
        ("io_out_bits_region_bit_single", "output", 16),
        ("io_out_bits_region_offset", "output", 4),
        ("io_out_bits_access_cnt", "output", 4),
        ("io_out_bits_decr_mode", "output", 1),
        ("io_out_bits_single_update", "output", 1),
        ("io_out_bits_has_been_signal_updated", "output", 1),
    ),
    "TimeAsync": (
        ("clock", "input", 1),
        ("reset", "input", 1),
        ("io_i_time_valid", "input", 1),
        ("io_i_time_bits", "input", 64),
        ("io_o_time_bits", "output", 64),
    ),
    "r4_qds_v2": (
        ("io_rem_i", "input", 6),
        ("io_quo_dig_o", "output", 5),
    ),
    "r4_qds_v2_spec": (
        ("io_rem_i", "input", 7),
        ("io_divisor_mul_pos_2_i", "input", 7),
        ("io_divisor_mul_pos_1_i", "input", 7),
        ("io_divisor_mul_neg_1_i", "input", 7),
        ("io_divisor_mul_neg_2_i", "input", 7),
        ("io_prev_quo_dig_i", "input", 5),
        ("io_quo_dig_o", "output", 5),
    ),
    "skidBufferConnect": (
        ("clock", "input", 1),
        ("reset", "input", 1),
        ("io_in_ready", "output", 1),
        ("io_in_valid", "input", 1),
        ("io_in_bits_flowMask", "input", 16),
        ("io_in_bits_data", "input", 128),
        ("io_in_bits_baseAddr", "input", 64),
        ("io_in_bits_uopAddr", "input", 64),
        ("io_in_bits_stride", "input", 128),
        ("io_in_bits_flowNum", "input", 5),
        ("io_in_bits_eew", "input", 2),
        ("io_in_bits_sew", "input", 3),
        ("io_in_bits_emul", "input", 3),
        ("io_in_bits_lmul", "input", 3),
        ("io_in_bits_instType", "input", 3),
        ("io_in_bits_indexedSplitOffset", "input", 5),
        ("io_in_bits_uop_ftqPtr_flag", "input", 1),
        ("io_in_bits_uop_ftqPtr_value", "input", 6),
        ("io_in_bits_uop_ftqOffset", "input", 4),
        ("io_in_bits_uop_fuOpType", "input", 9),
        ("io_in_bits_uop_vpu_vstart", "input", 8),
        ("io_in_bits_uop_vpu_vuopIdx", "input", 7),
        ("io_in_bits_uop_vpu_veew", "input", 2),
        ("io_in_bits_uop_uopIdx", "input", 7),
        ("io_in_bits_uop_pdest", "input", 8),
        ("io_in_bits_uop_robIdx_flag", "input", 1),
        ("io_in_bits_uop_robIdx_value", "input", 8),
        ("io_in_bits_uop_lqIdx_flag", "input", 1),
        ("io_in_bits_uop_lqIdx_value", "input", 7),
        ("io_in_bits_uop_sqIdx_flag", "input", 1),
        ("io_in_bits_uop_sqIdx_value", "input", 6),
        ("io_in_bits_preIsSplit", "input", 1),
        ("io_in_bits_mBIndex", "input", 4),
        ("io_in_bits_alignedType", "input", 3),
        ("io_in_bits_indexVlMaxInVd", "input", 8),
        ("io_in_bits_usLowBitsAddr", "input", 4),
        ("io_in_bits_usAligned128", "input", 1),
        ("io_in_bits_usMask", "input", 32),
        ("io_in_bits_isVecPartReplay", "input", 1),
        ("io_in_bits_vecReplayFlowMask", "input", 16),
        ("io_flush", "input", 1),
        ("io_out_ready", "input", 1),
        ("io_out_valid", "output", 1),
        ("io_out_bits_flowMask", "output", 16),
        ("io_out_bits_data", "output", 128),
        ("io_out_bits_baseAddr", "output", 64),
        ("io_out_bits_uopAddr", "output", 64),
        ("io_out_bits_stride", "output", 128),
        ("io_out_bits_flowNum", "output", 5),
        ("io_out_bits_eew", "output", 2),
        ("io_out_bits_sew", "output", 3),
        ("io_out_bits_emul", "output", 3),
        ("io_out_bits_lmul", "output", 3),
        ("io_out_bits_instType", "output", 3),
        ("io_out_bits_indexedSplitOffset", "output", 5),
        ("io_out_bits_uop_exceptionVec_5", "output", 1),
        ("io_out_bits_uop_exceptionVec_13", "output", 1),
        ("io_out_bits_uop_exceptionVec_19", "output", 1),
        ("io_out_bits_uop_exceptionVec_21", "output", 1),
        ("io_out_bits_uop_trigger", "output", 4),
        ("io_out_bits_uop_preDecodeInfo_isRVC", "output", 1),
        ("io_out_bits_uop_ftqPtr_flag", "output", 1),
        ("io_out_bits_uop_ftqPtr_value", "output", 6),
        ("io_out_bits_uop_ftqOffset", "output", 4),
        ("io_out_bits_uop_fuOpType", "output", 9),
        ("io_out_bits_uop_rfWen", "output", 1),
        ("io_out_bits_uop_fpWen", "output", 1),
        ("io_out_bits_uop_vpu_vstart", "output", 8),
        ("io_out_bits_uop_vpu_vuopIdx", "output", 7),
        ("io_out_bits_uop_vpu_veew", "output", 2),
        ("io_out_bits_uop_uopIdx", "output", 7),
        ("io_out_bits_uop_pdest", "output", 8),
        ("io_out_bits_uop_robIdx_flag", "output", 1),
        ("io_out_bits_uop_robIdx_value", "output", 8),
        ("io_out_bits_uop_storeSetHit", "output", 1),
        ("io_out_bits_uop_waitForRobIdx_flag", "output", 1),
        ("io_out_bits_uop_waitForRobIdx_value", "output", 8),
        ("io_out_bits_uop_loadWaitBit", "output", 1),
        ("io_out_bits_uop_loadWaitStrict", "output", 1),
        ("io_out_bits_uop_lqIdx_flag", "output", 1),
        ("io_out_bits_uop_lqIdx_value", "output", 7),
        ("io_out_bits_uop_sqIdx_flag", "output", 1),
        ("io_out_bits_uop_sqIdx_value", "output", 6),
        ("io_out_bits_preIsSplit", "output", 1),
        ("io_out_bits_mBIndex", "output", 4),
        ("io_out_bits_alignedType", "output", 3),
        ("io_out_bits_indexVlMaxInVd", "output", 8),
        ("io_out_bits_usLowBitsAddr", "output", 4),
        ("io_out_bits_usAligned128", "output", 1),
        ("io_out_bits_usMask", "output", 32),
        ("io_out_bits_isVecPartReplay", "output", 1),
        ("io_out_bits_vecReplayFlowMask", "output", 16),
    ),
    "PrintCommitIDModule": (
        ("hartID", "input", 6),
        ("commitID", "input", 40),
        ("dirty", "input", 1),
    ),
}
PORT_SPECS = LOCKED_PORT_SPECS
class UtilityResidualFamily(Elaboratable):
    def __init__(self, member: str = ('CSA3to2', 'CSA3to2_20', 'CSA3to2_24', 'CSA4to2', 'CSA_Nto2With3to2MainPipeline', 'ClockGate', 'DebugTransportModuleJTAG', 'IDPool', 'JtagStateMachine', 'JtagTapController', 'MaxPeriodFibonacciLFSR', 'MaxPeriodFibonacciLFSR_3', 'OverrideableQueue', 'OverrideableQueue_1', 'TimeAsync', 'r4_qds_v2', 'r4_qds_v2_spec', 'skidBufferConnect', 'PrintCommitIDModule')[0]) -> None:
        if member not in PORT_SPECS: raise ValueError(member)
        self.member = member; self.specs = PORT_SPECS[member]; self.ports = {n: Signal(w, name=n) for n, _d, w in self.specs}
    def elaborate(self, platform: Any) -> Module:
        del platform; module = Module()
        if "clock" in self.ports and "reset" in self.ports:
            domain = ClockDomain("sync", async_reset=True); domain.clk = self.ports["clock"]; domain.rst = self.ports["reset"]; module.domains += domain
        for n, d, _w in self.specs:
            if d == "output": module.d.comb += self.ports[n].eq(0)
        return module
def build_verilog(configuration: Any, injected_dependencies: Any) -> str:
    del injected_dependencies; member = ('CSA3to2', 'CSA3to2_20', 'CSA3to2_24', 'CSA4to2', 'CSA_Nto2With3to2MainPipeline', 'ClockGate', 'DebugTransportModuleJTAG', 'IDPool', 'JtagStateMachine', 'JtagTapController', 'MaxPeriodFibonacciLFSR', 'MaxPeriodFibonacciLFSR_3', 'OverrideableQueue', 'OverrideableQueue_1', 'TimeAsync', 'r4_qds_v2', 'r4_qds_v2_spec', 'skidBufferConnect', 'PrintCommitIDModule')[0]
    if isinstance(configuration, dict): member = str(configuration.get("module", member))
    elif isinstance(configuration, str): member = configuration
    top = UtilityResidualFamily(member); return verilog.convert(top, name=member, ports=[top.ports[n] for n, _d, _w in top.specs], emit_src=False)
def main() -> None: print(build_verilog({"module": ('CSA3to2', 'CSA3to2_20', 'CSA3to2_24', 'CSA4to2', 'CSA_Nto2With3to2MainPipeline', 'ClockGate', 'DebugTransportModuleJTAG', 'IDPool', 'JtagStateMachine', 'JtagTapController', 'MaxPeriodFibonacciLFSR', 'MaxPeriodFibonacciLFSR_3', 'OverrideableQueue', 'OverrideableQueue_1', 'TimeAsync', 'r4_qds_v2', 'r4_qds_v2_spec', 'skidBufferConnect', 'PrintCommitIDModule')[0]}, {}))
if __name__ == "__main__": main()
