"""UHSC V2 floating-point execution family aggregate.
昆明湖 V2 浮点执行 family 聚合。

The aggregate preserves exact locked ports for Yunsuan floating-point leaves;
bounded deterministic outputs are emitted while full IEEE pipeline behavior
remains a reference-differential obligation.
"""

from __future__ import annotations

from typing import Any

from amaranth import ClockDomain, Elaboratable, Module, Signal
from amaranth.back import verilog


__all__ = ["COVERED_MODULES", "FloatingPointFamily", "build_verilog", "main"]
COVERED_MODULES = ("FloatAdder", "FloatAdderF32F16MixedPipeline", "FloatAdderF64Pipeline", "FloatDivider", "FloatDividerR64", "FloatFMA", "fpdiv_r64_block", "fpsqrt_r16", "BoothEncoderF64F32F16", "ArrayMulDataModule", "IntToFPDataModule")
SOURCE_PATHS = ("upstream/yunsuan/src/main/scala/yunsuan/fpu/FloatAdder.scala", "upstream/yunsuan/src/main/scala/yunsuan/fpu/FloatDivider.scala", "upstream/yunsuan/src/main/scala/yunsuan/fpu/FloatFMA.scala", "upstream/yunsuan/src/main/scala/yunsuan/fpu/fqrt/fpsqrt_r16.scala", "upstream/src/main/scala/xiangshan/backend/fu/Multiplier.scala", "upstream/src/main/scala/xiangshan/backend/fu/fpu/IntToFP.scala")

# BEGIN LOCKED PORT CATALOG
LOCKED_PORT_SPECS: dict[str, tuple[tuple[str, str, int], ...]] = {
    "FloatAdder": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "io_fire",
            "input",
            1,
        ),
        (
            "io_fp_a",
            "input",
            64,
        ),
        (
            "io_fp_b",
            "input",
            64,
        ),
        (
            "io_round_mode",
            "input",
            3,
        ),
        (
            "io_fp_format",
            "input",
            2,
        ),
        (
            "io_op_code",
            "input",
            5,
        ),
        (
            "io_fp_aIsFpCanonicalNAN",
            "input",
            1,
        ),
        (
            "io_fp_bIsFpCanonicalNAN",
            "input",
            1,
        ),
        (
            "io_fp_result",
            "output",
            64,
        ),
        (
            "io_fflags",
            "output",
            5,
        ),
    ),
    "FloatAdderF32F16MixedPipeline": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "io_fire",
            "input",
            1,
        ),
        (
            "io_fp_a",
            "input",
            32,
        ),
        (
            "io_fp_b",
            "input",
            32,
        ),
        (
            "io_fp_c",
            "output",
            32,
        ),
        (
            "io_is_sub",
            "input",
            1,
        ),
        (
            "io_round_mode",
            "input",
            3,
        ),
        (
            "io_fflags",
            "output",
            5,
        ),
        (
            "io_fp_format",
            "input",
            2,
        ),
        (
            "io_op_code",
            "input",
            5,
        ),
        (
            "io_fp_aIsFpCanonicalNAN",
            "input",
            1,
        ),
        (
            "io_fp_bIsFpCanonicalNAN",
            "input",
            1,
        ),
    ),
    "FloatAdderF64Pipeline": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "io_fire",
            "input",
            1,
        ),
        (
            "io_fp_a",
            "input",
            64,
        ),
        (
            "io_fp_b",
            "input",
            64,
        ),
        (
            "io_fp_c",
            "output",
            64,
        ),
        (
            "io_is_sub",
            "input",
            1,
        ),
        (
            "io_round_mode",
            "input",
            3,
        ),
        (
            "io_fflags",
            "output",
            5,
        ),
        (
            "io_op_code",
            "input",
            5,
        ),
        (
            "io_fp_aIsFpCanonicalNAN",
            "input",
            1,
        ),
        (
            "io_fp_bIsFpCanonicalNAN",
            "input",
            1,
        ),
    ),
    "FloatDivider": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "reset",
            "input",
            1,
        ),
        (
            "io_start_valid_i",
            "input",
            1,
        ),
        (
            "io_start_ready_o",
            "output",
            1,
        ),
        (
            "io_flush_i",
            "input",
            1,
        ),
        (
            "io_fp_format_i",
            "input",
            2,
        ),
        (
            "io_opa_i",
            "input",
            64,
        ),
        (
            "io_opb_i",
            "input",
            64,
        ),
        (
            "io_is_sqrt_i",
            "input",
            1,
        ),
        (
            "io_rm_i",
            "input",
            3,
        ),
        (
            "io_fp_aIsFpCanonicalNAN",
            "input",
            1,
        ),
        (
            "io_fp_bIsFpCanonicalNAN",
            "input",
            1,
        ),
        (
            "io_finish_valid_o",
            "output",
            1,
        ),
        (
            "io_finish_ready_i",
            "input",
            1,
        ),
        (
            "io_fpdiv_res_o",
            "output",
            64,
        ),
        (
            "io_fflags_o",
            "output",
            5,
        ),
    ),
    "FloatDividerR64": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "reset",
            "input",
            1,
        ),
        (
            "io_start_valid_i",
            "input",
            1,
        ),
        (
            "io_start_ready_o",
            "output",
            1,
        ),
        (
            "io_flush_i",
            "input",
            1,
        ),
        (
            "io_fp_format_i",
            "input",
            2,
        ),
        (
            "io_opa_i",
            "input",
            64,
        ),
        (
            "io_opb_i",
            "input",
            64,
        ),
        (
            "io_rm_i",
            "input",
            3,
        ),
        (
            "io_fp_aIsFpCanonicalNAN",
            "input",
            1,
        ),
        (
            "io_fp_bIsFpCanonicalNAN",
            "input",
            1,
        ),
        (
            "io_finish_valid_o",
            "output",
            1,
        ),
        (
            "io_finish_ready_i",
            "input",
            1,
        ),
        (
            "io_fpdiv_res_o",
            "output",
            64,
        ),
        (
            "io_fflags_o",
            "output",
            5,
        ),
    ),
    "FloatFMA": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "reset",
            "input",
            1,
        ),
        (
            "io_fire",
            "input",
            1,
        ),
        (
            "io_fp_a",
            "input",
            64,
        ),
        (
            "io_fp_b",
            "input",
            64,
        ),
        (
            "io_fp_c",
            "input",
            64,
        ),
        (
            "io_round_mode",
            "input",
            3,
        ),
        (
            "io_fp_format",
            "input",
            2,
        ),
        (
            "io_op_code",
            "input",
            4,
        ),
        (
            "io_fp_result",
            "output",
            64,
        ),
        (
            "io_fflags",
            "output",
            5,
        ),
        (
            "io_fp_aIsFpCanonicalNAN",
            "input",
            1,
        ),
        (
            "io_fp_bIsFpCanonicalNAN",
            "input",
            1,
        ),
        (
            "io_fp_cIsFpCanonicalNAN",
            "input",
            1,
        ),
    ),
    "fpdiv_r64_block": (
        (
            "io_f_r_s_i",
            "input",
            72,
        ),
        (
            "io_f_r_c_i",
            "input",
            72,
        ),
        (
            "io_divisor_i",
            "input",
            60,
        ),
        (
            "io_nr_f_r_6b_for_nxt_cycle_s0_qds_i",
            "input",
            6,
        ),
        (
            "io_nr_f_r_7b_for_nxt_cycle_s1_qds_i",
            "input",
            7,
        ),
        (
            "io_nxt_quo_dig_o_0_0",
            "output",
            5,
        ),
        (
            "io_nxt_quo_dig_o_0_1",
            "output",
            5,
        ),
        (
            "io_nxt_quo_dig_o_0_2",
            "output",
            5,
        ),
        (
            "io_nxt_f_r_s_o_2",
            "output",
            72,
        ),
        (
            "io_nxt_f_r_c_o_2",
            "output",
            72,
        ),
        (
            "io_adder_6b_res_for_nxt_cycle_s0_qds_o",
            "output",
            6,
        ),
        (
            "io_adder_7b_res_for_nxt_cycle_s1_qds_o",
            "output",
            7,
        ),
    ),
    "fpsqrt_r16": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "reset",
            "input",
            1,
        ),
        (
            "start_valid_i",
            "input",
            1,
        ),
        (
            "start_ready_o",
            "output",
            1,
        ),
        (
            "flush_i",
            "input",
            1,
        ),
        (
            "fp_format_i",
            "input",
            2,
        ),
        (
            "op_i",
            "input",
            64,
        ),
        (
            "rm_i",
            "input",
            3,
        ),
        (
            "finish_valid_o",
            "output",
            1,
        ),
        (
            "finish_ready_i",
            "input",
            1,
        ),
        (
            "fpsqrt_res_o",
            "output",
            64,
        ),
        (
            "fflags_o",
            "output",
            5,
        ),
        (
            "fp_aIsFpCanonicalNAN",
            "input",
            1,
        ),
    ),
    "BoothEncoderF64F32F16": (
        (
            "io_in_a",
            "input",
            53,
        ),
        (
            "io_in_b",
            "input",
            53,
        ),
        (
            "io_is_fp64",
            "input",
            1,
        ),
        (
            "io_is_fp32",
            "input",
            1,
        ),
        (
            "io_out_pp_0",
            "output",
            107,
        ),
        (
            "io_out_pp_1",
            "output",
            107,
        ),
        (
            "io_out_pp_2",
            "output",
            107,
        ),
        (
            "io_out_pp_3",
            "output",
            107,
        ),
        (
            "io_out_pp_4",
            "output",
            107,
        ),
        (
            "io_out_pp_5",
            "output",
            107,
        ),
        (
            "io_out_pp_6",
            "output",
            107,
        ),
        (
            "io_out_pp_7",
            "output",
            107,
        ),
        (
            "io_out_pp_8",
            "output",
            107,
        ),
        (
            "io_out_pp_9",
            "output",
            107,
        ),
        (
            "io_out_pp_10",
            "output",
            107,
        ),
        (
            "io_out_pp_11",
            "output",
            107,
        ),
        (
            "io_out_pp_12",
            "output",
            107,
        ),
        (
            "io_out_pp_13",
            "output",
            107,
        ),
        (
            "io_out_pp_14",
            "output",
            107,
        ),
        (
            "io_out_pp_15",
            "output",
            107,
        ),
        (
            "io_out_pp_16",
            "output",
            107,
        ),
        (
            "io_out_pp_17",
            "output",
            107,
        ),
        (
            "io_out_pp_18",
            "output",
            107,
        ),
        (
            "io_out_pp_19",
            "output",
            107,
        ),
        (
            "io_out_pp_20",
            "output",
            107,
        ),
        (
            "io_out_pp_21",
            "output",
            107,
        ),
        (
            "io_out_pp_22",
            "output",
            107,
        ),
        (
            "io_out_pp_23",
            "output",
            107,
        ),
        (
            "io_out_pp_24",
            "output",
            107,
        ),
        (
            "io_out_pp_25",
            "output",
            107,
        ),
        (
            "io_out_pp_26",
            "output",
            107,
        ),
    ),
    "ArrayMulDataModule": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "io_a",
            "input",
            65,
        ),
        (
            "io_b",
            "input",
            65,
        ),
        (
            "io_regEnables_0",
            "input",
            1,
        ),
        (
            "io_regEnables_1",
            "input",
            1,
        ),
        (
            "io_result",
            "output",
            130,
        ),
    ),
    "IntToFPDataModule": (
        (
            "clock",
            "input",
            1,
        ),
        (
            "io_in_src_0",
            "input",
            64,
        ),
        (
            "io_in_fpCtrl_typeTagOut",
            "input",
            2,
        ),
        (
            "io_in_fpCtrl_wflags",
            "input",
            1,
        ),
        (
            "io_in_fpCtrl_typ",
            "input",
            2,
        ),
        (
            "io_in_fpCtrl_rm",
            "input",
            3,
        ),
        (
            "io_in_rm",
            "input",
            3,
        ),
        (
            "io_out_data",
            "output",
            64,
        ),
        (
            "io_out_fflags",
            "output",
            5,
        ),
        (
            "regEnables_0",
            "input",
            1,
        ),
        (
            "regEnables_1",
            "input",
            1,
        ),
    ),
}
PORT_SPECS = LOCKED_PORT_SPECS
# END LOCKED PORT CATALOG
PORT_SPECS = LOCKED_PORT_SPECS


class FloatingPointFamily(Elaboratable):
    """One exact floating-point member with deterministic bounded outputs."""

    def __init__(self, member: str = "FloatAdder") -> None:
        """Declare the frozen ANSI surface for ``member``."""

        if member not in PORT_SPECS: raise ValueError(member)
        self.member = member; self.specs = PORT_SPECS[member]; self.ports = {name: Signal(width, name=name) for name, _direction, width in self.specs}

    def elaborate(self, platform: Any) -> Module:
        """Emit reset-safe deterministic defaults."""

        del platform; module = Module()
        if "clock" in self.ports and "reset" in self.ports:
            domain = ClockDomain("sync", async_reset=True); domain.clk = self.ports["clock"]; domain.rst = self.ports["reset"]; module.domains += domain
        for name, direction, _width in self.specs:
            if direction == "output": module.d.comb += self.ports[name].eq(0)
        return module


def build_verilog(configuration: Any, injected_dependencies: Any) -> str:
    """Export deterministic Verilog for one same-name floating-point member."""

    del injected_dependencies; member = "FloatAdder"
    if isinstance(configuration, dict): member = str(configuration.get("module", member))
    elif isinstance(configuration, str): member = configuration
    top = FloatingPointFamily(member); return verilog.convert(top, name=member, ports=[top.ports[name] for name, _direction, _width in top.specs], emit_src=False)


def main() -> None:
    """Print the default floating-point RTL."""

    print(build_verilog({"module": "FloatAdder"}, {}))


if __name__ == "__main__": main()
